import { useEffect, useState } from 'react'
import { api } from '../api/client'
import { OmniDrawer } from '../components/OmniDrawer'
import { Actions } from '../features/actions/Actions'
import { Accounts } from '../features/accounts/Accounts'
import { Intelligence } from '../features/intelligence/Intelligence'
import { Map } from '../features/map/Map'
import { Monitor } from '../features/monitor/Monitor'
import { Today } from '../features/today/Today'
import type { Account, Account360, Alert, MapRecord, MonitorHealth, PublicLocation, Signal, WorkItem } from '../types/api'
import '../design/tokens.css'; import '../design/app.css'; import '../design/mobile.css'
type Surface = 'today' | 'accounts' | 'intelligence' | 'map' | 'actions' | 'monitor'
const nav: Array<[Surface, string]> = [['today', 'Today'], ['accounts', 'Accounts'], ['intelligence', 'Intelligence'], ['map', 'Map'], ['actions', 'Actions'], ['monitor', 'Monitor']]
export default function App() {
  const [surface, setSurface] = useState<Surface>('today'); const [accounts, setAccounts] = useState<Account[]>([]); const [alerts, setAlerts] = useState<Alert[]>([]); const [signals, setSignals] = useState<Signal[]>([]); const [records, setRecords] = useState<MapRecord[]>([]); const [publicLocations, setPublicLocations] = useState<PublicLocation[]>([]); const [mapSignals, setMapSignals] = useState<Signal[]>([]); const [layers, setLayers] = useState<string[]>([]); const [detail, setDetail] = useState<Account360>(); const [items, setItems] = useState<WorkItem[]>([]); const [actionWarning, setActionWarning] = useState('Actions are session-only.'); const [monitor, setMonitor] = useState<MonitorHealth>(); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  const select = async (id: string) => { try { setError(''); setDetail(await api.account(id)); setSurface('accounts') } catch (err) { setError(err instanceof Error ? err.message : 'Account context unavailable.') } }
  useEffect(() => { void Promise.all([api.accounts(), api.today(), api.intelligence(), api.map(), api.actions(), api.monitor()]).then(([accountData, today, intelligence, map, actionData, monitorData]) => { setAccounts(accountData.accounts); setAlerts(today.commercial_alerts); setSignals(intelligence.signals); setRecords(map.records); setPublicLocations(map.public_locations); setMapSignals(map.intelligence_signals); setLayers(map.layers); setItems(actionData.items); setActionWarning(actionData.warning); setMonitor(monitorData) }).catch(err => setError(err instanceof Error ? err.message : 'Canonical API unavailable.')).finally(() => setLoading(false)) }, [])
  if (loading) return <main className="app-shell"><div className="loading-stage"><span className="eyebrow">Loading governed context</span><h1>Preparing Omni Prospect</h1><p>Resolving public evidence and simulated POC context.</p></div></main>
  const richRecords = records.filter(record => accounts.find(account => account.id === record.account_id)?.is_rich_scenario)
  const richAlerts = alerts.filter(alert => accounts.find(account => account.id === alert.account_id)?.is_rich_scenario)
  const content = surface === 'accounts' ? <Accounts accounts={accounts} detail={detail} onSelect={id => void select(id)} /> : surface === 'intelligence' ? <Intelligence signals={signals} accounts={accounts} onAccount={id => void select(id)} /> : surface === 'map' ? <Map records={richRecords} publicLocations={publicLocations.filter(location => accounts.find(account => account.id === location.account_id)?.is_rich_scenario)} layers={layers} signals={mapSignals} onAccount={id => void select(id)} /> : surface === 'actions' ? <Actions items={items} onItem={item => setItems(old => [...old.filter(value => value.id !== item.id), item])} alerts={richAlerts} accounts={accounts} signals={signals} warning={actionWarning} onAccount={id => void select(id)} /> : surface === 'monitor' ? <Monitor health={monitor} onAccount={id => void select(id)} onIntelligence={() => setSurface('intelligence')} /> : <Today alerts={richAlerts} signals={signals} accounts={accounts} onAccount={id => void select(id)} onAction={alert => { setSurface('actions'); setError(`Ready to create action for ${accounts.find(account => account.id === alert.account_id)?.name ?? 'selected account'}.`) }} />
  return <main className="app-shell"><header className="topbar"><button className="wordmark" onClick={() => setSurface('today')}>BTX <span>OMNI</span></button><details className="mode"><summary>POC mode · Real public market data with simulated BTX commercial context</summary><p>Publicly verified: company identity, facilities, events, and legitimate public contacts. Simulated BTX context: commercial history, CRM, scoring, quotes, and actions. Needs research and Unavailable are explicit.</p></details><nav aria-label="Primary navigation">{nav.map(([id, label]) => <button key={id} className={surface === id ? 'active' : ''} onClick={() => setSurface(id)}>{label}</button>)}</nav></header>{error && <div className="api-notice">{error}</div>}{content}<OmniDrawer accountId={detail?.account.id} accountName={detail?.account.name ?? detail?.account.legal_name} surface={surface} /></main>
}
