import { useCallback, useEffect, useState } from 'react'
import { api } from '../api/client'
import { OmniDrawer } from '../components/OmniDrawer'
import { Actions } from '../features/actions/Actions'
import { Accounts } from '../features/accounts/Accounts'
import { Intelligence } from '../features/intelligence/Intelligence'
import { Map } from '../features/map/Map'
import { Monitor } from '../features/monitor/Monitor'
import { Today } from '../features/today/Today'
import type { Account, Account360, Alert, BtxMapFacility, MapIntelligence, MapRecord, MonitorHealth, OmniContext, OmniSurface, PublicLocation, Signal, WorkItem } from '../types/api'
import '../design/tokens.css'; import '../design/app.css'; import '../design/mobile.css'
type Surface = 'today' | 'accounts' | 'intelligence' | 'map' | 'actions' | 'monitor'
const nav: Array<[Surface, string]> = [['today', 'Today'], ['accounts', 'Accounts'], ['intelligence', 'Intelligence'], ['map', 'Map'], ['actions', 'Actions'], ['monitor', 'Monitor']]
export default function App() {
  const [surface, setSurface] = useState<Surface>('today'); const [accounts, setAccounts] = useState<Account[]>([]); const [alerts, setAlerts] = useState<Alert[]>([]); const [signals, setSignals] = useState<Signal[]>([]); const [records, setRecords] = useState<MapRecord[]>([]); const [publicLocations, setPublicLocations] = useState<PublicLocation[]>([]); const [btxFacilities, setBtxFacilities] = useState<BtxMapFacility[]>([]); const [mapSignals, setMapSignals] = useState<MapIntelligence[]>([]); const [layers, setLayers] = useState<string[]>([]); const [detail, setDetail] = useState<Account360>(); const [items, setItems] = useState<WorkItem[]>([]); const [actionWarning, setActionWarning] = useState('Actions are session-only.'); const [monitor, setMonitor] = useState<MonitorHealth>(); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [selectedEventId, setSelectedEventId] = useState<string>(); const [selectedMapAccountId, setSelectedMapAccountId] = useState<string>(); const [selectedMapFacilityId, setSelectedMapFacilityId] = useState<string>(); const [selectedActionId, setSelectedActionId] = useState<string>()
  const clearSelectedEvent = useCallback(() => setSelectedEventId(undefined), [])
  const clearMapSelection = useCallback(() => { setSelectedMapAccountId(undefined); setSelectedMapFacilityId(undefined) }, [])
  const clearSelectedAction = useCallback(() => setSelectedActionId(undefined), [])
  const select = async (id: string) => { try { setError(''); clearSelectedEvent(); clearMapSelection(); clearSelectedAction(); setDetail(await api.account(id)); setSurface('accounts') } catch (err) { setError(err instanceof Error ? err.message : 'Account context unavailable.') } }
  useEffect(() => { void Promise.all([api.accounts(), api.today(), api.intelligence(), api.map(), api.actions(), api.monitor()]).then(([accountData, today, intelligence, map, actionData, monitorData]) => { setAccounts(accountData.accounts); setAlerts(today.commercial_alerts); setSignals(intelligence.signals); setRecords(map.accounts); setPublicLocations(map.facilities); setBtxFacilities(map.btx_facilities); setMapSignals(map.intelligence); setLayers(map.layers); setItems(actionData.items); setActionWarning(actionData.warning); setMonitor(monitorData) }).catch(err => setError(err instanceof Error ? err.message : 'Canonical API unavailable.')).finally(() => setLoading(false)) }, [])
  if (loading) return <main className="app-shell"><div className="loading-stage"><span className="eyebrow">Loading governed context</span><h1>Preparing Omni Prospect</h1><p>Resolving public evidence and simulated POC context.</p></div></main>
  const richAlerts = alerts.filter(alert => accounts.find(account => account.id === alert.account_id)?.is_rich_scenario)
  const content = surface === 'accounts' ? <Accounts accounts={accounts} detail={detail} onSelect={id => void select(id)} /> : surface === 'intelligence' ? <Intelligence signals={signals} accounts={accounts} onAccount={id => void select(id)} onEventSelect={setSelectedEventId} /> : surface === 'map' ? <Map records={records} publicLocations={publicLocations} btxFacilities={btxFacilities} layers={layers} signals={mapSignals} onAccount={id => void select(id)} onMapAccountSelect={id => { setSelectedMapAccountId(id); setSelectedMapFacilityId(undefined) }} onMapFacilitySelect={(facilityId, accountId) => { setSelectedMapFacilityId(facilityId); setSelectedMapAccountId(accountId) }} /> : surface === 'actions' ? <Actions items={items} onItem={item => setItems(old => [...old.filter(value => value.id !== item.id), item])} alerts={richAlerts} accounts={accounts} signals={signals} warning={actionWarning} onAccount={id => void select(id)} onActionSelect={setSelectedActionId} /> : surface === 'monitor' ? <Monitor health={monitor} onAccount={id => void select(id)} onIntelligence={() => { clearSelectedEvent(); clearMapSelection(); clearSelectedAction(); setSurface('intelligence') }} /> : <Today alerts={richAlerts} signals={signals} accounts={accounts} onAccount={id => void select(id)} onAction={alert => { clearSelectedEvent(); clearMapSelection(); clearSelectedAction(); setSurface('actions'); setError(`Ready to create action for ${accounts.find(account => account.id === alert.account_id)?.name ?? 'selected account'}.`) }} />
  const omniSurface: OmniSurface = detail && surface === 'accounts' ? 'ACCOUNT_DETAIL' : ({ today: 'TODAY', accounts: 'ACCOUNTS', intelligence: 'INTELLIGENCE', map: 'MAP', actions: 'ACTIONS', monitor: 'TODAY' } as const)[surface]
  const selectedAccountId = detail?.account.id ?? (surface === 'map' ? selectedMapAccountId : undefined)
  const omniContext: OmniContext = { surface: omniSurface, selected_account_id: selectedAccountId, selected_event_id: surface === 'intelligence' ? selectedEventId : undefined, selected_facility_id: surface === 'map' ? selectedMapFacilityId : undefined, selected_action_id: surface === 'actions' ? selectedActionId : undefined }
  const selectedAccount = accounts.find(account => account.id === selectedAccountId)
  return <main className="app-shell"><header className="topbar"><button className="wordmark" onClick={() => { clearSelectedEvent(); clearMapSelection(); clearSelectedAction(); setSurface('today'); setDetail(undefined) }}>BTX <span>OMNI</span></button><details className="mode"><summary>POC mode · Real public market data with simulated BTX commercial context</summary><p>Publicly verified: company identity, facilities, events, and legitimate public contacts. Simulated BTX context: commercial history, CRM, scoring, quotes, and actions. Needs research and Unavailable are explicit.</p></details><nav aria-label="Primary navigation">{nav.map(([id, label]) => <button key={id} className={surface === id ? 'active' : ''} onClick={() => { clearSelectedEvent(); clearMapSelection(); clearSelectedAction(); setSurface(id); if (id !== 'accounts') setDetail(undefined) }}>{label}</button>)}</nav></header>{error && <div className="api-notice">{error}</div>}{content}<OmniDrawer accountId={selectedAccountId} accountName={detail?.account.name ?? detail?.account.legal_name ?? selectedAccount?.name ?? selectedAccount?.legal_name} context={omniContext} /></main>
}
