import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const app = readFileSync(new URL('../src/app/App.tsx', import.meta.url), 'utf8')
const destinations = readFileSync(new URL('../src/app/destinations.ts', import.meta.url), 'utf8')
const mobileStyles = readFileSync(new URL('../src/design/mobile.css', import.meta.url), 'utf8')
const omniStyles = readFileSync(new URL('../src/components/omni-drawer.css', import.meta.url), 'utf8')
const ui = readFileSync(new URL('../src/components/UI.tsx', import.meta.url), 'utf8')
const uiStyles = readFileSync(new URL('../src/components/ui.css', import.meta.url), 'utf8')
const client = readFileSync(new URL('../src/api/client.ts', import.meta.url), 'utf8')
const map = readFileSync(new URL('../src/features/map/Map.tsx', import.meta.url), 'utf8')
const mapFilters = readFileSync(new URL('../src/features/map/MapFilterPanel.tsx', import.meta.url), 'utf8')
const mapPresentation = readFileSync(new URL('../src/features/map/mapPresentation.ts', import.meta.url), 'utf8')
const mapAccountDetails = readFileSync(new URL('../src/features/map/MapAccountDetails.tsx', import.meta.url), 'utf8')
const mapCanvas = readFileSync(new URL('../src/features/map/MapCanvas.tsx', import.meta.url), 'utf8')
const itineraryPlanner = readFileSync(new URL('../src/features/map/ItineraryPlanner.tsx', import.meta.url), 'utf8')
const mapModel = readFileSync(new URL('../src/features/map/mapModel.ts', import.meta.url), 'utf8')
const apiTypes = readFileSync(new URL('../src/types/api.ts', import.meta.url), 'utf8')
const actions = readFileSync(new URL('../src/features/actions/Actions.tsx', import.meta.url), 'utf8')
const suggestions = readFileSync(new URL('../src/features/actions/SuggestionList.tsx', import.meta.url), 'utf8')
const accounts = readFileSync(new URL('../src/features/accounts/Accounts.tsx', import.meta.url), 'utf8')
const intelligence = readFileSync(new URL('../src/features/intelligence/Intelligence.tsx', import.meta.url), 'utf8')
const intelligenceBriefing = readFileSync(new URL('../src/features/intelligence/IntelligenceBriefing.tsx', import.meta.url), 'utf8')
const today = readFileSync(new URL('../src/features/today/Today.tsx', import.meta.url), 'utf8')
const monitor = readFileSync(new URL('../src/features/monitor/Monitor.tsx', import.meta.url), 'utf8')
const signalBrief = readFileSync(new URL('../src/components/SignalBriefCard.tsx', import.meta.url), 'utf8')
const signalBriefModel = readFileSync(new URL('../src/components/signalBriefModel.ts', import.meta.url), 'utf8')
const communications = readFileSync(new URL('../src/features/communications/Communications.tsx', import.meta.url), 'utf8')
const settings = readFileSync(new URL('../src/features/settings/Settings.tsx', import.meta.url), 'utf8')
const federal = readFileSync(new URL('../src/features/intelligence/FederalProcurement.tsx', import.meta.url), 'utf8')
const governedExplanation = readFileSync(new URL('../src/components/GovernedExplanationDisclosure.tsx', import.meta.url), 'utf8')
const supportingEvidence = readFileSync(new URL('../src/components/SupportingEvidence.tsx', import.meta.url), 'utf8')
const relatedBtxActivity = readFileSync(new URL('../src/components/RelatedBtxActivity.tsx', import.meta.url), 'utf8')
const scoreSummary = readFileSync(new URL('../src/components/ScoreSummary.tsx', import.meta.url), 'utf8')

test('governed explanations are subordinate, truthful, and additive on seller detail surfaces', () => {
  assert.match(governedExplanation, /if \(!explanation\) return null/)
  assert.match(governedExplanation, /explanation\.assisted \? explanation\.disclosure/)
  assert.match(governedExplanation, /Key drivers/)
  assert.match(governedExplanation, /Limitations \/ missing context/)
  assert.match(accounts, /Why it matters/)
  assert.match(accounts, /organization\.classification_basis/)
  assert.match(scoreSummary, /Coverage describes completeness and never raises this decision score/)
  assert.match(federal, /Why this opportunity is relevant/)
  assert.match(federal, /Federal Opportunity Relevance/)
  assert.match(federal, /item\.relevance\.calibration_label/)
  assert.match(signalBrief, /Program, components and possible BTX fit/)
  assert.match(signalBrief, /Why this technical fit may matter/)
  assert.match(signalBrief, /MODEL_INFERRED|display\(match\.basis\)/)
  assert.match(signalBrief, /Controlled BTX match/)
  assert.match(signalBrief, /Applicable BU/)
  assert.match(signalBrief, /technical_opportunity\.governed_explanation/)
  assert.match(accounts, /Why this relationship path may be useful/)
  assert.match(accounts, /explanation=\{path\.governed_explanation\}/)
  assert.match(accounts, /Evidence · \$\{path\.truth_label\} · \$\{path\.evidence\.length\}/)
  assert.doesNotMatch(`${accounts}\n${federal}\n${signalBrief}\n${governedExplanation}`, /PWin|win probability|warm introduction/)
})

test('canonical navigation and mobile core flow are present', () => {
  for (const surface of ['Today', 'Customers & Prospects', 'Intelligence', 'Map', 'Actions', 'OmniDrawer']) assert.match(app, new RegExp(surface))
  assert.match(app, /onAccount=\{\(id\) => void select\(id\)\}/)
})

test('frontend uses only canonical Omni Prospect API routes', () => {
  for (const route of ['/accounts', '/today', '/intelligence', '/map', '/actions', '/omni']) assert.match(client, new RegExp(route))
  assert.doesNotMatch(client, /\/v1|\/v2|\/poc/)
  assert.doesNotMatch(app, /BTX_ACTION_(SALESPERSON|MANAGER)_TOKEN/)
})

test('mobile-first layout prevents horizontal overflow and exposes responsive Omni workspaces', () => {
  assert.match(mobileStyles, /grid-template-columns:\s*repeat\(6,/)
  assert.match(mobileStyles, /safe-area-inset-bottom/)
  assert.match(mobileStyles, /--touch-target/)
  assert.match(omniStyles, /\.quick-omni\s*\{/)
  assert.match(omniStyles, /\.full-omni\s*\{/)
  assert.match(omniStyles, /safe-area-inset-bottom/)
})

test('asynchronous warning notices announce failures and wrap provider diagnostics', () => {
  assert.match(ui, /tone === 'info' \? 'status' : 'alert'/)
  assert.match(uiStyles, /\.ui-notice\s*\{[\s\S]*display:\s*grid/)
  assert.match(uiStyles, /\.ui-notice-content[\s\S]*overflow-wrap:\s*anywhere/)
  assert.match(itineraryPlanner, /Driving estimates are unavailable because the route service is not enabled/)
  assert.match(itineraryPlanner, /setFailure\(routeFailureMessage\(error\)\)/)
})

test('live Monitor observations use the canonical intelligence and map surfaces', () => {
  assert.match(app, /setMapSignals\(value\.intelligence\)/)
  assert.match(map, /public-intelligence geography/)
  assert.match(map, /Intelligence/)
  for (const key of ['accounts', 'today', 'intelligence', 'actions', 'communications', 'settings']) assert.ok(app.includes(`load('${key}', api.${key}(signal)`))
  assert.match(app, /workspaceSettings\?\.capabilities\.view_source_health[\s\S]*api\.monitor\(controller\.signal\)/)
  assert.match(app, /load\('map', api\.map\(undefined, signal\)/)
  assert.doesNotMatch(app, /Promise\.allSettled/)
  assert.match(app, /return \(\) => controller\.abort\(\)/)
})

test('Technical Opportunity disclosure preserves the model hypothesis and controlled-match boundary', () => {
  assert.match(apiTypes, /TechnicalFitMatch/)
  assert.match(apiTypes, /POSSIBLE_MATCH_REVIEW_REQUIRED/)
  assert.match(signalBrief, /Program, components and possible BTX fit/)
  assert.match(signalBrief, /Controlled BTX match/)
  assert.match(signalBrief, /No controlled BTX capability match identified/)
  assert.doesNotMatch(signalBrief, /probability|supplier claim/i)
})

test('adaptive Organization 360 distinguishes relationship mode and progressive evidence', () => {
  assert.match(accounts, /Public professional contact research/)
  assert.match(app, /aria-label="Demonstration environment"/)
  assert.match(app, /Simulated data environment/)
  assert.match(accounts, /organization\.title/)
  assert.match(accounts, /organization\.mode === 'PROSPECT'/)
  assert.match(accounts, /No confirmed BTX commercial history is available for this Prospect/)
  assert.match(accounts, /Expansion pursuit/)
  assert.match(accounts, /<SupportingEvidence/)
  assert.match(supportingEvidence, /'View'\} supporting evidence/)
  assert.match(supportingEvidence, /aria-expanded=\{open\}/)
})

test('Customers and Prospects uses one semantic sortable table with bounded mobile overflow', () => {
  const styles = readFileSync(new URL('../src/features/accounts/accounts.css', import.meta.url), 'utf8')
  assert.match(accounts, /<table className="portfolio-data-table" aria-label="Customers and Prospects">/)
  assert.match(accounts, /<thead><tr>/)
  assert.match(accounts, /<tbody>/)
  for (const label of ['Customer / Prospect', 'Classification', 'Industry', 'Customer Health', 'Priority', 'Evidence']) assert.match(accounts, new RegExp(label))
  assert.doesNotMatch(accounts, /attractivenessSummary\(/)
  assert.match(accounts, /aria-sort=\{direction\(key\)\}/)
  assert.match(accounts, /shown\.slice\(safePage \* PAGE_SIZE/)
  assert.match(accounts, /compareKnown/)
  assert.match(styles, /position:sticky/)
  assert.match(styles, /overflow:auto/)
  assert.doesNotMatch(accounts, /portfolio-mobile-list/)
})

test('Customer 360 renders deterministic seller-facing canonical relationship paths', () => {
  assert.match(client, /relationships: \(accountId: string, signal\?: AbortSignal\) => request<AccountRelationships>\(`\/accounts\/\$\{accountId\}\/relationships\?depth=2`, \{ signal \}\)/)
  assert.match(accounts, /People and relationship paths/)
  assert.match(accounts, /How this organization is connected/)
  assert.match(accounts, /Public professional contact research remains separate/)
  assert.match(accounts, /does not establish a BTX relationship, introduction path, or relationship strength/)
  assert.match(accounts, /No eligible recorded relationship is currently available/)
  assert.match(accounts, /api\.relationships\(accountId, controller\.signal\)/)
  assert.match(accounts, /Recorded relationships/)
  assert.match(accounts, /Needs validation/)
  assert.match(accounts, /<RankedRelationships accountId=/)
  assert.match(accounts, /Reference connections retain their original evidence/)
  assert.match(accounts, /Why this relationship path may be useful/)
  assert.doesNotMatch(accounts, /function RelationshipGraph\(|relationship-graph-node/)
  assert.match(accounts, /No route requiring validation is currently available/)
  assert.match(accounts, /seller_projection/)
  assert.match(accounts, /path\.seller_rationale/)
  assert.match(accounts, /Why it matters:/)
  assert.match(accounts, /Suggested move:/)
  assert.doesNotMatch(accounts, /Canonical 2-hop path|validated warm paths|Request intro/)
  assert.doesNotMatch(accounts, /confidence score|strength percentage/)
})

test('Customer 360 renders backend-owned commercial source states without zero inference', () => {
  assert.match(accounts, /commercial_source_states/)
  assert.match(accounts, /No \$\{label\} record is linked to this canonical Customer/)
  assert.match(accounts, /\$\{label\} integration is not configured/)
  assert.match(accounts, /\$\{label\} context is currently unavailable/)
  assert.match(accounts, /source_state === 'AVAILABLE'/)
  assert.match(app, /Simulated data environment/)
})

test('Omni shares governed conversation state across Quick and Full responsive workspaces', () => {
  const drawer = readFileSync(new URL('../src/components/OmniDrawer.tsx', import.meta.url), 'utf8')
  assert.match(drawer, /No organization selected/)
  assert.match(drawer, /Clear/)
  assert.match(drawer, /What should I review today\?/)
  assert.match(drawer, /session_account_id/)
  assert.match(drawer, /citation_links/)
  assert.match(drawer, /Gemini not configured · structured evidence summary/)
  assert.match(drawer, /Gemini temporarily unavailable · structured evidence summary/)
  assert.match(drawer, /Use Actions to create or update work/)
  assert.match(drawer, /Open in Omni/)
  assert.match(drawer, /Back to Quick Omni/)
  assert.match(drawer, /Evidence &amp; sources/)
  assert.match(drawer, /Organization context/)
  assert.match(drawer, /titleId="full-omni-title"/)
  assert.match(ui, /aria-modal="true"/)
  assert.doesNotMatch(drawer, /triggerStorageKey|setPointerCapture|dragThreshold|clampTriggerPosition/)
})

test('all intelligence launch surfaces pass the persisted assessment contract to Omni', () => {
  assert.match(apiTypes, /interface OmniAssessmentSelection/)
  assert.match(apiTypes, /selected_assessment\?: OmniAssessmentSelection/)
  assert.match(today, /selected_assessment: selectedAssessment/)
  assert.match(intelligence, /selected_assessment: selectedBrief/)
  assert.match(map, /selected_assessment: selectedSignal/)
  assert.match(accounts, /selected_assessment: selectedAssessment/)
  assert.match(accounts, /initialAssessment/)
  assert.match(signalBrief, /Use in Omni/)
  assert.match(app, /viewContext\.selected_assessment\?\.event_id/)
  assert.match(app, /initialAssessment=\{locationAssessment\}/)
  assert.match(app, /assessment_id: location\.assessment\.assessmentId/)
})

test('map and action interactions remain touch-accessible and confirmation-safe', () => {
  assert.match(map, /Map controls/)
  assert.match(map, /Layers &amp; filters/)
  assert.match(mapFilters, /Reset filters/)
  assert.match(mapFilters, /Customer, Prospect or review state/)
  assert.match(mapPresentation, /Customers/)
  assert.match(mapPresentation, /Dormant customers/)
  assert.match(mapPresentation, /Relationship needs review/)
  assert.match(map, /Open Organization 360/)
  assert.match(mapCanvas, /AdvancedMarkerElement/)
  assert.match(mapCanvas, /VITE_GOOGLE_MAPS_API_KEY/)
  assert.match(mapCanvas, /Interactive map unavailable in this build/)
  assert.doesNotMatch(mapCanvas, /maplibre|MapLibre/)
  assert.match(mapModel, /validCoordinates/)
  assert.match(mapModel, /buildMapMarkers/)
  assert.doesNotMatch(mapModel, /google\.maps|AdvancedMarkerElement|MapLibre/)
  assert.doesNotMatch(mapModel, /Strategic Partnership|Industry Top 100|relationship.*proximity|attractiveness.*proximity/i)
  assert.match(mapModel, /DEFAULT_MAP_LAYERS.*customers.*prospects.*btx-facilities/)
  assert.match(mapModel, /markersForZoom/)
  assert.match(mapModel, /haversineMiles/)
  assert.match(mapModel, /3958\.7613/)
  assert.match(map, /<MapAccountDetails key=\{selectedRecord\.id\} record=\{selectedRecord\}/)
  assert.match(mapAccountDetails, /miles straight-line/)
  assert.match(map, /selectionFrame/)
  assert.match(mapModel, /Current collected intelligence/)
  assert.match(mapModel, /upcoming-intelligence/)
  assert.match(map, /Current collected intelligence/)
  assert.match(map, /Upcoming source-supported event/)
  assert.match(map, /SignalBriefCard brief=\{selectedSignal\}/)
  assert.match(apiTypes, /MapIntelligence extends MonitorSignalBrief/)
  assert.match(apiTypes, /marker_mode: 'CURRENT_COLLECTED' \| 'UPCOMING'/)
  assert.match(mapCanvas, /gmpClickable: true/)
  assert.match(mapCanvas, /VITE_MAP_TEST_MODE/)
  assert.match(mapCanvas, /aria-pressed/)
  assert.match(actions, /External workflow requires Manager approval/)
  assert.match(actions, /Approval does not change work status/)
  assert.match(mapCanvas, /Map unavailable/)
  assert.doesNotMatch(mapCanvas, /tile\.openstreetmap\.org/)
  assert.match(map, /onSelect=\{selectMarker\}/)
  assert.match(mapModel, /signal\.coordinates/)
  assert.match(actions, /Authorized principal/)
  assert.doesNotMatch(client, /actor_id/)
})

test('Actions workbench separates Suggestions from durable governed work', () => {
  assert.match(actions, /Suggestions recommend work/)
  assert.match(suggestions, /Recommendations are not Actions/)
  assert.match(actions, /Filter by priority/)
  assert.match(actions, /Filter by status/)
  assert.match(actions, /Evidence and history/)
  assert.match(actions, /EvidenceSource/)
  assert.match(actions, /convertSuggestion/)
  assert.match(suggestions, /api\.suggestionFeedback/)
  assert.match(suggestions, /Undo my feedback/)
  assert.match(suggestions, /Hidden and snoozed for me/)
  assert.match(suggestions, /idempotency_key: crypto\.randomUUID/)
  assert.match(suggestions, /expected_feedback_id: item\.feedback\?\.id/)
  assert.match(actions, /OPEN.*IN_PROGRESS.*COMPLETED.*CANCELED/)
  assert.match(actions, /priorityRank/)
})

test('Actions creation and editing use canonical Customers and role-aware controls', () => {
  assert.match(actions, /Create Action/)
  assert.match(actions, /Edit Action/)
  assert.match(actions, /principal\?\.role === 'MANAGER'/)
  assert.match(actions, /account_id: customerId/)
  assert.match(client, /X-BTX-Principal-Token/)
})

test('Intelligence distinguishes browser validation from publisher-blocked source checks', () => {
  assert.match(signalBrief, /evidenceState="Source reviewed"/)
  assert.match(signalBrief, /source=\{brief\.source_system\}/)
  assert.match(signalBrief, /timeZone: 'UTC'/)
  assert.match(intelligence, /curatedSignalBrief\(signal, byId\.get/)
  assert.match(signalBriefModel, /source_validation_state|seller_promotion_state: signal\.evidence_state/)
})

test('External Intelligence preserves governed priority, source modes, Radar, and procurement navigation', () => {
  assert.doesNotMatch(intelligence, /Today's Priority Signals|Backend ranked/)
  assert.match(intelligence, /saved_recent_signal_briefs/)
  assert.match(intelligence, /No fresh collection in this session · saved intelligence remains available/)
  assert.match(intelligence, /Tracked Customers & Prospects/)
  assert.match(intelligence, /Open the watchlist when you need to change the organization context for this review/)
  assert.match(intelligence, /Forward Radar/)
  assert.match(intelligence, /Future source-supported event dates only/)
  assert.match(intelligence, /Public Intelligence/)
  assert.match(intelligence, /Federal Procurement/)
  assert.match(intelligence, /new Date\(item\.relevant_event_timestamp\)\.getTime\(\) > Date\.now\(\)/)
  assert.match(intelligence, /State value=\{brief\.analysis_status/)
  assert.match(intelligence, /Research direction · not yet assessed/)
  assert.match(intelligence, /brief\.why_it_may_matter/)
  assert.doesNotMatch(intelligence, /CONNECTED public|BTX commercial context|SAMPLE BTX context/)
  assert.doesNotMatch(intelligence, /Confidence Fit|For BU 1 Sales Leadership|momentum percentage/i)
})

test('Federal opportunities preserve one governed context across seller workflows', () => {
  assert.match(federal, /Open organization profile/)
  assert.match(federal, /Open Strategic Partnership profile/)
  assert.match(federal, /Explore relationship route/)
  assert.match(federal, /Ask Omni about this opportunity/)
  assert.match(federal, /Create or review Action proposal/)
  assert.match(federal, /selected_federal_opportunity/)
  assert.match(accounts, /Potential joint pursuits/)
  assert.match(accounts, /Federal opportunity starting context/)
  assert.match(accounts, /graph shows only recorded canonical connections/i)
  assert.match(actions, /Federal opportunity context/)
  assert.match(app, /\['federal_assessment', assessment\.assessment_id\]/)
  assert.match(app, /assessment_version/)
  assert.match(app, /federal_route_type/)
  assert.match(client, /federalAssessment/)
})

test('Intelligence sends canonical selected event context to the shared Omni request and clears it on navigation', () => {
  const drawer = readFileSync(new URL('../src/components/OmniDrawer.tsx', import.meta.url), 'utf8')
  assert.match(intelligence, /onEventSelect/)
  assert.match(intelligence, /onSelect\(brief\)/)
  assert.match(intelligence, /selected === briefKey\(brief\)/)
  assert.match(intelligence, /account_id: selectedBrief\.canonical_account_ids\[0\]/)
  assert.match(app, /selectedEventId/)
  assert.match(app, /surface === ['"]intelligence['"] \|\| surface === ['"]today['"]/)
  assert.match(app, /onClick=\{\(\) => navigate\(destination\.surface\)\}/)
  assert.match(drawer, /\{ \.\.\.currentContext, relationship_selection: !portfolioQuestion && activeAccount \? currentContext\.relationship_selection : undefined, session_account_id/)
  assert.match(drawer, /conversationReferent/)
  assert.match(drawer, /conversation_referent: portfolioQuestion \? undefined : conversationReferent/)
  assert.match(drawer, /setConversationReferent\(response\.conversation_referent/)
  assert.match(drawer, /messages\.slice\(-6\)/)
  assert.match(drawer, /slice\(-1600\)/)
  assert.match(drawer, /waitForSelectedGovernedContext\(contextRef, text\)/)
  assert.match(drawer, /selected relationship is still refreshing/)
  assert.match(drawer, /selected Intelligence assessment is still refreshing/)
  assert.match(drawer, /AUTH_FAILED: ["']Gemini authentication unavailable/)
  assert.match(drawer, /TIMEOUT: ["']Gemini timed out/)
  assert.match(drawer, /QUOTA: ["']Gemini quota unavailable/)
})

test('Intelligence briefing uses canonical account context without substituting an unrelated account action', () => {
  assert.match(intelligence, /Open briefing/)
  assert.match(intelligence, /subview: ['"]brief['"]/)
  assert.match(intelligenceBriefing, /api\.account\(accountId, controller\.signal\)/)
  assert.match(intelligenceBriefing, /brief\.recommended_action \?\? brief\.what_to_watch/)
  assert.doesNotMatch(intelligenceBriefing, /brief\.recommended_action \?\? detail\?\.recommended_next_step/)
  assert.match(intelligenceBriefing, /do not establish that this public event applies/)
  assert.match(intelligenceBriefing, /Account creation is unavailable until canonical identity resolution succeeds/)
})

test('Map selection sends canonical Customer and facility context without inventing BTX Customer identity', () => {
  assert.match(map, /selectMarker = useCallback/)
  assert.match(map, /onMapFacilitySelect\(marker\.facilityId, marker\.accountId\)/)
  assert.match(map, /onMapAccountSelect\(marker\.accountId\)/)
  assert.match(mapModel, /facilityId: facility\.facility_id/)
  assert.match(mapModel, /accountId: facility\.account_id/)
  assert.match(app, /selectedMapAccountId/)
  assert.match(app, /selectedMapFacilityId/)
  assert.match(app, /selected_facility_id:\s*surface === ['"]map['"] \? selectedMapFacilityId : surface === ['"]accounts['"] \? location\.facilityId : undefined/)
  assert.match(app, /onClick=\{\(\) => navigate\(destination\.surface\)\}/)
})

test('Map test renderer accepts legacy and facility-scoped canonical account marker IDs', () => {
  assert.match(mapCanvas, /accountIdFromMarkerId/)
  assert.match(mapCanvas, /split\(/)
  assert.match(mapCanvas, /account:<accountId>:facility:<facilityId>/)
})

test('Actions sends the selected canonical work-item ID without leaking other passive selections', () => {
  assert.match(actions, /onActionSelect/)
  assert.match(actions, /onActionSelect\(selected\?\.id\)/)
  assert.match(actions, /setSelectedId\(item\.id\)/)
  assert.match(app, /selectedActionId/)
  assert.match(app, /selected_action_id:\s*surface === ['"]actions['"] \? selectedActionId : undefined/)
  assert.match(app, /onClick=\{\(\) => navigate\(destination\.surface\)\}/)
})

test('list surfaces publish only their current filters and bounded canonical visible IDs to Omni', () => {
  assert.match(accounts, /account_scope: 'RICH'/)
  assert.match(accounts, /market: industry/)
  assert.match(accounts, /paged\.map\(account => account\.id\)/)
  assert.match(accounts, /onOmniContext\(\{ active_filters: Object\.keys\(activeFilters\)\.length \? activeFilters : undefined, visible_record_ids: visibleRecordIds \}\)/)
  assert.match(intelligence, /ordered\.map\(\(item\) => item\.id\)\.slice\(0, 50\)/)
  assert.match(intelligence, /onOmniContext\(\{[\s\S]*active_filters: \{[\s\S]*Object\.fromEntries\(active\),[\s\S]*account_id: selectedBrief\.canonical_account_ids\[0\][\s\S]*visible_record_ids:/)
  assert.match(actions, /action_status: 'ACTIVE'/)
  assert.match(actions, /\(tab === 'SUGGESTIONS' \? scopedSuggestions : visible\)\.map\(item => item\.id\)\.slice\(0, 50\)/)
  assert.match(actions, /onOmniContext\(\{ active_filters: activeFilters, visible_record_ids:/)
  assert.match(today, /visibleIds = useMemo\(\(\) => \[\.\.\.new Set\(\[\.\.\.priority\.map/)
  assert.match(today, /\.slice\(0, 50\)/)
  assert.match(today, /active_filters: \{ market, priority_kind: filters\.kind, account_id: selectedEventAccountId \?\? filters\.accountId, business_unit_id: filters\.businessUnit \}/)
  assert.match(today, /watchOpen \? \[\.\.\.visibleCurrent/)
})

test('shell clears stale list, detail, and passive entity context across surface changes', () => {
  assert.match(app, /const navigate = useCallback\(\(id: Surface, recordHistory = true\) => \{[\s\S]*clearSelectedEvent\(\)[\s\S]*clearMapSelection\(\)[\s\S]*clearSelectedAction\(\)[\s\S]*clearViewContext\(\)[\s\S]*setDetail\(undefined\)[\s\S]*commitLocation\(\{ surface: id \}/)
  assert.match(app, /await api\.account\(id, controller\.signal\)[\s\S]*if \(controller\.signal\.aborted\) return[\s\S]*clearViewContext\(\)[\s\S]*setDetail\(federalAssessment[\s\S]*commitLocation\(next/)
  assert.match(app, /active_filters:[\s\S]*viewContext\.active_filters/)
  assert.match(app, /visible_record_ids:[\s\S]*viewContext\.visible_record_ids/)
})

test('curated public evidence is never labeled as synthetic demo', () => {
  assert.match(signalBrief, /Source reviewed/)
  assert.doesNotMatch(signalBrief, />CURATED PUBLIC</)
  assert.doesNotMatch(map, /CURATED_POC_PUBLIC|INDUSTRY_UPDATE|CONTRACT_AWARD/)
})

test('Source Health leads with administrator decisions and keeps operational truth disclosed', () => {
  assert.match(monitor, /schedulerLabel\(health\.scheduler_state\)/)
  assert.match(monitor, /Administrator operations/)
  assert.match(monitor, /Operator decision/)
  assert.match(monitor, /Last-good content/)
  assert.match(monitor, /not a claim about the total addressable market/)
  assert.match(monitor, /Run history and exact diagnostics/)
  assert.match(monitor, /Retained operational evidence/)
  assert.doesNotMatch(monitor, /SignalBriefCard|Stored public signal preview/)
  assert.match(monitor, /Source freshness and coverage/)
  assert.match(monitor, /Last successful check/)
  assert.match(monitor, /Awaiting continuation/)
})

test('Seller Command Center reuses governed Signal Briefs with market, Radar, and watch truth', () => {
  assert.match(today, /Your next commercial decisions/)
  assert.match(today, /Action priorities/)
  assert.match(today, /Needs validation/)
  assert.match(today, /Potential BTX relevance not yet established/)
  assert.match(today, /needs_validation_assessments/)
  assert.match(today, /Current public intelligence/)
  assert.match(today, /Market Hubs/)
  assert.match(today, /Today briefing is unavailable\. This is not zero activity/)
  assert.match(today, /Upcoming Radar/)
  assert.match(today, /System recommended · read only/)
  assert.match(today, /Unknown dates are not promoted into Radar/)
  assert.match(today, /priority_kind: filters\.kind/)
  assert.match(today, /setSelectedProgramId\(next \? brief\.canonical_program_id : undefined\)/)
  assert.match(today, /displayedPriority\.map/)
  assert.match(today, /pageSlice\(sortedPriority/)
  assert.match(today, /total action priorities/)
  assert.match(today, /priority\.slice\(0, 3\)\.map/)
  assert.match(today, /data-priority-id=\{item\.id\}/)
  assert.match(today, /alertById\.get\(item\.id\).*Create action/)
  assert.match(today, /selectedHub\?\.current_signal_ids/)
  assert.match(today, /selectedHub\?\.upcoming_signal_ids/)
  assert.match(today, /selectedHub\?\.watched_account_ids/)
  assert.match(today, /selectedHub\?\.watched_program_ids/)
  assert.match(today, /selectedHub\.source_coverage/)
  assert.match(today, /selectedHub\.gaps/)
  assert.match(today, /curated_reference_signal_ids/)
  assert.match(today, /item\.id === id && item\.data_mode === 'CURATED_PUBLIC'/)
  assert.doesNotMatch(today, /signals\.slice\(/)
  assert.match(today, /no substitute was shown/)
  assert.match(today, /SignalBriefCard/)
  assert.match(intelligence, /Why it matters/)
  assert.match(intelligence, /Evidence, freshness, and context/)
  assert.doesNotMatch(monitor, /SignalBriefCard/)
  assert.match(signalBrief, /Next decision/)
  assert.match(signalBrief, /View supporting evidence|SupportingEvidence/)
  assert.match(relatedBtxActivity, /Why Omni selected it/)
  assert.doesNotMatch(signalBrief, />CURATED_POC_PUBLIC<|>INDUSTRY_UPDATE<|canonical account/i)
})

test('target interaction primitives expose governed semantic and accessibility contracts', () => {
  for (const component of ['Button', 'IconButton', 'SearchInput', 'SelectInput', 'FilterChip', 'StatusBadge', 'Disclosure', 'EvidenceSource', 'ResponsiveTable', 'MobileListRow', 'Drawer', 'StatusMessage']) assert.match(ui, new RegExp(`export (?:const|function) ${component}`))
  assert.match(ui, /aria-busy=/)
  assert.match(ui, /aria-pressed=/)
  assert.match(ui, /aria-expanded=/)
  assert.match(ui, /aria-controls=/)
  assert.match(ui, /role="dialog"/)
  assert.match(ui, /Source link unavailable/)
  assert.match(ui, /Unavailable · needs research/)
  assert.match(ui, /aria-sort=/)
})

test('Communications keeps drafting, review, and delivery explicitly governed', () => {
  assert.match(communications, /loadedHistory\?\.version === historyVersion/)
  assert.match(communications, /Trigger → Draft → Human review → Approved send/)
  assert.match(communications, /Gemini can assist\s+with words, never authorization or delivery/)
  assert.match(communications, /Gemini proposes words only/)
  assert.match(communications, /Propose draft/)
  assert.match(communications, /Propose revision/)
  assert.match(communications, /Recipient unavailable/)
  assert.match(communications, /Manager review is required/)
  assert.match(communications, /Confirm send/)
  assert.match(communications, /createRetry\.current\?\.signature !== signature/)
  assert.match(communications, /idempotency_key: createRetry\.current\.key/)
  assert.match(communications, /expected_version: baseDraft!\.version/)
  assert.match(client, /confirmed=true&idempotency_key/)
  assert.match(client, /assistNewCommunication/)
  assert.doesNotMatch(communications, /autonomous send/i)
})

test('Settings presents backend-managed role and gates administrator diagnostics', () => {
  assert.match(settings, /Personal/)
  assert.match(settings, /Role & Access/)
  assert.match(settings, /Integrations/)
  assert.match(settings, /canInspectOperations/)
  assert.match(settings, /view_integration_diagnostics/)
  assert.match(settings, /cannot change or self-promote/)
  assert.match(settings, /Credentials and tokens are never returned/)
  assert.match(settings, /state === 'loading'/)
  assert.match(settings, /state === 'error'/)
  assert.match(settings, /Retry Settings/)
  assert.match(settings, /Safe release diagnostics/)
  assert.match(app, /surface === 'settings' \? \(/)
  assert.doesNotMatch(app, /surface === 'settings' && workspaceSettings/)
  assert.match(client, /credentials: 'include'/)
  assert.match(client, /X-CSRF-Token/)
  assert.match(client, /import\.meta\.env\.DEV/)
  assert.match(app, /authorizedDestinations\(navigationAuthority\)/)
  assert.match(destinations, /requiredCapability: 'source_health'/)
  assert.match(destinations, /desktop: 'primary', mobile: 'secondary'/)
})

test('target primitive CSS encodes focus, touch, responsive rows, and safe-area sheets', () => {
  const componentStyles = readFileSync(new URL('../src/components/ui.css', import.meta.url), 'utf8')
  assert.match(componentStyles, /--touch-target/)
  assert.match(componentStyles, /\.ui-mobile-row\s*\{[^}]*display:\s*none/s)
  assert.match(componentStyles, /@media\s*\(max-width:\s*760px\).*\.ui-mobile-row\s*\{[^}]*display:\s*grid/s)
  assert.match(componentStyles, /safe-area-inset-bottom/)
  assert.match(componentStyles, /\.ui-drawer\s*\{/)
})

test('shared search inputs use the full available mobile grid width', () => {
  assert.match(uiStyles, /\.ui-search\s*\{[^}]*grid-template-columns:\s*minmax\(0, 1fr\)/s)
  assert.doesNotMatch(uiStyles, /\.ui-search\s*\{[^}]*grid-template-columns:\s*auto\s+minmax\(0, 1fr\)/s)
})

test('sanitized reference classifications remain orthogonal and source-backed in Portfolio and Map', () => {
  assert.match(accounts, /btx_top_100/)
  assert.match(accounts, /BTX Top 100/)
  assert.match(mapFilters, /Strategic Partnership and shortlist/)
  assert.match(mapFilters, /Filters change the visible planning set only/)
  assert.match(map, /Added to your shortlist/)
  assert.match(mapModel, /!filters\.top100 \|\| record\.btx_top_100/)
  assert.doesNotMatch(mapModel, /priority.*top100|attractiveness.*top100/i)
})
