import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const app = readFileSync(new URL('../src/app/App.tsx', import.meta.url), 'utf8')
const mobileStyles = readFileSync(new URL('../src/design/mobile.css', import.meta.url), 'utf8')
const omniStyles = readFileSync(new URL('../src/components/omni-drawer.css', import.meta.url), 'utf8')
const ui = readFileSync(new URL('../src/components/UI.tsx', import.meta.url), 'utf8')
const client = readFileSync(new URL('../src/api/client.ts', import.meta.url), 'utf8')
const map = readFileSync(new URL('../src/features/map/Map.tsx', import.meta.url), 'utf8')
const mapCanvas = readFileSync(new URL('../src/features/map/MapCanvas.tsx', import.meta.url), 'utf8')
const mapModel = readFileSync(new URL('../src/features/map/mapModel.ts', import.meta.url), 'utf8')
const apiTypes = readFileSync(new URL('../src/types/api.ts', import.meta.url), 'utf8')
const actions = readFileSync(new URL('../src/features/actions/Actions.tsx', import.meta.url), 'utf8')
const accounts = readFileSync(new URL('../src/features/accounts/Accounts.tsx', import.meta.url), 'utf8')
const intelligence = readFileSync(new URL('../src/features/intelligence/Intelligence.tsx', import.meta.url), 'utf8')
const today = readFileSync(new URL('../src/features/today/Today.tsx', import.meta.url), 'utf8')
const monitor = readFileSync(new URL('../src/features/monitor/Monitor.tsx', import.meta.url), 'utf8')
const signalBrief = readFileSync(new URL('../src/components/SignalBriefCard.tsx', import.meta.url), 'utf8')
const signalBriefModel = readFileSync(new URL('../src/components/signalBriefModel.ts', import.meta.url), 'utf8')
const communications = readFileSync(new URL('../src/features/communications/Communications.tsx', import.meta.url), 'utf8')
const settings = readFileSync(new URL('../src/features/settings/Settings.tsx', import.meta.url), 'utf8')

test('canonical navigation and mobile core flow are present', () => {
  for (const surface of ['Today', 'Customers & Prospects', 'Intelligence', 'Map', 'Actions', 'OmniDrawer']) assert.match(app, new RegExp(surface))
  assert.match(app, /onAccount=\{\(id\) => void select\(id\)\}/)
})

test('frontend uses only canonical Omni Prospect API routes', () => {
  for (const route of ['/accounts', '/today', '/intelligence', '/map', '/actions', '/omni']) assert.match(client, new RegExp(route))
  assert.doesNotMatch(client, /\/v1|\/v2|\/poc/)
})

test('mobile-first layout prevents horizontal overflow and exposes responsive Omni workspaces', () => {
  assert.match(mobileStyles, /grid-template-columns:\s*repeat\(5,/)
  assert.match(mobileStyles, /safe-area-inset-bottom/)
  assert.match(mobileStyles, /--touch-target/)
  assert.match(omniStyles, /\.quick-omni\s*\{/)
  assert.match(omniStyles, /\.full-omni\s*\{/)
  assert.match(omniStyles, /safe-area-inset-bottom/)
})

test('live Monitor observations use the canonical intelligence and map surfaces', () => {
  assert.match(app, /setMapSignals\(mapResult\.value\.intelligence\)/)
  assert.match(map, /public-intelligence geography/)
  assert.match(map, /Intelligence/)
  assert.match(app, /Promise\.allSettled\(\[[\s\S]*api\.accounts\(\)[\s\S]*api\.today\(\)[\s\S]*api\.intelligence\(\)[\s\S]*api\.map\(\)[\s\S]*api\.actions\(\)[\s\S]*api\.communications\(\)[\s\S]*api\.settings\(\)/)
  assert.match(app, /api[\s\S]*\.monitor\(\)[\s\S]*\.then\(setMonitor\)[\s\S]*\.catch/)
})

test('Customer 360 distinguishes public evidence from simulated BTX context', () => {
  assert.match(accounts, /Public professional contact research/)
  assert.match(accounts, /Simulated BTX commercial context/)
  assert.match(accounts, /Customer Attractiveness · POC simulation/)
  assert.match(accounts, /Coverage/)
  assert.match(accounts, /Curated scenarios/)
})

test('Customer 360 renders deterministic seller-facing canonical relationship paths', () => {
  assert.match(client, /relationships: \(accountId: string\) => request<AccountRelationships>\(`\/accounts\/\$\{accountId\}\/relationships\?depth=2`\)/)
  assert.match(accounts, /Relationship Intelligence/)
  assert.match(accounts, /How this Customer is connected/)
  assert.match(accounts, /Public professional contact research remains separate/)
  assert.match(accounts, /does not establish a BTX relationship, introduction path, or relationship strength/)
  assert.match(accounts, /No canonical direct connection is currently available/)
  assert.match(accounts, /api\.relationships\(accountId\)/)
  assert.match(accounts, /Direct connections/)
  assert.match(accounts, /Connected paths/)
  assert.match(accounts, /No canonical connected path is currently available/)
  assert.match(accounts, /path\.presentation_state/)
  assert.match(accounts, /Why it matters:/)
  assert.match(accounts, /Suggested move:/)
  assert.doesNotMatch(accounts, /Canonical 2-hop path|validated warm paths|Request intro/)
})

test('Omni shares governed conversation state across Quick and Full responsive workspaces', () => {
  const drawer = readFileSync(new URL('../src/components/OmniDrawer.tsx', import.meta.url), 'utf8')
  assert.match(drawer, /No Customer selected/)
  assert.match(drawer, /Clear/)
  assert.match(drawer, /What should I review today\?/)
  assert.match(drawer, /session_account_id/)
  assert.match(drawer, /citation_links/)
  assert.match(drawer, /Gemini not configured · governed fallback/)
  assert.match(drawer, /Gemini temporarily unavailable · governed fallback/)
  assert.match(drawer, /Use the governed Actions workspace for mutations/)
  assert.match(drawer, /Open in Omni/)
  assert.match(drawer, /Back to Quick Omni/)
  assert.match(drawer, /Evidence &amp; sources/)
  assert.match(drawer, /Customer context/)
  assert.match(drawer, /titleId="full-omni-title"/)
  assert.match(ui, /aria-modal="true"/)
  assert.doesNotMatch(drawer, /triggerStorageKey|setPointerCapture|dragThreshold|clampTriggerPosition/)
})

test('map and action interactions remain touch-accessible and confirmation-safe', () => {
  assert.match(map, /Map controls/)
  assert.match(map, /Layers &amp; filters/)
  assert.match(map, /Clear filters/)
  assert.match(map, /Customer relationship/)
  assert.match(map, /Customers/)
  assert.match(map, /Customer/)
  assert.match(map, /Dormant customers/)
  assert.match(map, /Other researched/)
  assert.match(map, /View Customer/)
  assert.match(mapCanvas, /AdvancedMarkerElement/)
  assert.match(mapCanvas, /VITE_GOOGLE_MAPS_API_KEY/)
  assert.match(mapCanvas, /Map not configured/)
  assert.doesNotMatch(mapCanvas, /maplibre|MapLibre/)
  assert.match(mapModel, /validCoordinates/)
  assert.match(mapModel, /buildMapMarkers/)
  assert.doesNotMatch(mapModel, /google\.maps|AdvancedMarkerElement|MapLibre/)
  assert.doesNotMatch(mapModel, /Strategic Partnership|Industry Top 100|relationship.*proximity|attractiveness.*proximity/i)
  assert.match(mapModel, /DEFAULT_MAP_LAYERS.*customers.*prospects.*btx-facilities/)
  assert.match(mapModel, /markersForZoom/)
  assert.match(mapModel, /haversineMiles/)
  assert.match(mapModel, /3958\.7613/)
  assert.match(map, /miles straight-line/)
  assert.match(map, /selectionFrame/)
  assert.match(mapModel, /Current collected intelligence/)
  assert.match(mapModel, /upcoming-intelligence/)
  assert.match(map, /Current collected intelligence/)
  assert.match(map, /Upcoming source-supported event/)
  assert.match(map, /SignalBriefCard brief=\{selectedSignal\}/)
  assert.match(apiTypes, /MapIntelligence extends MonitorSignalBrief/)
  assert.match(apiTypes, /marker_mode: 'CURRENT_COLLECTED' \| 'UPCOMING'/)
  assert.match(mapCanvas, /gmpClickable: true/)
  assert.match(mapCanvas, /VITE_MAP_TEST_MODE/)
  assert.match(mapCanvas, /aria-pressed/)
  assert.match(actions, /External workflow requires Manager approval/)
  assert.match(actions, /Approval does not change work status/)
  assert.match(mapCanvas, /Map unavailable/)
  assert.doesNotMatch(mapCanvas, /tile\.openstreetmap\.org/)
  assert.match(map, /onSelect=\{selectMarker\}/)
  assert.match(mapModel, /signal\.coordinates/)
  assert.match(actions, /Authorized principal/)
  assert.doesNotMatch(client, /actor_id/)
})

test('Actions workbench separates Suggestions from durable governed work', () => {
  assert.match(actions, /Suggestions recommend work/)
  assert.match(actions, /Recommendations are not Actions/)
  assert.match(actions, /Filter by priority/)
  assert.match(actions, /Filter by status/)
  assert.match(actions, /Evidence and history/)
  assert.match(actions, /EvidenceSource/)
  assert.match(actions, /convertSuggestion/)
  assert.match(actions, /dismissSuggestion/)
  assert.match(actions, /OPEN.*IN_PROGRESS.*COMPLETED.*CANCELED/)
  assert.match(actions, /priorityRank/)
})

test('Actions creation and editing use canonical Customers and role-aware controls', () => {
  assert.match(actions, /Create Action/)
  assert.match(actions, /Edit Action/)
  assert.match(actions, /principal\?\.role === 'MANAGER'/)
  assert.match(actions, /account_id: customerId/)
  assert.match(client, /X-BTX-Principal-Token/)
})

test('Intelligence distinguishes browser validation from publisher-blocked source checks', () => {
  assert.match(signalBrief, /validationState=\{brief\.seller_promotion_state\}/)
  assert.match(signalBrief, /evidenceState=\{brief\.resolution_state\}/)
  assert.match(signalBrief, /source=\{brief\.source_system\}/)
  assert.match(signalBrief, /timeZone: 'UTC'/)
  assert.match(intelligence, /curatedSignalBrief\(signal, account\)/)
  assert.match(signalBriefModel, /source_validation_state|seller_promotion_state: signal\.evidence_state/)
})

test('Intelligence sends canonical selected event context to the shared Omni request and clears it on navigation', () => {
  const drawer = readFileSync(new URL('../src/components/OmniDrawer.tsx', import.meta.url), 'utf8')
  assert.match(intelligence, /onEventSelect/)
  assert.match(intelligence, /selectEvent\(signal\.id\)/)
  assert.match(intelligence, /selectedEventId === signal\.id \? 'selected' : ''/)
  assert.match(app, /selectedEventId/)
  assert.match(app, /surface === ['"]intelligence['"] \|\| surface === ['"]today['"]/)
  assert.match(app, /onClick=\{\(\) => navigate\(id\)\}/)
  assert.match(drawer, /\{ \.\.\.context, session_account_id/)
  assert.match(drawer, /conversationReferent/)
  assert.match(drawer, /conversation_referent: conversationReferent/)
  assert.match(drawer, /setConversationReferent\(response\.conversation_referent/)
  assert.match(drawer, /messages\.slice\(-6\)/)
  assert.match(drawer, /slice\(-1600\)/)
  assert.match(drawer, /AUTH_FAILED: ["']Gemini authentication unavailable/)
  assert.match(drawer, /TIMEOUT: ["']Gemini timed out/)
  assert.match(drawer, /QUOTA: ["']Gemini quota unavailable/)
})

test('Map selection sends canonical Customer and facility context without inventing BTX Customer identity', () => {
  assert.match(map, /selectMarker = useCallback/)
  assert.match(map, /onMapFacilitySelect\(marker\.facilityId, marker\.accountId\)/)
  assert.match(map, /onMapAccountSelect\(marker\.accountId\)/)
  assert.match(mapModel, /facilityId: facility\.facility_id/)
  assert.match(mapModel, /accountId: facility\.account_id/)
  assert.match(app, /selectedMapAccountId/)
  assert.match(app, /selectedMapFacilityId/)
  assert.match(app, /selected_facility_id:\s*surface === ['"]map['"] \? selectedMapFacilityId : undefined/)
  assert.match(app, /onClick=\{\(\) => navigate\(id\)\}/)
})

test('Actions sends the selected canonical work-item ID without leaking other passive selections', () => {
  assert.match(actions, /onActionSelect/)
  assert.match(actions, /onActionSelect\(selected\?\.id\)/)
  assert.match(actions, /setSelectedId\(item\.id\)/)
  assert.match(app, /selectedActionId/)
  assert.match(app, /selected_action_id:\s*surface === ['"]actions['"] \? selectedActionId : undefined/)
  assert.match(app, /onClick=\{\(\) => navigate\(id\)\}/)
})

test('list surfaces publish only their current filters and bounded canonical visible IDs to Omni', () => {
  assert.match(accounts, /account_scope: 'RICH'/)
  assert.match(accounts, /market: industry/)
  assert.match(accounts, /shown\.slice\(0, 50\)\.map\(account => account\.id\)/)
  assert.match(accounts, /onOmniContext\(\{ active_filters: Object\.keys\(activeFilters\)\.length \? activeFilters : undefined, visible_record_ids: visibleRecordIds \}\)/)
  assert.match(intelligence, /visible\.slice\(0, 50\)\.map\(signal => signal\.id\)/)
  assert.match(intelligence, /onOmniContext\(\{ active_filters: Object\.keys\(activeFilters\)\.length \? activeFilters : undefined, visible_record_ids: visibleRecordIds \}\)/)
  assert.match(actions, /action_status: 'ACTIVE'/)
  assert.match(actions, /visible\.map\(item => item\.id\)\.slice\(0, 50\)/)
  assert.match(actions, /onOmniContext\(\{ active_filters: activeFilters, visible_record_ids:/)
  assert.match(today, /visibleIds = useMemo\(\(\) => \[\.\.\.new Set\(\[\.\.\.priority\.map/)
  assert.match(today, /\.slice\(0, 50\)/)
  assert.match(today, /active_filters: market \? \{ market \} : undefined/)
})

test('shell clears stale list, detail, and passive entity context across surface changes', () => {
  assert.match(app, /const navigate = \(id: Surface\) => \{[\s\S]*clearSelectedEvent\(\)[\s\S]*clearMapSelection\(\)[\s\S]*clearSelectedAction\(\)[\s\S]*clearViewContext\(\)[\s\S]*setDetail\(undefined\)[\s\S]*setSurface\(id\)/)
  assert.match(app, /clearViewContext\(\)[\s\S]*setDetail\(await api\.account\(id\)\)[\s\S]*setSurface\(['"]accounts['"]\)/)
  assert.match(app, /active_filters:[\s\S]*viewContext\.active_filters/)
  assert.match(app, /visible_record_ids:[\s\S]*viewContext\.visible_record_ids/)
})

test('curated public evidence is never labeled as synthetic demo', () => {
  assert.match(signalBrief, /CURATED PUBLIC/)
  assert.doesNotMatch(map, /CURATED_POC_PUBLIC|INDUSTRY_UPDATE|CONTRACT_AWARD/)
})

test('Monitor keeps inactive collection separate from curated public preview signals', () => {
  assert.match(monitor, /schedulerLabel\(health\.scheduler_state\)/)
  assert.match(monitor, /Curated POC signal preview/)
  assert.match(monitor, /CURATED PUBLIC · NOT LIVE INGESTION/)
  assert.match(monitor, /No active scheduler is verified/)
  assert.match(monitor, /Open Customer 360/)
  assert.match(monitor, /Source freshness/)
  assert.match(monitor, /Last successful check/)
  assert.match(monitor, /signal_briefs\?\.filter/)
  assert.match(monitor, /brief\.freshness === ["']CURRENT["']/)
  assert.match(monitor, /No resolved, evidence-backed current signal brief is\s+seller-visible/)
})

test('Seller Command Center reuses governed Signal Briefs with market, Radar, and watch truth', () => {
  assert.match(today, /Seller Command Center/)
  assert.match(today, /Current Signal Briefs/)
  assert.match(today, /Upcoming Radar/)
  assert.match(today, /System recommended · read only/)
  assert.match(today, /Unknown dates are not promoted into Radar/)
  assert.match(today, /active_filters: market \? \{ market \} : undefined/)
  assert.match(today, /setSelectedProgramId\(next \? brief\.canonical_program_id : undefined\)/)
  assert.match(today, /priority\.map\(item => item\.kind === 'COMMERCIAL_REVIEW'/)
  assert.match(today, /data-priority-id=\{item\.id\}/)
  assert.match(today, /alertById\.get\(item\.id\).*Create action/)
  assert.match(today, /selectedHub\?\.current_signal_ids/)
  assert.match(today, /selectedHub\?\.upcoming_signal_ids/)
  assert.match(today, /selectedHub\?\.watched_account_ids/)
  assert.match(today, /selectedHub\?\.watched_program_ids/)
  assert.match(today, /selectedHub\.source_coverage/)
  assert.match(today, /selectedHub\.gaps/)
  assert.match(today, /curated_reference_signal_ids/)
  assert.match(today, /item\.id === id && item\.data_mode === 'CURATED_PUBLIC'/)
  assert.doesNotMatch(today, /signals\.slice\(/)
  assert.match(today, /no substitute was shown/)
  assert.match(today, /SignalBriefCard/)
  assert.match(intelligence, /SignalBriefCard/)
  assert.match(monitor, /SignalBriefCard/)
  assert.match(signalBrief, /Evidence, why it matters, and next step/)
  assert.match(signalBrief, /Language assisted; governed evidence unchanged/)
  assert.doesNotMatch(signalBrief, />CURATED_POC_PUBLIC<|>INDUSTRY_UPDATE<|canonical account/i)
})

test('target interaction primitives expose governed semantic and accessibility contracts', () => {
  for (const component of ['Button', 'IconButton', 'SearchInput', 'SelectInput', 'FilterChip', 'StatusBadge', 'Disclosure', 'EvidenceSource', 'ResponsiveTable', 'MobileListRow', 'Drawer', 'StatusMessage']) assert.match(ui, new RegExp(`export (?:const|function) ${component}`))
  assert.match(ui, /aria-busy=/)
  assert.match(ui, /aria-pressed=/)
  assert.match(ui, /aria-expanded=/)
  assert.match(ui, /aria-controls=/)
  assert.match(ui, /role="dialog"/)
  assert.match(ui, /Source link unavailable/)
  assert.match(ui, /Unavailable · needs research/)
  assert.match(ui, /aria-sort=/)
})

test('Communications keeps drafting, review, and delivery explicitly governed', () => {
  assert.match(communications, /Trigger → Draft → Human review → Approved send/)
  assert.match(communications, /Gemini can assist with words, never authorization or delivery/)
  assert.match(communications, /Recipient unavailable/)
  assert.match(communications, /Manager review is required/)
  assert.match(communications, /Confirm send/)
  assert.match(client, /confirmed=true&idempotency_key/)
  assert.doesNotMatch(communications, /autonomous send/i)
})

test('Settings presents backend-managed role and truthful integration state', () => {
  assert.match(settings, /Personal/)
  assert.match(settings, /Role & Access/)
  assert.match(settings, /Integrations/)
  assert.match(settings, /cannot change or self-promote/)
  assert.match(settings, /Credentials and tokens are never returned/)
  assert.match(settings, /state === 'loading'/)
  assert.match(settings, /state === 'error'/)
  assert.match(settings, /Retry Settings/)
  assert.match(settings, /Safe release diagnostics/)
  assert.match(app, /surface === 'settings' \? \(/)
  assert.doesNotMatch(app, /surface === 'settings' && workspaceSettings/)
  assert.match(client, /credentials: 'include'/)
  assert.match(client, /X-CSRF-Token/)
  assert.match(client, /import\.meta\.env\.DEV/)
  assert.match(app, /mobileNav = nav\.filter\(\(\[id\]\) =>[\s\S]*\[['"]today['"], ['"]accounts['"], ['"]intelligence['"], ['"]map['"], ['"]actions['"]\]/)
})

test('target primitive CSS encodes focus, touch, responsive rows, and safe-area sheets', () => {
  const componentStyles = readFileSync(new URL('../src/components/ui.css', import.meta.url), 'utf8')
  assert.match(componentStyles, /--touch-target/)
  assert.match(componentStyles, /\.ui-mobile-row\s*\{[^}]*display:\s*none/s)
  assert.match(componentStyles, /@media\s*\(max-width:\s*760px\).*\.ui-mobile-row\s*\{[^}]*display:\s*grid/s)
  assert.match(componentStyles, /safe-area-inset-bottom/)
  assert.match(componentStyles, /\.ui-drawer\s*\{/)
})

test('sanitized reference classifications remain orthogonal and source-backed in Portfolio and Map', () => {
  assert.match(accounts, /btx_top_100/)
  assert.match(accounts, /BTX Top 100/)
  assert.match(map, /BTX Top 100 uses the sanitized POC reference workbook/)
  assert.match(map, /Strategic Partnership and Industry Top 100 remain unavailable/)
  assert.match(mapModel, /!filters\.top100 \|\| record\.btx_top_100/)
  assert.doesNotMatch(mapModel, /priority.*top100|attractiveness.*top100/i)
})
