import { useCallback, useMemo, useState } from 'react'
import type { BtxMapFacility, MapAccountSegment, MapIntelligence, MapRecord, PublicLocation } from '../../types/api'
import { Button, Drawer, Empty, FilterChip, FilterTrigger, StatusBadge } from '../../components/UI'
import { MapCanvas } from './MapCanvas'
import { ALL_MAP_LAYERS, buildMapMarkers, filterMapRecords, toggleValue, type MapFilters, type MapLayer, type MapMarker } from './mapModel'

const relationships: Array<[MapAccountSegment, string]> = [['CURRENT_CLIENT', 'Customers'], ['DORMANT_CUSTOMER', 'Dormant customers'], ['PROSPECT', 'Prospects'], ['UNKNOWN', 'Other researched']]
const layerOptions: Array<[MapLayer, string]> = [['customers', 'Customers'], ['prospects', 'Prospects'], ['public-facilities', 'Public facilities'], ['btx-facilities', 'BTX facilities'], ['intelligence', 'Intelligence']]
const layerMarkerKind: Record<MapLayer, string> = { customers: 'customer', prospects: 'prospect', 'public-facilities': 'public-facility', 'btx-facilities': 'btx-facility', intelligence: 'intelligence' }
const defaults: MapFilters = { coverage: 'RICH', top100: false, industries: [], relationships: [], layers: ALL_MAP_LAYERS }

export function Map({ records, publicLocations, btxFacilities, layers, signals, onAccount, onMapAccountSelect, onMapFacilitySelect }: { records: MapRecord[]; publicLocations: PublicLocation[]; btxFacilities: BtxMapFacility[]; layers: string[]; signals: MapIntelligence[]; onAccount: (id: string) => void; onMapAccountSelect: (id?: string) => void; onMapFacilitySelect: (facilityId?: string, accountId?: string) => void }) {
  const [filters, setFilters] = useState<MapFilters>(defaults); const [selected, setSelected] = useState<MapMarker>(); const [controlsOpen, setControlsOpen] = useState(false)
  const visible = useMemo(() => filterMapRecords(records, filters), [records, filters]); const ids = useMemo(() => new Set(visible.map(record => record.account_id)), [visible])
  const facilities = useMemo(() => publicLocations.filter(location => ids.has(location.account_id)), [publicLocations, ids]); const intelligence = useMemo(() => signals.filter(signal => !signal.account_id || ids.has(signal.account_id)), [signals, ids])
  const markers = useMemo(() => buildMapMarkers(visible, facilities, btxFacilities, intelligence, filters.layers), [visible, facilities, btxFacilities, intelligence, filters.layers])
  const selectedRecord = selected?.accountId ? records.find(record => record.account_id === selected.accountId) : undefined
  const selectedFacility = selected?.facilityId ? [...publicLocations, ...btxFacilities].find(facility => facility.facility_id === selected.facilityId) : undefined
  const selectedSignal = selected?.eventId ? signals.find(signal => signal.event_id === selected.eventId) : undefined
  const selectMarker = useCallback((marker: MapMarker) => { setSelected(marker); if (marker.facilityId) onMapFacilitySelect(marker.facilityId, marker.accountId); else if (marker.accountId) onMapAccountSelect(marker.accountId) }, [onMapAccountSelect, onMapFacilitySelect])
  const clearSelection = () => { setSelected(undefined); onMapFacilitySelect() }
  const updateFilters = (next: MapFilters) => { setFilters(next); if (selected && !buildMapMarkers(filterMapRecords(records, next), publicLocations, btxFacilities, signals, next.layers).some(marker => marker.id === selected.id)) { setSelected(undefined); onMapFacilitySelect() } }
  const clearFilters = () => updateFilters(defaults); const changed = filters.coverage !== 'RICH' || filters.top100 || filters.industries.length > 0 || filters.relationships.length > 0 || filters.layers.length !== ALL_MAP_LAYERS.length
  const title = selectedRecord?.name ?? selectedFacility?.name ?? selectedSignal?.title ?? selected?.label
  return <div className="surface map-workspace">
    <div className="page-title map-title"><span className="eyebrow">National commercial geography</span><h1>Tactical Map</h1><p>Verified Customer, facility, and public-intelligence geography. Proximity never changes Customer Attractiveness.</p></div>
    <section className="map-stage" aria-label="Tactical Map V2 workspace">
      <MapCanvas markers={markers} selectedMarkerId={selected?.id} onSelect={selectMarker} />
      <div className="map-toolbar"><FilterTrigger active={changed} aria-expanded={controlsOpen} onClick={() => setControlsOpen(true)}>Layers &amp; filters</FilterTrigger><span>{markers.length} verified markers</span></div>
      <div className="map-active-filters" aria-label="Active map filters">{filters.coverage === 'RICH' && <FilterChip selected onClear={() => updateFilters({ ...filters, coverage: 'ALL' })}>Curated scenarios</FilterChip>}{filters.top100 && <FilterChip selected onClear={() => updateFilters({ ...filters, top100: false })}>BTX Top 100</FilterChip>}{filters.industries.map(value => <FilterChip key={value} selected onClear={() => updateFilters({ ...filters, industries: filters.industries.filter(item => item !== value) })}>{value}</FilterChip>)}{filters.relationships.map(value => <FilterChip key={value} selected onClear={() => updateFilters({ ...filters, relationships: filters.relationships.filter(item => item !== value) })}>{relationships.find(([id]) => id === value)?.[1] ?? value}</FilterChip>)}</div>
      {!markers.length && <div className="map-no-results"><Empty>No verified markers match the selected filters.</Empty><Button onClick={clearFilters}>Clear filters</Button></div>}
      <div className="map-legend" aria-label="Map legend">{layerOptions.filter(([id]) => filters.layers.includes(id)).map(([id, label]) => <span key={id}><i className={`map-legend-marker map-marker-${layerMarkerKind[id]}`} />{label}</span>)}</div>
      {selected && <aside className="map-selection" aria-label="Selected map location"><button className="map-selection-close" aria-label="Close selected map location" onClick={clearSelection}>×</button><span className="eyebrow">Selected {selected.kind.replace('-', ' ')}</span><h2>{title}</h2>{selectedRecord && <><div className="map-badges"><StatusBadge value={selectedRecord.account_segment === 'PROSPECT' ? 'Prospect' : 'Customer'} kind="entity" />{selectedRecord.btx_top_100 && <StatusBadge value="BTX Top 100" />}{selectedRecord.primary_markets.map(market => <StatusBadge key={market} value={market} />)}</div><p>{selectedRecord.location_truth_state.replaceAll('_', ' ')} coordinates</p><p>Nearest BTX facility: <strong>{selectedRecord.nearest_btx_facility?.name ?? 'Unavailable'}</strong></p></>}{selectedFacility && <p>{'city' in selectedFacility ? `${selectedFacility.city}, ${selectedFacility.region}` : 'Verified facility location'}</p>}{selectedSignal && <><StatusBadge value={selectedSignal.evidence_state ?? 'PUBLIC EVIDENCE'} kind="evidence" /><p>{selectedSignal.relevance ?? 'Relevance detail unavailable.'}</p>{selectedSignal.source_url && <a href={selectedSignal.source_url} target="_blank" rel="noreferrer">Inspect source →</a>}</>}{selected?.accountId && <Button variant="primary" size="touch" onClick={() => onAccount(selected.accountId!)}>View Customer</Button>}</aside>}
    </section>
    <Drawer open={controlsOpen} onClose={() => setControlsOpen(false)} titleId="map-filter-title" className="map-filter-sheet"><header><div><span className="eyebrow">Map controls</span><h2 id="map-filter-title">Layers &amp; filters</h2></div><Button variant="ghost" onClick={() => setControlsOpen(false)}>Close</Button></header>
      <fieldset><legend>Coverage</legend><FilterChip selected={filters.coverage === 'RICH'} onClick={() => updateFilters({ ...filters, coverage: 'RICH' })}>Curated scenarios</FilterChip><FilterChip selected={filters.coverage === 'ALL'} onClick={() => updateFilters({ ...filters, coverage: 'ALL' })}>All researched</FilterChip></fieldset>
      <fieldset><legend>Reference classifications</legend><FilterChip selected={filters.top100} onClick={() => updateFilters({ ...filters, coverage: 'ALL', top100: !filters.top100 })}>BTX Top 100</FilterChip></fieldset>
      <fieldset><legend>Customer relationship</legend>{relationships.map(([value, label]) => <FilterChip key={value} selected={filters.relationships.includes(value)} onClick={() => updateFilters({ ...filters, relationships: toggleValue(filters.relationships, value) })}>{label}</FilterChip>)}</fieldset>
      <fieldset><legend>Industry</legend>{layers.map(value => <FilterChip key={value} selected={filters.industries.includes(value)} onClick={() => updateFilters({ ...filters, industries: toggleValue(filters.industries, value) })}>{value}</FilterChip>)}</fieldset>
      <fieldset><legend>Marker layers</legend>{layerOptions.map(([value, label]) => <FilterChip key={value} selected={filters.layers.includes(value)} onClick={() => updateFilters({ ...filters, layers: toggleValue(filters.layers, value) })}>{label}</FilterChip>)}</fieldset>
      <div className="map-filter-actions"><Button onClick={clearFilters} disabled={!changed}>Clear filters</Button><Button variant="primary" onClick={() => setControlsOpen(false)}>Apply to map</Button></div>
      <p className="map-filter-boundary">BTX Top 100 uses the sanitized POC reference workbook. Strategic Partnership and Industry Top 100 remain unavailable until canonical sources exist.</p>
    </Drawer>
  </div>
}
