import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import type { BtxMapFacility, MapAccountSegment, MapIntelligence, MapRecord, PublicLocation } from '../../types/api'
import { Button, Drawer, Empty, FilterChip, FilterTrigger, StatusBadge } from '../../components/UI'
import { MapCanvas } from './MapCanvas'
import { MapAccountDetails } from './MapAccountDetails'
import { SignalBriefCard } from '../../components/SignalBriefCard'
import { DEFAULT_MAP_LAYERS, FULFILLMENT_LABELS, buildMapMarkers, filterMapRecords, filterMarkersByRadius, toggleValue, type MapFilters, type MapLayer, type MapMarker } from './mapModel'
import type { PendingMapAccount } from '../../types/api'
import type { MapViewSnapshot } from './mapModel'
import { ItineraryPlanner, type ItineraryPlannerHandle } from './ItineraryPlanner'
import { api } from '../../api/client'
import type { AccountPlanning } from '../../types/api'

const relationships: Array<[MapAccountSegment, string]> = [['CURRENT_CLIENT', 'Customers'], ['DORMANT_CUSTOMER', 'Dormant customers'], ['PROSPECT', 'Prospects'], ['UNKNOWN', 'Other researched']]
const layerOptions: Array<[MapLayer, string]> = [['customers', 'Customers'], ['prospects', 'Prospects'], ['public-facilities', 'Public facilities'], ['btx-facilities', 'BTX facilities'], ['intelligence', 'Intelligence']]
const layerMarkerKind: Record<MapLayer, string> = { customers: 'customer', prospects: 'prospect', 'public-facilities': 'public-facility', 'btx-facilities': 'btx-facility', intelligence: 'intelligence' }
const defaults: MapFilters = { coverage: 'ALL', top100: false, industries: [], relationships: [], layers: DEFAULT_MAP_LAYERS, signalTiming: ['CURRENT', 'UPCOMING'], strategicPartnership: 'ALL', shortlistOnly: false }

export function Map({ records, pendingAccounts = [], initialSnapshot, onSnapshot, publicLocations, btxFacilities, layers, signals, onAccount, onRelationships, onMapAccountSelect, onMapFacilitySelect, onMapEventSelect, onOmniContext }: { records: MapRecord[]; pendingAccounts?: PendingMapAccount[]; initialSnapshot?: MapViewSnapshot; onSnapshot?: (snapshot: MapViewSnapshot) => void; publicLocations: PublicLocation[]; btxFacilities: BtxMapFacility[]; layers: string[]; signals: MapIntelligence[]; onAccount: (id: string) => void; onRelationships: (id: string) => void; onMapAccountSelect: (id?: string) => void; onMapFacilitySelect: (facilityId?: string, accountId?: string) => void; onMapEventSelect?: (id?: string) => void; onOmniContext?: (context: { active_filters?: Record<string, string>; visible_record_ids?: string[]; selected_event_id?: string }) => void }) {
  const [filters, setFilters] = useState<MapFilters>(() => initialSnapshot?.filters ?? defaults); const [selectedSnapshot, setSelected] = useState<MapMarker | undefined>(() => initialSnapshot?.selected); const [controlsOpen, setControlsOpen] = useState(false); const [renderedMarkers, setRenderedMarkers] = useState<MapMarker[]>([])
  const [mobileView, setMobileView] = useState<'MAP' | 'LIST'>('MAP')
  const [resultsOpen, setResultsOpen] = useState(true)
  const [resultLimit, setResultLimit] = useState(40)
  const [planning, setPlanning] = useState<AccountPlanning>()
  const [planningError, setPlanningError] = useState(false)
  const itinerary = useRef<ItineraryPlannerHandle>(null)
  useEffect(() => {
    const controller = new AbortController()
    void api.accountPlanning(controller.signal).then(value => { if (!controller.signal.aborted) { setPlanning(value); setPlanningError(false) } }).catch(() => { if (!controller.signal.aborted) setPlanningError(true) })
    return () => controller.abort()
  }, [])
  const partnershipIds = useMemo(() => new Set(planning?.strategic_partnerships.map(item => item.account_id) ?? []), [planning])
  const shortlistIds = useMemo(() => new Set(planning?.shortlist.map(item => item.account_id) ?? []), [planning])
  const planningFilter = useCallback(<T extends { account_id: string },>(items: T[]) => items.filter(item =>
    ((filters.strategicPartnership ?? 'ALL') === 'ALL' || ((filters.strategicPartnership === 'ONLY') === partnershipIds.has(item.account_id)))
    && (!filters.shortlistOnly || shortlistIds.has(item.account_id))), [filters.shortlistOnly, filters.strategicPartnership, partnershipIds, shortlistIds])
  const visible = useMemo(() => planningFilter(filterMapRecords(records, filters)), [records, filters, planningFilter]); const ids = useMemo(() => new Set(visible.map(record => record.account_id)), [visible])
  const naicsOptions = useMemo(() => [...new Set([...records, ...pendingAccounts].flatMap(record => record.naics_assignments?.map(item => item.code) ?? []))].sort(), [records, pendingAccounts])
  const businessUnitOptions = useMemo(() => [...new Set([...records, ...pendingAccounts].flatMap(record => record.commercial_business_unit_ids ?? []))].sort(), [records, pendingAccounts])
  const fulfillmentOptions = useMemo(() => [...new Set([...records, ...pendingAccounts].flatMap(record => record.fulfillment_attention?.states ?? []))].sort(), [records, pendingAccounts])
  const pending = useMemo(() => planningFilter(filterMapRecords(pendingAccounts, filters)).filter(account => filters.layers.includes(account.account_segment === 'PROSPECT' ? 'prospects' : 'customers')), [pendingAccounts, filters, planningFilter])
  const facilities = useMemo(() => publicLocations.filter(location => ids.has(location.account_id)), [publicLocations, ids]); const intelligence = useMemo(() => signals.filter(signal => (!signal.account_id || ids.has(signal.account_id)) && filters.signalTiming.includes(signal.marker_mode === 'UPCOMING' ? 'UPCOMING' : 'CURRENT')), [filters.signalTiming, signals, ids])
  const allMarkers = useMemo(() => buildMapMarkers(visible, facilities, btxFacilities, intelligence, filters.layers), [visible, facilities, btxFacilities, intelligence, filters.layers])
  const selected = allMarkers.find(marker => marker.id === selectedSnapshot?.id)
  useEffect(() => { onSnapshot?.({ filters, selected }) }, [filters, selected, onSnapshot])
  useEffect(() => { onMapEventSelect?.(selected?.eventId); onMapFacilitySelect(selected?.facilityId, selected?.accountId) }, [selected, onMapEventSelect, onMapFacilitySelect])
  const focal = selected && selected.kind !== 'cluster' ? selected : undefined
  const markers = useMemo(() => filterMarkersByRadius(allMarkers, focal, filters.radiusMiles), [allMarkers, focal, filters.radiusMiles])
  const prioritizedMarkers = useMemo(() => {
    const representedAccounts = new Set<string>(); const firstAccountSites: MapMarker[] = []; const additionalSites: MapMarker[] = []
    for (const marker of markers) {
      if (marker.accountId && !representedAccounts.has(marker.accountId)) { representedAccounts.add(marker.accountId); firstAccountSites.push(marker) }
      else additionalSites.push(marker)
    }
    return [...firstAccountSites, ...additionalSites]
  }, [markers])
  const listedMarkers = prioritizedMarkers.slice(0, resultLimit)
  const selectedRecord = selected ? records.find(record => record.id === selected.id) ?? (selected.accountId ? records.find(record => record.account_id === selected.accountId && record.facility_id === selected.facilityId) : undefined) : undefined
  const selectedFacility = selected?.facilityId ? [...publicLocations, ...btxFacilities].find(facility => facility.facility_id === selected.facilityId) : undefined
  const selectedSignal = selected?.eventId ? signals.find(signal => signal.event_id === selected.eventId) : undefined
  const accountName = useCallback((id: string) => records.find(record => record.account_id === id)?.name ?? 'Open Customer', [records])
  const selectMarker = useCallback((marker: MapMarker) => { setSelected(marker); onMapEventSelect?.(marker.eventId); if (marker.facilityId) onMapFacilitySelect(marker.facilityId, marker.accountId); else if (marker.accountId) onMapAccountSelect(marker.accountId) }, [onMapAccountSelect, onMapEventSelect, onMapFacilitySelect])
  const clearSelection = () => { setSelected(undefined); onMapEventSelect?.(); onMapFacilitySelect() }
  const updateFilters = (next: MapFilters) => { setFilters(next); setResultLimit(40); if (selected && !buildMapMarkers(filterMapRecords(records, next), publicLocations, btxFacilities, signals, next.layers).some(marker => marker.id === selected.id)) { setSelected(undefined); onMapFacilitySelect() } }
  const clearFilters = () => updateFilters(defaults); const changed = filters.coverage !== 'ALL' || filters.top100 || filters.industries.length > 0 || filters.relationships.length > 0 || filters.layers.join() !== DEFAULT_MAP_LAYERS.join() || filters.signalTiming.length !== 2 || (filters.strategicPartnership ?? 'ALL') !== 'ALL' || Boolean(filters.shortlistOnly) || Boolean(filters.radiusMiles) || Boolean(filters.naicsCodes?.length) || Boolean(filters.businessUnitIds?.length) || Boolean(filters.fulfillmentStates?.length)
  const title = selectedRecord?.name ?? selectedFacility?.name ?? selectedSignal?.title ?? selected?.label
  const selectionFrame = useMemo(() => {
    if (selectedRecord) return buildMapMarkers([selectedRecord], publicLocations.filter(location => location.account_id === selectedRecord.account_id), btxFacilities.filter(facility => facility.facility_id === selectedRecord.nearest_btx_facility?.id), [], ['customers', 'prospects', 'public-facilities', 'btx-facilities'])
    return selectedFacility ? allMarkers.filter(marker => marker.id === selected?.id || marker.accountId === selected?.accountId) : undefined
  }, [allMarkers, btxFacilities, publicLocations, selected, selectedFacility, selectedRecord])
  useEffect(() => { onOmniContext?.({ active_filters: { coverage: filters.coverage, layers: filters.layers.join(','), markets: filters.industries.join(','), signal_timing: filters.signalTiming.join(','), strategic_partnership: filters.strategicPartnership ?? 'ALL', saved_shortlist: filters.shortlistOnly ? 'true' : '', radius_miles: filters.radiusMiles?.toString() ?? '', naics_codes: filters.naicsCodes?.join(',') ?? '', commercial_business_unit_ids: filters.businessUnitIds?.join(',') ?? '', fulfillment_states: filters.fulfillmentStates?.join(',') ?? '' }, visible_record_ids: renderedMarkers.filter(marker => marker.kind !== 'cluster').slice(0, 50).map(marker => marker.eventId ?? marker.accountId ?? marker.facilityId ?? marker.id), selected_event_id: selected?.eventId }) }, [filters, onOmniContext, renderedMarkers, selected?.eventId])
  return <div className="surface map-workspace">
    {Boolean(filters.fulfillmentStates?.length) && <div className="map-commercial-filters" aria-label="Active fulfillment filters">{filters.fulfillmentStates?.map(state => <FilterChip key={state} selected onClear={() => updateFilters({ ...filters, fulfillmentStates: filters.fulfillmentStates?.filter(value => value !== state) })}>{FULFILLMENT_LABELS[state] ?? state}</FilterChip>)}</div>}
    <div className="page-title map-title"><span className="eyebrow">National commercial geography</span><h1>Tactical Map</h1><p>Verified Customer, facility, and public-intelligence geography. Proximity never changes Customer Attractiveness.</p></div>
    <div className="map-mobile-switch" role="group" aria-label="Map display"><Button variant={mobileView === 'MAP' ? 'primary' : 'ghost'} aria-pressed={mobileView === 'MAP'} onClick={() => setMobileView('MAP')}>Map</Button><Button variant={mobileView === 'LIST' ? 'primary' : 'ghost'} aria-pressed={mobileView === 'LIST'} onClick={() => setMobileView('LIST')}>List</Button></div>
    <div className={`map-compose map-mobile-${mobileView.toLowerCase()} ${resultsOpen ? '' : 'map-results-collapsed'}`}>
    <section className="map-results" aria-label="Map results"><div className="map-results-heading"><h2>Sites and accounts</h2><Button variant="ghost" aria-expanded={resultsOpen} onClick={() => setResultsOpen(value => !value)}>{resultsOpen ? 'Collapse list' : 'Show list'}</Button></div><p>{markers.length} geographic results · {pending.length} accounts awaiting site verification{filters.radiusMiles ? ' (unknown locations cannot be evaluated against the radius)' : ''}.</p><ul>{listedMarkers.map(marker => <li key={marker.id}><button type="button" aria-pressed={selected?.id === marker.id} onClick={() => { selectMarker(marker); setMobileView('MAP') }}><strong>{marker.label}</strong><span>{marker.kind.replaceAll('-', ' ')} · inspect site</span></button></li>)}</ul>{resultLimit < markers.length && <Button className="map-results-more" onClick={() => setResultLimit((value) => Math.min(value + 40, markers.length))}>Show {Math.min(40, markers.length - resultLimit)} more · {markers.length - resultLimit} remaining</Button>}{pending.length > 0 && <details><summary>Location pending ({pending.length})</summary><p>These accounts remain available without assigning an unsupported headquarters or facility location.</p><ul>{pending.map(account => <li key={account.id}><button type="button" onClick={() => onAccount(account.account_id)}><strong>{account.name}</strong><span>{account.primary_markets.join(' · ')} · open Account 360</span></button></li>)}</ul></details>}</section>
    <section className="map-stage" aria-label="Tactical Map V2 workspace">
      <MapCanvas markers={markers} selectedMarkerId={selected?.id} selectionFrame={selectionFrame} onSelect={selectMarker} onVisibleMarkers={setRenderedMarkers} />
      <div className="map-toolbar"><Button className="map-results-reopen" variant="ghost" aria-expanded={resultsOpen} onClick={() => setResultsOpen(true)}>Show results</Button><FilterTrigger active={changed} aria-expanded={controlsOpen} onClick={() => setControlsOpen(true)}>Layers &amp; filters</FilterTrigger><Button onClick={() => itinerary.current?.open()}>Itinerary</Button><span>{markers.length} verified markers</span></div>
      <div className="map-active-filters" aria-label="Active map filters">{filters.coverage === 'RICH' && <FilterChip selected onClear={() => updateFilters({ ...filters, coverage: 'ALL' })}>Priority demo cohort</FilterChip>}{filters.top100 && <FilterChip selected onClear={() => updateFilters({ ...filters, top100: false })}>BTX Top 100</FilterChip>}{filters.strategicPartnership === 'ONLY' && <FilterChip selected onClear={() => updateFilters({ ...filters, strategicPartnership: 'ALL' })}>Only partnerships</FilterChip>}{filters.strategicPartnership === 'EXCLUDE' && <FilterChip selected onClear={() => updateFilters({ ...filters, strategicPartnership: 'ALL' })}>Exclude partnerships</FilterChip>}{filters.shortlistOnly && <FilterChip selected onClear={() => updateFilters({ ...filters, shortlistOnly: false })}>My growth &amp; research shortlist</FilterChip>}{filters.radiusMiles && <FilterChip selected onClear={() => updateFilters({ ...filters, radiusMiles: undefined })}>{filters.radiusMiles}-mile radius</FilterChip>}{filters.industries.map(value => <FilterChip key={value} selected onClear={() => updateFilters({ ...filters, industries: filters.industries.filter(item => item !== value) })}>{value}</FilterChip>)}{filters.relationships.map(value => <FilterChip key={value} selected onClear={() => updateFilters({ ...filters, relationships: filters.relationships.filter(item => item !== value) })}>{relationships.find(([id]) => id === value)?.[1] ?? value}</FilterChip>)}</div>
      {!markers.length && <div className="map-no-results"><Empty>No verified markers match the selected filters.</Empty><Button onClick={clearFilters}>Clear filters</Button></div>}
      <div className="map-legend" aria-label="Map legend">{layerOptions.filter(([id]) => filters.layers.includes(id)).map(([id, label]) => <span key={id}><i className={`map-legend-marker map-marker-${layerMarkerKind[id]}`} />{label}</span>)}</div>
      {selected && <aside className="map-selection" aria-label="Selected map location"><div className="map-selection-content"><button className="map-selection-close" aria-label="Close selected map location" onClick={clearSelection}>×</button><span className="eyebrow">Selected {selected.kind.replace('-', ' ')}</span><h2>{title}</h2>{selectedSignal ? <><StatusBadge value={selectedSignal.marker_mode === 'UPCOMING' ? 'Upcoming source-supported event' : 'Current collected intelligence'} kind="evidence" /><SignalBriefCard brief={selectedSignal} accountName={accountName} onAccount={onAccount} onUseInOmni={() => onMapEventSelect?.(selectedSignal.event_id)} selected /></> : <>{selectedRecord && <MapAccountDetails key={selectedRecord.id} record={selectedRecord} />}{selectedFacility && <><p>{'city' in selectedFacility ? `${selectedFacility.city}, ${selectedFacility.region}` : 'Verified facility location'}</p><p>{'location_type' in selectedFacility ? selectedFacility.location_type : 'BTX facility'} · verified coordinates</p>{'source_url' in selectedFacility && selectedFacility.source_url && <a href={selectedFacility.source_url} target="_blank" rel="noreferrer">Inspect location source →</a>}</>}{selected?.accountId && <div className="map-selection-actions">{selected.facilityId && <Button variant="primary" size="touch" onClick={() => itinerary.current?.add(selected)}>Add to itinerary</Button>}<Button size="touch" onClick={() => onAccount(selected.accountId!)}>View Customer 360</Button><Button size="touch" onClick={() => onRelationships(selected.accountId!)}>Relationship Intelligence</Button></div>}</>}</div></aside>}
    </section>
    </div>
    {(Boolean(filters.naicsCodes?.length) || Boolean(filters.businessUnitIds?.length)) && <div className="map-commercial-filters" aria-label="Active commercial map filters">{filters.naicsCodes?.map(code => <FilterChip key={code} selected onClear={() => updateFilters({ ...filters, naicsCodes: filters.naicsCodes?.filter(item => item !== code) })}>{`NAICS ${code}`}</FilterChip>)}{filters.businessUnitIds?.map(id => <FilterChip key={id} selected onClear={() => updateFilters({ ...filters, businessUnitIds: filters.businessUnitIds?.filter(item => item !== id) })}>{`BU ${id.replaceAll('-', ' ')}`}</FilterChip>)}</div>}
    <Drawer open={controlsOpen} onClose={() => setControlsOpen(false)} titleId="map-filter-title" className="map-filter-sheet"><header><div><span className="eyebrow">Map controls</span><h2 id="map-filter-title">Layers &amp; filters</h2></div><Button variant="ghost" onClick={() => setControlsOpen(false)}>Close</Button></header>
      <fieldset><legend>Coverage</legend><FilterChip selected={filters.coverage === 'ALL'} onClick={() => updateFilters({ ...filters, coverage: 'ALL' })}>All researched</FilterChip><FilterChip selected={filters.coverage === 'RICH'} onClick={() => updateFilters({ ...filters, coverage: 'RICH' })}>Priority demo cohort</FilterChip></fieldset>
      <fieldset><legend>Reference classifications</legend><FilterChip selected={filters.top100} onClick={() => updateFilters({ ...filters, coverage: 'ALL', top100: !filters.top100 })}>BTX Top 100</FilterChip></fieldset>
      <fieldset><legend>Saved account planning</legend>{planningError && <p role="alert">Saved planning is temporarily unavailable. Existing map results remain visible.</p>}{!planning && !planningError && <p role="status">Loading saved planning…</p>}<FilterChip disabled={!planning} selected={(filters.strategicPartnership ?? 'ALL') === 'EXCLUDE'} onClick={() => updateFilters({ ...filters, strategicPartnership: filters.strategicPartnership === 'EXCLUDE' ? 'ALL' : 'EXCLUDE' })}>Exclude partnerships</FilterChip><FilterChip disabled={!planning} selected={filters.strategicPartnership === 'ONLY'} onClick={() => updateFilters({ ...filters, strategicPartnership: filters.strategicPartnership === 'ONLY' ? 'ALL' : 'ONLY' })}>Only partnerships</FilterChip><FilterChip disabled={!planning} selected={Boolean(filters.shortlistOnly)} onClick={() => updateFilters({ ...filters, shortlistOnly: !filters.shortlistOnly })}>My growth &amp; research shortlist</FilterChip></fieldset>
      <fieldset><legend>Customer relationship</legend>{relationships.map(([value, label]) => <FilterChip key={value} selected={filters.relationships.includes(value)} onClick={() => updateFilters({ ...filters, relationships: toggleValue(filters.relationships, value) })}>{label}</FilterChip>)}</fieldset>
      <fieldset><legend>Industry</legend>{layers.map(value => <FilterChip key={value} selected={filters.industries.includes(value)} onClick={() => updateFilters({ ...filters, industries: toggleValue(filters.industries, value) })}>{value}</FilterChip>)}</fieldset>
      <fieldset><legend>NAICS account classification</legend><p>POC classifications, not verified site registrations.</p>{naicsOptions.length ? naicsOptions.map(value => <FilterChip key={value} selected={Boolean(filters.naicsCodes?.includes(value))} onClick={() => updateFilters({ ...filters, naicsCodes: toggleValue(filters.naicsCodes ?? [], value) })}>{value}</FilterChip>) : <p>No classified accounts available.</p>}</fieldset>
      <fieldset><legend>BTX BU commercial context</legend><p>Account-level scenario context; not site qualification or available capacity.</p>{businessUnitOptions.length ? businessUnitOptions.map(value => <FilterChip key={value} selected={Boolean(filters.businessUnitIds?.includes(value))} onClick={() => updateFilters({ ...filters, businessUnitIds: toggleValue(filters.businessUnitIds ?? [], value) })}>{value.replaceAll('-', ' ')}</FilterChip>) : <p>No commercial BU context available.</p>}</fieldset>
      <fieldset><legend>Fulfillment attention</legend><p>Recorded account-level obligations, not site capacity or a new delivery approval.</p>{fulfillmentOptions.map(value => <FilterChip key={value} selected={Boolean(filters.fulfillmentStates?.includes(value))} onClick={() => updateFilters({ ...filters, fulfillmentStates: toggleValue(filters.fulfillmentStates ?? [], value) })}>{FULFILLMENT_LABELS[value] ?? value}</FilterChip>)}</fieldset>
      <fieldset><legend>Marker layers</legend>{layerOptions.map(([value, label]) => <FilterChip key={value} selected={filters.layers.includes(value)} onClick={() => updateFilters({ ...filters, layers: toggleValue(filters.layers, value) })}>{label}</FilterChip>)}</fieldset>
      <fieldset><legend>Intelligence timing</legend><FilterChip selected={filters.signalTiming.includes('CURRENT')} onClick={() => updateFilters({ ...filters, signalTiming: toggleValue(filters.signalTiming, 'CURRENT') })}>Current intelligence</FilterChip><FilterChip selected={filters.signalTiming.includes('UPCOMING')} onClick={() => updateFilters({ ...filters, signalTiming: toggleValue(filters.signalTiming, 'UPCOMING') })}>Upcoming intelligence</FilterChip></fieldset>
      {focal && <fieldset><legend>Straight-line exploration radius</legend>{([30, 50, 100] as const).map(value => <FilterChip key={value} selected={filters.radiusMiles === value} onClick={() => updateFilters({ ...filters, radiusMiles: filters.radiusMiles === value ? undefined : value })}>{value} miles</FilterChip>)}</fieldset>}
      <div className="map-filter-actions"><Button onClick={clearFilters} disabled={!changed}>Clear filters</Button><Button variant="primary" onClick={() => setControlsOpen(false)}>Apply to map</Button></div>
      <p className="map-filter-boundary">BTX Top 100 uses the sanitized POC reference workbook. Strategic partnership uses the audited manager designation; the personal shortlist is private to the signed-in user. Industry Top 100 remains unavailable until a canonical source exists.</p>
    </Drawer>
    <ItineraryPlanner ref={itinerary} />
  </div>
}
