import { useMemo, useState } from 'react'
import type { MapRecord } from '../../types/api'
import { Panel, State } from '../../components/UI'

export function Map({ records, layers, onAccount }: { records: MapRecord[]; layers: string[]; onAccount: (id: string) => void }) {
  const [layer, setLayer] = useState('All'); const [relationship, setRelationship] = useState('All'); const [selected, setSelected] = useState<MapRecord>()
  const visible = useMemo(() => records.filter(record => (layer === 'All' || record.industry === layer) && (relationship === 'All' || record.relationship === relationship)), [records, layer, relationship])
  return <div className="surface"><div className="page-title"><span className="eyebrow">National commercial graph</span><h1>Map</h1><p>External market rank, canonical relationship state, and seller-planning proximity remain separate facts.</p></div><div className="map-layout"><div><Panel title="Layer controls"><div className="control-group"><span>Industry</span><div className="chips"><button className={layer === 'All' ? 'selected' : ''} onClick={() => setLayer('All')}>All</button>{layers.map(value => <button className={layer === value ? 'selected' : ''} key={value} onClick={() => setLayer(value)}>{value}</button>)}</div></div><div className="control-group"><span>Relationship</span><div className="chips"><button className={relationship === 'All' ? 'selected' : ''} onClick={() => setRelationship('All')}>All</button><button className={relationship === 'CURRENT_CUSTOMER' ? 'selected' : ''} onClick={() => setRelationship('CURRENT_CUSTOMER')}>Customers</button><button className={relationship === 'TARGET' ? 'selected' : ''} onClick={() => setRelationship('TARGET')}>Targets</button></div></div><p className="muted">{visible.length} canonical locations · proximity is a planning input only.</p></Panel><Panel title="Account geography"><div className="map-grid">{visible.map(record => <button className={`map-point ${selected?.account_id === record.account_id ? 'selected' : ''}`} key={record.account_id} onClick={() => setSelected(record)}><span className="rank">#{record.external_rank}</span><strong>{record.industry}</strong><State value={record.relationship} /><small>{record.latitude}, {record.longitude}<br />{record.deep_account ? 'Deep scenario context' : 'Market-universe context'}</small></button>)}</div></Panel></div><aside className="map-quick-view">{selected ? <Panel title="Account quick view"><State value={selected.relationship} /><h3>{selected.industry} · #{selected.external_rank}</h3><p>Nearest BTX facility: <strong>{selected.nearest_btx_facility.name}</strong></p><p className="muted">Planning proximity: {selected.proximity_input}</p><button className="primary" onClick={() => onAccount(selected.account_id)}>Open Account 360</button></Panel> : <Panel title="Account quick view"><p className="empty">Tap a location to inspect context without leaving the map.</p></Panel>}</aside></div></div>
}
