import { useEffect, useMemo, useRef, useState } from 'react'
import * as maplibregl from 'maplibre-gl'
import type { FeatureCollection, Point } from 'geojson'
import 'maplibre-gl/dist/maplibre-gl.css'
import './map.css'
import type { BtxMapFacility, Coordinates, MapIntelligence, MapRecord, PublicLocation } from '../../types/api'

type Props = { records: MapRecord[]; publicLocations: PublicLocation[]; btxFacilities: BtxMapFacility[]; signals: MapIntelligence[]; selectedAccountId?: string; onAccountSelect: (accountId: string) => void; onFacilitySelect: (facilityId: string, accountId?: string) => void }
type Mappable = { coordinates: Coordinates | null; id: string; entity_type: string; account_id?: string; facility_id?: string; name?: string; title?: string }
type MapData = { accounts: FeatureCollection<Point>; facilities: FeatureCollection<Point>; btx: FeatureCollection<Point>; intelligence: FeatureCollection<Point> }

const validCoordinates = (value: Coordinates | null | undefined) => value && Number.isFinite(Number(value.latitude)) && Number.isFinite(Number(value.longitude)) && Math.abs(Number(value.latitude)) <= 90 && Math.abs(Number(value.longitude)) <= 180
const collection = (items: Mappable[]): FeatureCollection<Point> => ({ type: 'FeatureCollection', features: items.filter(item => validCoordinates(item.coordinates)).map(item => ({ type: 'Feature', properties: { id: item.id, entityType: item.entity_type, accountId: item.account_id ?? '', facilityId: item.facility_id ?? '', label: item.name ?? item.title ?? '' }, geometry: { type: 'Point', coordinates: [Number(item.coordinates!.longitude), Number(item.coordinates!.latitude)] } })) })
const mapStyle = (data: MapData): maplibregl.StyleSpecification => ({ version: 8, sources: { osm: { type: 'raster', tiles: ['https://tile.openstreetmap.org/{z}/{x}/{y}.png'], tileSize: 256, attribution: '© OpenStreetMap contributors' }, accounts: { type: 'geojson', data: data.accounts, cluster: true, clusterRadius: 42, clusterMaxZoom: 10 }, facilities: { type: 'geojson', data: data.facilities }, btx: { type: 'geojson', data: data.btx }, intelligence: { type: 'geojson', data: data.intelligence } }, layers: [{ id: 'osm', type: 'raster', source: 'osm' }, { id: 'account-clusters', type: 'circle', source: 'accounts', filter: ['has', 'point_count'], paint: { 'circle-color': '#2b7db0', 'circle-radius': 18 } }, { id: 'account-cluster-count', type: 'symbol', source: 'accounts', filter: ['has', 'point_count'], layout: { 'text-field': '{point_count_abbreviated}', 'text-size': 12 }, paint: { 'text-color': '#fff' } }, { id: 'account-points', type: 'circle', source: 'accounts', filter: ['!', ['has', 'point_count']], paint: { 'circle-color': '#79bdf2', 'circle-radius': 7, 'circle-stroke-color': '#0b1523', 'circle-stroke-width': 1 } }, { id: 'facility-points', type: 'circle', source: 'facilities', paint: { 'circle-color': '#67d6a0', 'circle-radius': 5, 'circle-stroke-color': '#0b1523', 'circle-stroke-width': 1 } }, { id: 'btx-points', type: 'circle', source: 'btx', paint: { 'circle-color': '#f0b54d', 'circle-radius': 8, 'circle-stroke-color': '#0b1523', 'circle-stroke-width': 1 } }, { id: 'intelligence-points', type: 'circle', source: 'intelligence', paint: { 'circle-color': '#e56b6f', 'circle-radius': 6, 'circle-stroke-color': '#0b1523', 'circle-stroke-width': 1 } }] })

export function MapCanvas({ records, publicLocations, btxFacilities, signals, selectedAccountId, onAccountSelect, onFacilitySelect }: Props) {
  const container = useRef<HTMLDivElement>(null); const mapRef = useRef<maplibregl.Map | null>(null); const fallbackMarkersRef = useRef<maplibregl.Marker[]>([]); const fallbackActiveRef = useRef(false); const renderFallbackMarkersRef = useRef<() => void>(() => {}); const [loaded, setLoaded] = useState(false); const [failure, setFailure] = useState<string | null>(null)
  const data = useMemo(() => ({ accounts: collection(records), facilities: collection(publicLocations), btx: collection(btxFacilities), intelligence: collection(signals) }), [records, publicLocations, btxFacilities, signals])
  const dataRef = useRef(data); const onAccountSelectRef = useRef(onAccountSelect); const onFacilitySelectRef = useRef(onFacilitySelect)
  useEffect(() => { dataRef.current = data }, [data]); useEffect(() => { onAccountSelectRef.current = onAccountSelect }, [onAccountSelect]); useEffect(() => { onFacilitySelectRef.current = onFacilitySelect }, [onFacilitySelect])
  useEffect(() => { renderFallbackMarkersRef.current = () => { const map = mapRef.current; if (!map) return; fallbackMarkersRef.current.forEach(marker => marker.remove()); const addMarkers = (items: Mappable[], kind: 'account' | 'facility' | 'btx' | 'intelligence') => items.filter(item => validCoordinates(item.coordinates)).forEach(item => { const element = document.createElement('button'); const selected = Boolean(item.account_id && item.account_id === selectedAccountId); element.type = 'button'; element.className = `map-dom-marker map-dom-marker-${kind}${selected ? ' selected' : ''}`; element.setAttribute('aria-label', `Map ${kind === 'account' ? 'Customer' : kind} marker: ${item.name ?? item.title ?? item.id}`); element.setAttribute('aria-pressed', String(selected)); element.title = item.name ?? item.title ?? item.id; element.addEventListener('click', event => { event.stopPropagation(); if (kind === 'account' || kind === 'intelligence') { if (item.account_id) onAccountSelectRef.current(item.account_id) } else if (item.facility_id) onFacilitySelectRef.current(item.facility_id, item.account_id) }); fallbackMarkersRef.current.push(new maplibregl.Marker({ element, anchor: 'center' }).setLngLat([Number(item.coordinates!.longitude), Number(item.coordinates!.latitude)]).addTo(map)) }); addMarkers(records, 'account'); addMarkers(publicLocations, 'facility'); addMarkers(btxFacilities, 'btx'); addMarkers(signals, 'intelligence') } }, [records, publicLocations, btxFacilities, signals, selectedAccountId])
  useEffect(() => { if (fallbackActiveRef.current) renderFallbackMarkersRef.current() }, [records, publicLocations, btxFacilities, signals, selectedAccountId])
  useEffect(() => { if (!container.current || mapRef.current) return; const map = new maplibregl.Map({ container: container.current, style: mapStyle(dataRef.current), center: [-98, 38], zoom: 3.2 }); mapRef.current = map; map.addControl(new maplibregl.NavigationControl(), 'top-right'); map.on('error', () => setFailure('Map unavailable. The public basemap could not load.')); const ready = () => setLoaded(true); map.on('styledata', ready); map.once('load', ready); if (map.loaded()) ready(); map.on('click', 'account-clusters', event => { const feature = event.features?.[0]; const source = map.getSource('accounts') as maplibregl.GeoJSONSource; const clusterId = feature?.properties?.cluster_id; if (feature && typeof clusterId === 'number') void source.getClusterExpansionZoom(clusterId).then(zoom => map.easeTo({ center: (feature.geometry as Point).coordinates as [number, number], zoom })) }); map.on('click', 'account-points', event => { const account = event.features?.[0]?.properties?.accountId; if (account) onAccountSelectRef.current(account) }); for (const id of ['facility-points', 'btx-points']) map.on('click', id, event => { const feature = event.features?.[0]?.properties; const facilityId = feature?.facilityId; if (facilityId) onFacilitySelectRef.current(facilityId, feature.accountId || undefined) }); map.on('click', 'intelligence-points', event => { const account = event.features?.[0]?.properties?.accountId; if (account) onAccountSelectRef.current(account) }); const fallbackTimer = window.setTimeout(() => { const rendered = map.queryRenderedFeatures({ layers: ['account-points', 'account-clusters', 'facility-points', 'btx-points', 'intelligence-points'] }); if (!rendered.length && (dataRef.current.accounts.features.length || dataRef.current.facilities.features.length || dataRef.current.btx.features.length || dataRef.current.intelligence.features.length)) { for (const id of ['account-clusters', 'account-cluster-count', 'account-points', 'facility-points', 'btx-points', 'intelligence-points']) map.setLayoutProperty(id, 'visibility', 'none'); fallbackActiveRef.current = true; renderFallbackMarkersRef.current() } }, 1800); const resize = new ResizeObserver(() => map.resize()); resize.observe(container.current); return () => { window.clearTimeout(fallbackTimer); resize.disconnect(); fallbackMarkersRef.current.forEach(marker => marker.remove()); fallbackMarkersRef.current = []; fallbackActiveRef.current = false; map.remove(); mapRef.current = null } }, [])
  useEffect(() => { const map = mapRef.current; if (!map || !loaded) return; for (const [id, value] of Object.entries(data)) (map.getSource(id) as maplibregl.GeoJSONSource | undefined)?.setData(value) }, [data, loaded])
  if (failure) return <section className="map-unavailable" role="status"><h3>Map unavailable</h3><p>{failure}</p></section>
  return <div ref={container} className="map-canvas" role="application" aria-label="Interactive MapLibre Customer, facility, BTX facility, and intelligence map" />
}
