"""Reviewed operation inventory; adding an API operation requires classification."""
HIDDEN_OPERATIONS = {
    "POST /api/monitor/internal/collect/{source_id}": "c: operator-only external collection stub",
    "POST /api/monitor/internal/collect": "c: operator-only external collection stub",
}
OPERATIONS = {
    "GET /api/accounts": "a: local fixture",
    "GET /api/accounts/workspace/opportunities": "a: local fixture",
    "GET /api/accounts/{account_id}": "a: local fixture",
    "GET /api/accounts/{account_id}/commercial/{collection}": "a: local fixture",
    "GET /api/accounts/{account_id}/relationships": "a: local fixture",
    "GET /api/accounts/{account_id}/workbook-fields": "a: local fixture",
    "GET /api/accounts/{account_id}/workbook-fields/{version_id}": "a: local fixture",
    "GET /api/actions": "a: local fixture",
    "GET /api/actions/principal": "a: local fixture",
    "GET /api/actions/suggestion-feedback/history": "a: local fixture",
    "GET /api/actions/{action_id}": "a: local fixture",
    "GET /api/actions/{action_id}/crm-proposals": "a: local fixture",
    "GET /api/actions/{action_id}/history": "a: local fixture",
    "GET /api/build": "b: non-data/session",
    "GET /api/communications": "a: local fixture",
    "GET /api/communications/{draft_id}/history": "a: local fixture",
    "GET /api/federal-procurement": "a: local fixture",
    "GET /api/federal-procurement/assessments/{assessment_id}": "c: external adapter stub",
    "GET /api/health": "b: non-data/session",
    "GET /api/intelligence": "a: local fixture",
    "GET /api/intelligence/{event_id}/evidence": "c: external adapter stub",
    "GET /api/itineraries/current": "a: local fixture",
    "GET /api/map": "a: local fixture",
    "GET /api/markets": "a: local fixture",
    "GET /api/markets/{series_id}": "c: external adapter stub",
    "GET /api/monitor/candidates": "c: external adapter stub",
    "GET /api/monitor/health": "c: external adapter stub",
    "GET /api/monitor/sources": "c: external adapter stub",
    "GET /api/omni/memories": "a: local fixture",
    "GET /api/omni/runs/{run_id}": "a: local fixture",
    "GET /api/planning": "a: local fixture",
    "GET /api/session": "b: non-data/session",
    "GET /api/settings": "a: local fixture",
    "GET /api/settings/ai-usage": "a: local fixture",
    "GET /api/today": "a: local fixture",
    "PATCH /api/actions/{action_id}": "a: local fixture",
    "PATCH /api/communications/{draft_id}": "a: local fixture",
    "PATCH /api/omni/memories/{memory_id}": "a: local fixture",
    "PATCH /api/settings/preferences": "a: local fixture",
    "POST /api/accounts/{account_id}/commercial/follow-ups/{action_id}/confirm": "a: local fixture",
    "POST /api/accounts/{account_id}/commercial/follow-ups/{action_id}/preview": "a: local fixture",
    "POST /api/actions": "a: local fixture",
    "POST /api/actions/suggestion-feedback/{receipt_id}/undo": "a: local fixture",
    "POST /api/actions/suggestions/{suggestion_id}/convert": "a: local fixture",
    "POST /api/actions/suggestions/{suggestion_id}/dismiss": "a: local fixture",
    "POST /api/actions/suggestions/{suggestion_id}/feedback": "a: local fixture",
    "POST /api/actions/{action_id}/approval": "a: local fixture",
    "POST /api/actions/{action_id}/crm-execute": "a: local fixture",
    "POST /api/actions/{action_id}/crm-preview": "a: local fixture",
    "POST /api/actions/{action_id}/crm-proposal-decision": "a: local fixture",
    "POST /api/actions/{action_id}/status": "a: local fixture",
    "POST /api/communications": "a: local fixture",
    "POST /api/communications/assist": "c: external adapter stub",
    "POST /api/communications/{draft_id}/approval": "a: local fixture",
    "POST /api/communications/{draft_id}/assist": "c: external adapter stub",
    "POST /api/communications/{draft_id}/preview": "a: local fixture",
    "POST /api/communications/{draft_id}/send": "c: external adapter stub",
    "POST /api/itineraries/current": "a: local fixture",
    "POST /api/monitor/candidates/{candidate_id}/promote": "c: external adapter stub",
    "POST /api/monitor/collect/{source_id}": "c: external adapter stub",
    "POST /api/monitor/program-candidates/{candidate_id}/promote": "c: external adapter stub",
    "POST /api/omni": "a: local fixture",
    "POST /api/omni/memories": "a: local fixture",
    "POST /api/omni/memories/{memory_id}/delete": "a: local fixture",
    "POST /api/planning/partnerships/{account_id}": "a: local fixture",
    "POST /api/planning/shortlist": "a: local fixture",
    "POST /api/relationships/query": "a: local fixture",
    "POST /api/session/sign-in": "b: non-data/session",
    "POST /api/session/sign-out": "b: non-data/session",
}
