import { expect, test } from '@playwright/test'

async function create(page, title) {
  await page.goto('/#/actions')
  await page.getByLabel('Quick add task').fill(title)
  await page.getByLabel('Quick add task').press('Enter')
  await expect(page.locator('.action-detail').getByLabel('Title', { exact: true })).toHaveValue(title)
  return page.locator('.action-detail')
}

test('inline personal task persists edits, subtasks, cancel undo and completed reopen', async ({ page }) => {
  const title = `Personal review ${crypto.randomUUID()}`
  const detail = await create(page, title)
  await detail.getByLabel('Description', { exact: true }).fill('Evidence review required')
  await detail.getByLabel('Description', { exact: true }).blur()
  await expect(detail.getByText('Saved', { exact: true })).toBeVisible()
  await detail.getByLabel('New subtask').fill('Read evidence')
  await detail.getByRole('button', { name: 'Add subtask' }).click()
  await expect(detail.getByRole('heading', { name: 'Subtasks · 0/1' })).toBeVisible()
  await detail.getByLabel('Subtask title', { exact: true }).fill('Read source evidence')
  await detail.getByLabel('Subtask title', { exact: true }).blur()
  await expect(detail.getByLabel('Done: Read source evidence')).toBeVisible()
  await detail.getByLabel('Done: Read source evidence').check()
  await expect(detail.getByRole('heading', { name: 'Subtasks · 1/1' })).toBeVisible()
  await detail.getByRole('button', { name: 'Remove subtask' }).click()
  await expect(detail.getByRole('button', { name: 'Restore subtask' })).toBeVisible()
  await detail.getByRole('button', { name: 'Restore subtask' }).click()
  await detail.getByRole('button', { name: 'Cancel task' }).click()
  await expect(detail.getByLabel('Status', { exact: true })).toHaveValue('CANCELED')
  await page.locator('.action-undo').getByRole('button', { name: 'Undo' }).click()
  await expect(detail.getByLabel('Status', { exact: true })).toHaveValue('OPEN')
  await detail.getByRole('button', { name: 'Complete', exact: true }).click()
  await expect(detail.getByLabel('Status', { exact: true })).toHaveValue('COMPLETED')
  await detail.getByRole('button', { name: 'Reopen', exact: true }).click()
  await expect(detail.getByLabel('Status', { exact: true })).toHaveValue('IN_PROGRESS')
  await page.reload()
  await expect(detail.getByLabel('Description', { exact: true })).toHaveValue('Evidence review required')
  await expect(detail.getByLabel('Done: Read source evidence')).toBeChecked()
})

test('cancel can reopen after the undo toast expires and Closed keeps its URL key', async ({ page }) => {
  const detail = await create(page, `Reopen later ${crypto.randomUUID()}`)
  await detail.getByRole('button', { name: 'Cancel task' }).click()
  await expect(page.locator('.action-undo')).toBeVisible()
  await expect(page.locator('.action-undo')).toBeHidden({ timeout: 12000 })
  await page.getByRole('button', { name: 'Closed', exact: true }).click()
  await expect(page).toHaveURL(/view=completed/)
  await detail.getByRole('button', { name: 'Reopen', exact: true }).click()
  await expect(detail.getByLabel('Status', { exact: true })).toHaveValue('OPEN')
})

test('open subtasks require explicit completion consent', async ({ page }) => {
  const detail = await create(page, `Subtask consent ${crypto.randomUUID()}`)
  await detail.getByLabel('New subtask').fill('Unfinished work')
  await detail.getByRole('button', { name: 'Add subtask' }).click()
  await expect(detail.getByRole('heading', { name: 'Subtasks · 0/1' })).toBeVisible()
  await detail.getByRole('button', { name: 'Complete', exact: true }).click()
  await expect(detail.getByLabel('Status', { exact: true })).toHaveValue('OPEN')
  await detail.getByRole('button', { name: 'Complete all and finish' }).click()
  await expect(detail.getByLabel('Status', { exact: true })).toHaveValue('COMPLETED')
  await expect(detail.getByRole('heading', { name: 'Subtasks · 1/1' })).toBeVisible()
})

test('owner requests and manager requests changes, rejects and approves without closing work', async ({ browser }) => {
  const seller = await browser.newPage()
  const title = `Approval review ${crypto.randomUUID()}`
  const detail = await create(seller, title)
  await detail.getByRole('button', { name: 'Request approval', exact: true }).click()
  await expect(detail.getByText('REQUESTED', { exact: true }).first()).toBeVisible()
  await detail.getByRole('button', { name: 'Complete', exact: true }).click()
  await expect(detail.getByRole('alert')).toContainText('Approval is required')
  await expect(detail.getByRole('button', { name: 'Approve', exact: true })).toHaveCount(0)
  const url = seller.url()
  const manager = await browser.newContext()
  await manager.addInitScript(() => sessionStorage.setItem('btx-principal-token', 'development-manager'))
  const page = await manager.newPage()
  await page.goto(url)
  const review = page.locator('.action-detail')
  await expect(review.getByRole('button', { name: 'Request changes', exact: true })).toBeDisabled()
  await review.getByLabel('Manager comment').fill('Review original evidence')
  await review.getByRole('button', { name: 'Request changes', exact: true }).click()
  await expect(review.getByLabel('Status', { exact: true })).toHaveValue('IN_PROGRESS')
  await seller.reload()
  await expect(detail.getByText('Review original evidence', { exact: true }).first()).toBeVisible()
  await expect(seller.locator('.action-row').filter({ hasText: title })).toBeVisible()
  await detail.getByRole('button', { name: 'Request approval', exact: true }).click()
  await expect(detail.getByText('REQUESTED', { exact: true }).first()).toBeVisible()
  await page.reload()
  await review.getByLabel('Manager comment').fill('Still incomplete')
  await review.getByRole('button', { name: 'Reject', exact: true }).click()
  await expect(review.getByText('REJECTED', { exact: true }).first()).toBeVisible()
  await seller.reload()
  await expect(seller.locator('.action-row').filter({ hasText: title })).toBeVisible()
  await detail.getByRole('button', { name: 'Request approval', exact: true }).click()
  await expect(detail.getByText('REQUESTED', { exact: true }).first()).toBeVisible()
  await page.reload()
  await review.getByRole('button', { name: 'Approve', exact: true }).click()
  await expect(review.getByText('APPROVED', { exact: true }).first()).toBeVisible()
  await expect(review.getByLabel('Status', { exact: true })).toHaveValue('IN_PROGRESS')
  await manager.close(); await seller.close()
})

test('Suggestions remain distinct and conversion retains its source and idempotency', async ({ page }) => {
  await page.goto('/#/actions?view=suggestions')
  await expect(page.getByText('Recommendations are not Actions')).toBeVisible()
  const suggestions = await (await page.request.get('/api/actions')).json()
  const candidate = suggestions.suggestions.find(item => !item.dismissed && !item.converted_action_id && !item.conversion_blocked)
  expect(candidate).toBeTruthy()
  await page.goto(`/#/actions?view=suggestions&record=${candidate.id}`)
  await page.locator('.suggestion-detail').getByRole('button', { name: 'Create Action', exact: true }).click()
  await expect(page.getByText(/converted to one durable Action/)).toBeVisible()
  await expect(page.locator('.action-detail').getByRole('link', { name: 'Suggested', exact: true })).toBeVisible()
  const replay = await page.request.post(`/api/actions/suggestions/${candidate.id}/convert`, { data: { expected_revision: candidate.revision } })
  expect(replay.ok()).toBeTruthy()
  expect((await replay.json()).id).toBe(new URL(page.url()).hash.match(/action=([^&]+)/)[1])
})

for (const width of [320, 390]) test(`${width}px detail replaces list, contains controls and restores row focus on Escape`, async ({ page }) => {
  await page.setViewportSize({ width, height: 844 })
  const title = `Mobile ${crypto.randomUUID()}`
  const detail = await create(page, title)
  await expect(page.locator('.action-list-pane')).toBeHidden()
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
  await detail.press('Escape')
  await expect(detail).toBeHidden()
  await expect(page.locator('.action-select').filter({ hasText: title })).toBeFocused()
  await page.locator('.action-select').filter({ hasText: title }).click()
  await detail.getByRole('button', { name: 'Complete', exact: true }).click()
  await expect(detail.getByLabel('Status', { exact: true })).toHaveValue('COMPLETED')
  await detail.press('Escape')
  await expect(page.getByLabel('Quick add task')).toBeFocused()
  await expect(page.getByRole('navigation', { name: 'Mobile primary navigation' })).toBeVisible()
})
