import { expect, test } from '@playwright/test'

test('stale communication edit preserves local text and requires explicit saved-version comparison', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 })
  const subject = `Version review ${testInfo.testId}`
  const created = await page.request.post('/api/communications', { data: {
    account_id: 'boeing', subject, body: 'Original saved message', recipients: [], idempotency_key: `versions-${testInfo.testId}`,
  } })
  expect(created.ok()).toBe(true)
  const draft = await created.json()
  await page.goto('/#/communications')
  await page.getByLabel('Search communications').fill(subject)
  await page.getByRole('button', { name: 'Edit draft', exact: true }).click()
  const editor = page.getByRole('dialog', { name: 'Edit communication' })
  await editor.getByRole('textbox', { name: 'Message', exact: true }).fill('My retained local changes')
  const changed = await page.request.patch(`/api/communications/${draft.id}`, { data: { body: 'Another saved revision', expected_version: draft.version } })
  expect(changed.ok()).toBe(true)
  const current = await changed.json()
  await editor.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(editor.getByRole('status')).toContainText('This communication changed')
  await expect(editor.getByRole('textbox', { name: 'Message', exact: true })).toHaveValue('My retained local changes')
  await editor.getByRole('button', { name: 'Refresh saved version for comparison' }).click()
  const comparison = editor.getByRole('region', { name: 'Saved communication comparison' })
  await expect(comparison).toContainText('Another saved revision')
  await expect(editor.getByRole('textbox', { name: 'Message', exact: true })).toHaveValue('My retained local changes')
  let persisted = (await (await page.request.get('/api/communications')).json()).items.find(item => item.id === draft.id)
  expect(persisted.version).toBe(current.version)
  await comparison.getByRole('button', { name: 'Use this reviewed version for my next save' }).click()
  persisted = (await (await page.request.get('/api/communications')).json()).items.find(item => item.id === draft.id)
  expect(persisted.body).toBe('Another saved revision')
  await editor.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(editor).not.toBeVisible()
  persisted = (await (await page.request.get('/api/communications')).json()).items.find(item => item.id === draft.id)
  expect(persisted.body).toBe('My retained local changes')
  expect(persisted.version).toBe(current.version + 1)
  expect(persisted.approval_status).toBe('PENDING')
  expect(persisted.status).toBe('DRAFT')
  await expect(page.locator('html')).toHaveJSProperty('scrollWidth', 390)
  await page.screenshot({ path: testInfo.outputPath('communication-version-review-mobile.png') })
})
