import { test, expect } from '@playwright/test'
import { openCustomerSection, openOrganizationEvidence } from './helpers.mjs'

test('retained reference fields and paginated lifecycle records use canonical API identity', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('navigation', { name: 'Primary navigation', exact: true }).getByRole('button', { name: 'Profiles', exact: true }).click()
  await page.getByRole('table', { name: 'Customers and Prospects' }).getByRole('link', { name: 'KLA Corporation', exact: true }).click()
  await openOrganizationEvidence(page)
  await page.getByText('Full commercial records & retained input fields', { exact: true }).click()
  const disclosure = page.locator('.commercial-records')
  await expect(disclosure.getByText('naics assignments', { exact: true })).toBeVisible()
  await disclosure.getByText('naics assignments', { exact: true }).click()
  const reference = await page.request.get('/api/accounts/kla/commercial/reference')
  expect(reference.ok()).toBeTruthy()
  const ref = await reference.json()
  expect(ref.reference.naics_assignments.length).toBeGreaterThan(0)
  await expect(disclosure).toContainText(String(ref.reference.naics_assignments[0].code ?? ref.reference.naics_assignments[0].naics_code))
  await page.getByLabel('Record group', { exact: true }).selectOption('shipments')
  const response = await page.request.get('/api/accounts/kla/commercial/shipments?offset=0&limit=10')
  const first = await response.json()
  expect(response.ok()).toBeTruthy()
  expect(first.record_key).toBe('shipment_id')
  const id = first.records[0][first.record_key]
  const recordSummary = value => disclosure.locator('summary').filter({ hasText: new RegExp(`^${value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}$`) })
  await expect(recordSummary(id)).toBeVisible()
  await recordSummary(id).click()
  await expect(disclosure).toContainText(first.records[0].order_line_id)
  await disclosure.getByRole('button', { name: 'Next records', exact: true }).click()
  const next = await (await page.request.get(`/api/accounts/kla/commercial/shipments?offset=${first.next_offset}&limit=10`)).json()
  await expect(recordSummary(next.records[0][next.record_key])).toBeVisible()
  await expect(disclosure.getByText(id, { exact: true })).toHaveCount(0)
})

test('customer risk view keeps public severity separate and preserves missingness', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('navigation', { name: 'Primary navigation', exact: true }).getByRole('button', { name: 'Profiles', exact: true }).click()
  await page.getByRole('table', { name: 'Customers and Prospects' }).getByRole('link', { name: 'Boeing', exact: true }).click()
  await openCustomerSection(page, /Commercial decisions & follow-ups/)
  const decision = page.locator('.commercial-decision').filter({ hasText: /^overall customer risk/ })
  await expect(decision.locator('summary')).toContainText('Status available in supporting details')
  await decision.locator('summary').click()
  await expect(decision).toContainText('Unknown coverage cannot create an overall score')
  await expect(decision).toContainText('Internal commercial risk and public event severity remain separately inspectable.')
  await expect(decision).toContainText('Missing public risk evidence is not a zero-risk observation.')

  const response = await page.request.get('/api/accounts/boeing/commercial/decisions')
  expect(response.ok()).toBeTruthy()
  const payload = await response.json()
  expect(payload.overall_customer_risk.status).toBe('INSUFFICIENT_EVIDENCE')
  expect(payload.overall_customer_risk.missing_fields).toContain('public_risk_rollup')
  expect(payload.public_risk_rollup.score).toBeNull()
})
