import { test, expect } from '@playwright/test'

test('retained reference fields and paginated lifecycle records use canonical API identity', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('navigation', { name: 'Primary navigation', exact: true }).getByRole('button', { name: 'Customers & Prospects', exact: true }).click()
  await page.getByRole('row', { name: /^KLA/ }).first().click()
  await page.getByText('Full commercial records & retained input fields', { exact: true }).click()
  const disclosure = page.locator('.commercial-records')
  await expect(disclosure.getByText('naics assignments', { exact: true })).toBeVisible()
  await disclosure.getByText('naics assignments', { exact: true }).click()
  const reference = await page.request.get('/api/accounts/kla/commercial/reference')
  expect(reference.ok()).toBeTruthy()
  const ref = await reference.json()
  expect(ref.reference.naics_assignments.length).toBeGreaterThan(0)
  await expect(disclosure).toContainText(String(ref.reference.naics_assignments[0].code ?? ref.reference.naics_assignments[0].naics_code))
  await page.getByLabel('Record group', { exact: true }).selectOption('shipments')
  const response = await page.request.get('/api/accounts/kla/commercial/shipments?offset=0&limit=10')
  const first = await response.json()
  expect(response.ok()).toBeTruthy()
  expect(first.record_key).toBe('shipment_id')
  const id = first.records[0][first.record_key]
  const recordSummary = value => disclosure.locator('summary').filter({ hasText: new RegExp(`^${value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}$`) })
  await expect(recordSummary(id)).toBeVisible()
  await recordSummary(id).click()
  await expect(disclosure).toContainText(first.records[0].order_line_id)
  await disclosure.getByRole('button', { name: 'Next records', exact: true }).click()
  const next = await (await page.request.get(`/api/accounts/kla/commercial/shipments?offset=${first.next_offset}&limit=10`)).json()
  await expect(recordSummary(next.records[0][next.record_key])).toBeVisible()
  await expect(disclosure.getByText(id, { exact: true })).toHaveCount(0)
})
