import { expect, test } from '@playwright/test'

test('shared disclosure and controls expose keyboard and selected-state contracts', async ({ page }) => {
  await page.goto('/')

  const disclosure = page.getByRole('button', { name: /Workspace menu/ })
  await expect(disclosure).toHaveAttribute('aria-expanded', 'false')
  await disclosure.focus()
  await expect(disclosure).toBeFocused()
  await disclosure.press('Enter')
  await expect(disclosure).toHaveAttribute('aria-expanded', 'true')
  await expect(page.getByText(/Public evidence and SAMPLE commercial context/)).toBeVisible()
  await disclosure.press('Enter')
  await expect(disclosure).toHaveAttribute('aria-expanded', 'false')

  await page.getByRole('navigation', { name: 'Primary navigation' }).getByRole('button', { name: 'Customers & Prospects' }).click()
  const search = page.getByRole('searchbox', { name: 'Search Customers and Prospects' })
  await search.focus()
  await expect(search).toBeFocused()
  await search.fill('Intel')
  await expect(page.locator('.account-row')).toHaveCount(1)

  const defense = page.getByRole('button', { name: 'Defense', exact: true })
  await defense.click()
  await expect(defense).toHaveAttribute('aria-pressed', 'true')
  const clear = page.getByRole('button', { name: 'All industries', exact: true })
  await clear.click()
  await expect(clear).toHaveAttribute('aria-pressed', 'true')
  await expect(defense).toHaveAttribute('aria-pressed', 'false')
})

test('shared evidence treatment renders truthful sourced and unavailable states', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('navigation', { name: 'Primary navigation' }).getByRole('button', { name: 'Intelligence' }).click()
  const disclosure = page.locator('.intelligence-card').first().getByRole('button', { name: /Evidence/ })
  await expect(disclosure).toHaveAttribute('aria-expanded', 'false')
  await disclosure.click()
  await expect(disclosure).toHaveAttribute('aria-expanded', 'true')
  const evidence = page.locator('.ui-evidence')
  await expect(evidence.first()).toBeVisible()
  await expect(evidence.first()).toContainText('Source:')
  await expect(evidence.first()).toContainText('Date:')
  const linked = evidence.filter({ has: page.getByRole('link', { name: 'Inspect source →' }) })
  await expect(linked.first()).toBeVisible()
  const unavailable = evidence.filter({ hasText: 'Source link unavailable' })
  if (await unavailable.count()) await expect(unavailable.first()).toContainText(/Unavailable|needs research|Source link unavailable/i)
})

test('shared drawer closes by controls and backdrop and becomes a safe mobile sheet', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  const opener = page.getByLabel('Open Omni assistant')
  await opener.click()
  const dialog = page.getByRole('dialog', { name: 'Omni' })
  await expect(dialog).toBeVisible()
  await expect(page.getByLabel('Close Omni')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Send', exact: true })).toBeDisabled()
  const box = await dialog.boundingBox()
  expect(box?.width).toBeLessThanOrEqual(390)
  expect((box?.y ?? 0) + (box?.height ?? 0)).toBeLessThanOrEqual(844)
  await page.getByLabel('Close Omni').click()
  await expect(dialog).toBeHidden()
  await expect(opener).toBeFocused()

  await opener.click()
  await page.locator('.ui-drawer-backdrop').click({ position: { x: 4, y: 4 } })
  await expect(dialog).toBeHidden()
})
