import { expect, test } from '@playwright/test'

test('mobile secondary navigation and controls expose keyboard and selected-state contracts', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')

  const mobileNavigation = page.getByRole('navigation', { name: 'Mobile primary navigation' })
  await expect(mobileNavigation).toBeVisible({ timeout: 15_000 })
  const more = mobileNavigation.getByRole('button', { name: 'More', exact: true })
  await expect(more).toHaveAttribute('aria-expanded', 'false')
  await more.focus()
  await expect(more).toBeFocused()
  await more.press('Enter')
  await expect(page.getByRole('dialog', { name: 'More' })).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'More workspaces' })).toBeVisible()
  await page.getByLabel('Close more workspaces').press('Enter')
  await expect(page.getByRole('dialog', { name: 'More' })).toBeHidden()

  await page.setViewportSize({ width: 1440, height: 900 })
  await page.getByRole('navigation', { name: 'Primary navigation' }).getByRole('button', { name: 'Customers & Prospects' }).click()
  const search = page.getByRole('searchbox', { name: 'Search Customers and Prospects' })
  await search.focus()
  await expect(search).toBeFocused()
  await search.fill('Intel')
  await expect(page.getByRole('table', { name: 'Customers and Prospects' }).getByRole('row')).toHaveCount(2)

  const defense = page.getByRole('button', { name: 'Defense', exact: true })
  await defense.click()
  await expect(defense).toHaveAttribute('aria-pressed', 'true')
  const clear = page.getByRole('button', { name: 'All industries', exact: true })
  await clear.click()
  await expect(clear).toHaveAttribute('aria-pressed', 'true')
  await expect(defense).toHaveAttribute('aria-pressed', 'false')
})

test('shared evidence treatment renders truthful sourced and unavailable states', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('navigation', { name: 'Primary navigation' }).getByRole('button', { name: 'Intelligence' }).click()
  const disclosure = page.locator('.intelligence-card').first().getByRole('button', { name: /Evidence/ })
  await expect(disclosure).toHaveAttribute('aria-expanded', 'false')
  await disclosure.click()
  await expect(disclosure).toHaveAttribute('aria-expanded', 'true')
  const evidence = page.locator('.ui-evidence')
  await expect(evidence.first()).toBeVisible()
  await expect(evidence.first()).toContainText('Source:')
  await expect(evidence.first()).toContainText('Date:')
  const linked = evidence.filter({ has: page.getByRole('link', { name: 'Inspect source →' }) })
  await expect(linked.first()).toBeVisible()
  const unavailable = evidence.filter({ hasText: 'Source link unavailable' })
  if (await unavailable.count()) await expect(unavailable.first()).toContainText(/Unavailable|needs research|Source link unavailable/i)
})

test('shared drawer closes by controls and backdrop and becomes a safe mobile sheet', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  const opener = page.getByLabel('Open Omni assistant')
  await opener.click()
  const dialog = page.getByRole('dialog', { name: 'Omni' })
  await expect(dialog).toBeVisible()
  await expect(page.getByLabel('Close Omni')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Send', exact: true })).toBeDisabled()
  const box = await dialog.boundingBox()
  expect(box?.width).toBeLessThanOrEqual(390)
  expect((box?.y ?? 0) + (box?.height ?? 0)).toBeLessThanOrEqual(844)
  await page.getByLabel('Close Omni').click()
  await expect(dialog).toBeHidden()
  await expect(opener).toBeFocused()

  await opener.click()
  await page.locator('.ui-drawer-backdrop').click({ position: { x: 4, y: 4 } })
  await expect(dialog).toBeHidden()
})

test('decision notices give the trigger and next step a full-width reading order', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/#/accounts/applied-materials')
  const notice = page.getByRole('alert').filter({ hasText: 'Execution attention' })
  await expect(notice).toContainText('What needs attention:')
  await expect(notice).toContainText('Next:')
  expect(await notice.evaluate(element => getComputedStyle(element).display)).toBe('grid')
  const noticeBox = await notice.boundingBox()
  const contentBox = await notice.locator('.ui-notice-content').boundingBox()
  expect(contentBox?.width ?? 0).toBeGreaterThan((noticeBox?.width ?? 0) * 0.85)

  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
  await expect(notice).toBeVisible()
})
