import { expect, test } from '@playwright/test'

async function openPortfolio(page) {
  await page.goto('/#/accounts')
  await expect(page.getByRole('heading', { name: 'Accounts', level: 1 })).toBeVisible()
}
const roster = page => page.getByRole('table', { name: 'Customers and Prospects' })

test('desktop Portfolio composes accessible search, filters, sorting, and canonical Customer navigation', async ({ page }) => {
  await openPortfolio(page)
  const table = roster(page)
  await expect(table.getByRole('columnheader', { name: /^Account/ })).toHaveAttribute('aria-sort', 'ascending')
  await page.getByLabel('Market', { exact: true }).selectOption('Defense')
  await expect(page.getByRole('button', { name: 'Remove market filter' })).toContainText('Defense')
  await page.getByRole('button', { name: 'Remove market filter' }).click()
  await expect(page.getByLabel('Market', { exact: true })).toHaveValue('ALL')
  const search = page.getByRole('searchbox', { name: 'Search Customers and Prospects' })
  await search.fill('Lockheed')
  const link = table.getByRole('link', { name: 'Lockheed Martin', exact: true })
  await link.focus(); await link.press('Enter')
  await expect(page.getByRole('heading', { name: 'Lockheed Martin', level: 1 })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'TTM commercial activity' })).toBeVisible()
  await expect(page.getByLabel('Demonstration environment')).toHaveCount(1)
  await page.getByRole('tab', { name: 'Relationships', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Ranked canonical relationships' })).toHaveAttribute('aria-busy', 'false')
  await page.getByRole('searchbox', { name: 'Switch organization' }).fill('Symbotic')
  await page.getByRole('option', { name: /Symbotic/ }).click()
  await expect(page.getByRole('heading', { name: 'Symbotic', level: 1 })).toBeVisible()
  await page.getByRole('button', { name: '← Customers & Prospects' }).click()
  await expect(search).toHaveValue('Lockheed')
  await table.getByRole('button', { name: /^Account/ }).click()
  await expect(table.getByRole('columnheader', { name: /^Account/ })).toHaveAttribute('aria-sort', 'descending')
  await search.fill('no canonical customer has this name')
  await expect(page.getByText('No accounts match this view. Try clearing filters.')).toBeVisible()
  await expect(table.locator(':scope > tbody > tr')).toHaveCount(0)
  await search.fill('Lockheed')
  await expect(link).toBeVisible()
})

test('390px Portfolio keeps a semantic scrollable table and accessible commercial details', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await openPortfolio(page)
  const table = roster(page)
  await expect(table.locator(':scope > thead > tr > th')).toHaveCount(9)
  await page.getByRole('searchbox', { name: 'Search Customers and Prospects' }).fill('Lockheed')
  await table.getByRole('link', { name: 'Lockheed Martin', exact: true }).click()
  await page.getByRole('tab', { name: 'Commercial', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Orders', exact: true })).toBeVisible()
  const orders = page.locator('.profile-commercial .profile-card').filter({ has: page.getByRole('heading', { name: 'Orders', exact: true }) })
  const order = orders.locator('tbody th button').first()
  await expect(order).toHaveAttribute('aria-expanded', 'false')
  await order.click()
  await expect(order).toHaveAttribute('aria-expanded', 'true')
  await expect(orders.getByRole('heading', { name: 'Lines, shipments & cancellations' })).toBeVisible()
  await order.click()
  await expect(order).toHaveAttribute('aria-expanded', 'false')
  await expect(page.getByLabel('Open Omni assistant')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
})

test('320px Customer Experience remains navigable without horizontal overflow', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 700 })
  await openPortfolio(page)
  await expect(roster(page)).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
  await page.getByRole('searchbox', { name: 'Search Customers and Prospects' }).fill('Lockheed')
  await roster(page).getByRole('link', { name: 'Lockheed Martin', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Lockheed Martin', level: 1 })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
})

test('Portfolio sorts the complete result set before pagination and retains sort after navigation', async ({ page }) => {
  await openPortfolio(page)
  const table = roster(page)
  const names = () => table.locator(':scope > tbody > tr > th a').allTextContents()
  const first = await names()
  expect(first).toHaveLength(50)
  expect(first).toEqual([...first].sort((a, b) => a.localeCompare(b)))
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  const second = await names()
  expect(first.at(-1).localeCompare(second[0])).toBeLessThanOrEqual(0)
  await table.getByRole('button', { name: /^Account/ }).click()
  const descending = await names()
  expect(descending).toEqual([...descending].sort((a, b) => b.localeCompare(a)))
  const selected = descending[0]
  await table.getByRole('link', { name: selected, exact: true }).click()
  await page.getByRole('button', { name: '← Customers & Prospects' }).click()
  await expect(table.getByRole('columnheader', { name: /^Account/ })).toHaveAttribute('aria-sort', 'descending')
  await expect(table.locator(':scope > tbody > tr > th a').first()).toHaveText(selected)
})
