import { expect, test } from '@playwright/test'

async function openPortfolio(page) {
  await page.goto('/')
  await page.getByRole('navigation', { name: 'Primary navigation' }).getByRole('button', { name: 'Customers & Prospects' }).click()
  await expect(page.getByRole('heading', { name: 'Customers & Prospects', level: 1 })).toBeVisible()
}

test('desktop Portfolio composes accessible search, filters, sorting, and canonical Customer navigation', async ({ page }) => {
  await openPortfolio(page)
  const table = page.getByRole('table', { name: 'Customers and Prospects' })
  await expect(table).toBeVisible()
  await expect(table.getByRole('columnheader', { name: /Customer/ })).toHaveAttribute('aria-sort', 'ascending')

  await page.getByRole('button', { name: /Filters/ }).click()
  await page.getByLabel('Customer scope').selectOption('ALL')
  await page.getByRole('button', { name: 'Defense', exact: true }).click()
  const active = page.getByLabel('Active Portfolio filters')
  await expect(active).toContainText('Defense')
  const activeDefense = active.getByRole('button', { name: 'Remove Defense filter' })
  await expect(activeDefense).toHaveAttribute('aria-pressed', 'true')
  await activeDefense.click()
  await expect(active).toBeHidden()

  const search = page.getByRole('searchbox', { name: 'Search Customers and Prospects' })
  await search.fill('Lockheed')
  const row = table.getByRole('row').filter({ hasText: 'Lockheed Martin' })
  await expect(row).toHaveCount(1)
  await row.focus()
  await expect(row).toBeFocused()
  await row.press('Enter')
  await expect(page.getByRole('heading', { name: 'Lockheed Martin', level: 1 })).toBeVisible()
  await expect(page.getByText('Why this Customer matters')).toBeVisible()
  await expect(page.getByLabel('Demonstration environment')).toHaveText('Simulated data environment')
  await expect(page.getByLabel('Demonstration environment')).toHaveCount(1)
  await expect(page.getByRole('heading', { name: 'Relationship Intelligence' })).toBeVisible()

  await page.getByRole('searchbox', { name: 'Switch Customer' }).fill('Symbotic')
  await page.getByRole('option', { name: /Symbotic/ }).click()
  await expect(page.getByRole('heading', { name: 'Symbotic', level: 1 })).toBeVisible()
  await page.getByRole('button', { name: '← Customers & Prospects' }).click()
  await expect(table).toBeVisible()

  await page.getByRole('button', { name: /Attractiveness/ }).click()
  await expect(table.getByRole('columnheader', { name: /Attractiveness/ })).toHaveAttribute('aria-sort', 'descending')
  await search.fill('no canonical customer has this name')
  await expect(page.getByText(/No Customers or Prospects match/)).toBeVisible()
  await search.fill('')
  await expect(table.getByRole('row').nth(1)).toBeVisible()
  await expect(page.locator('.accounts-surface')).not.toContainText(/\b(Account|Accounts|Client|Clients|Company|Companies)\b/)
})

test('390px Portfolio transforms to mobile rows and Customer 360 uses accessible disclosures', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await openPortfolio(page)
  await expect(page.getByRole('table', { name: 'Customers and Prospects' })).toBeHidden()
  const rows = page.locator('.portfolio-mobile-list .ui-mobile-row')
  await expect(rows.first()).toBeVisible()
  await expect(page.getByRole('searchbox', { name: 'Search Customers and Prospects' })).toBeVisible()
  await expect(page.getByLabel('Sort Customers and Prospects')).toBeVisible()
  await page.getByRole('searchbox', { name: 'Search Customers and Prospects' }).fill('Lockheed')
  await rows.filter({ hasText: 'Lockheed Martin' }).click()
  await expect(page.getByRole('heading', { name: 'Lockheed Martin', level: 1 })).toBeVisible()

  const commercial = page.getByRole('button', { name: /Commercial context/ })
  await expect(commercial).toHaveAttribute('aria-expanded', 'false')
  await commercial.click()
  await expect(commercial).toHaveAttribute('aria-expanded', 'true')
  await expect(page.getByText('SAMPLE · Commercial context available')).toBeVisible()
  await commercial.click()
  await expect(commercial).toHaveAttribute('aria-expanded', 'false')
  await expect(page.getByLabel('Open Omni assistant')).toBeVisible()

  const overflow = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)
  expect(overflow).toBeLessThanOrEqual(1)
  const lastDisclosure = page.locator('.account-workspace .ui-disclosure').last()
  await page.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight))
  const nav = await page.getByRole('navigation', { name: 'Mobile primary navigation' }).boundingBox()
  const disclosureBox = await lastDisclosure.boundingBox()
  expect((disclosureBox?.y ?? 0) + (disclosureBox?.height ?? 0)).toBeLessThanOrEqual(nav?.y ?? 844)
})

test('320px Customer Experience remains navigable without horizontal overflow', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 700 })
  await openPortfolio(page)
  await expect(page.locator('.portfolio-mobile-list .ui-mobile-row').first()).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
  await page.getByRole('searchbox', { name: 'Search Customers and Prospects' }).fill('Lockheed')
  await page.locator('.portfolio-mobile-list .ui-mobile-row').filter({ hasText: 'Lockheed Martin' }).click()
  await expect(page.getByRole('heading', { name: 'Lockheed Martin', level: 1 })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
})
