import { expect, test } from '@playwright/test'

async function openPortfolio(page) {
  await page.goto('/')
  await page.getByRole('navigation', { name: 'Primary navigation' }).getByRole('button', { name: 'Profiles' }).click()
  await expect(page.getByRole('heading', { name: 'Customers', level: 1 })).toBeVisible()
}

test('desktop Portfolio composes accessible search, filters, sorting, and canonical Customer navigation', async ({ page }) => {
  await openPortfolio(page)
  const table = page.getByRole('table', { name: 'Customers and Prospects' })
  await expect(table).toBeVisible()
  await expect(table.getByRole('columnheader', { name: /Customer \/ Prospect/ })).toHaveAttribute('aria-sort', 'ascending')

  await page.locator('.shared-filters').first().waitFor()
  if (await page.locator('.filter-mobile-trigger').first().isVisible()) await page.locator('.filter-mobile-trigger').first().click()
  await page.getByLabel('Customer scope').selectOption('ALL')
  await page.getByLabel('Industry', { exact: true }).selectOption('Defense')
  const active = page.getByLabel('Applied filters')
  await expect(active).toContainText('Defense')
  const activeDefense = active.getByRole('button', { name: 'Remove Industry: Defense filter' })
  await expect(activeDefense).toHaveAttribute('aria-pressed', 'true')
  await activeDefense.click()
  await expect(active).not.toContainText('Defense')

  const search = page.getByRole('searchbox', { name: 'Search Customers and Prospects' })
  await search.fill('Lockheed')
  const row = table.getByRole('row').filter({ hasText: 'Lockheed Martin' })
  await expect(row).toHaveCount(1)
  const profileLink = row.getByRole('link', { name: 'Lockheed Martin' })
  await profileLink.focus()
  await expect(profileLink).toBeFocused()
  await profileLink.press('Enter')
  await expect(page.getByRole('heading', { name: 'Lockheed Martin', level: 1 })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Organization decision summary' })).toContainText('Why it may matter')
  await expect(page.getByLabel('Demonstration environment')).toHaveText('Simulated data environment')
  await expect(page.getByLabel('Demonstration environment')).toHaveCount(1)
  await page.getByRole('tab', { name: 'Relationships', exact: true }).click()
  await expect(page.getByRole('button', { name: /People and relationship paths/ })).toBeVisible()

  await page.getByRole('searchbox', { name: 'Switch organization' }).fill('Symbotic')
  await page.getByRole('option', { name: /Symbotic/ }).click()
  await expect(page.getByRole('heading', { name: 'Symbotic', level: 1 })).toBeVisible()
  await page.getByRole('button', { name: '← Customers & Prospects' }).click()
  await page.goto('/#/accounts')
  await expect(table).toBeVisible()

  await page.getByRole('button', { name: /Customer Health/ }).click()
  await expect(table.getByRole('columnheader', { name: /Customer Health/ })).toHaveAttribute('aria-sort', 'descending')
  await search.fill('no canonical customer has this name')
  await expect(page.getByText(/No customers match the current search and filters/i)).toBeVisible()
  await search.fill('Lockheed')
  await expect(table.getByRole('link', { name: 'Lockheed Martin' })).toBeVisible()
  await expect(page.locator('.accounts-surface')).not.toContainText(/\b(Account|Accounts|Client|Clients|Company|Companies)\b/)
})

test('390px Portfolio keeps a semantic internally scrollable table and Customer 360 disclosures', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await openPortfolio(page)
  const table = page.getByRole('table', { name: 'Customers and Prospects' })
  await expect(table).toBeVisible()
  await expect(table.getByRole('columnheader')).toHaveCount(6)
  await expect(page.getByRole('searchbox', { name: 'Search Customers and Prospects' })).toBeVisible()
  await page.locator('.shared-filters').first().waitFor()
  if (await page.locator('.filter-mobile-trigger').first().isVisible()) await page.locator('.filter-mobile-trigger').first().click()
  await expect(page.getByLabel('Sort Customers and Prospects')).toBeVisible()
  await page.getByRole('searchbox', { name: 'Search Customers and Prospects' }).fill('Lockheed')
  await table.getByRole('link', { name: 'Lockheed Martin' }).click()
  await expect(page.getByRole('heading', { name: 'Lockheed Martin', level: 1 })).toBeVisible()

  await page.getByRole('tab', { name: 'Commercial', exact: true }).click()
  const decision = page.getByRole('button', { name: /Decision panel/ })
  if (await decision.getAttribute('aria-expanded') !== 'true') await decision.click()
  const commercial = page.getByRole('button', { name: /Commercial context/ })
  await expect(commercial).toHaveAttribute('aria-expanded', 'true')
  await commercial.click()
  await expect(commercial).toHaveAttribute('aria-expanded', 'false')
  await commercial.click()
  await expect(commercial).toHaveAttribute('aria-expanded', 'true')
  await expect(page.getByText(/Commercial context available/)).toBeVisible()
  await commercial.click()
  await expect(commercial).toHaveAttribute('aria-expanded', 'false')
  await expect(page.getByLabel('Open Omni assistant')).toBeVisible()

  const overflow = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)
  expect(overflow).toBeLessThanOrEqual(1)
  const lastDisclosure = page.locator('.account-workspace .ui-disclosure:visible').last()
  await page.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight))
  const nav = await page.getByRole('navigation', { name: 'Mobile primary navigation' }).boundingBox()
  const disclosureBox = await lastDisclosure.boundingBox()
  expect((disclosureBox?.y ?? 0) + (disclosureBox?.height ?? 0)).toBeLessThanOrEqual(nav?.y ?? 844)
})

test('320px Customer Experience remains navigable without horizontal overflow', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 700 })
  await openPortfolio(page)
  const table = page.getByRole('table', { name: 'Customers and Prospects' })
  await expect(table).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
  await page.getByRole('searchbox', { name: 'Search Customers and Prospects' }).fill('Lockheed')
  await table.getByRole('link', { name: 'Lockheed Martin' }).click()
  await expect(page.getByRole('heading', { name: 'Lockheed Martin', level: 1 })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
})

test('Portfolio sorts the complete filtered result set before pagination and keeps missing values last', async ({ page }) => {
  await openPortfolio(page)
  await page.locator('.shared-filters').first().waitFor()
  if (await page.locator('.filter-mobile-trigger').first().isVisible()) await page.locator('.filter-mobile-trigger').first().click()
  await page.getByLabel('Customer scope').selectOption('ALL')
  const table = page.getByRole('table', { name: 'Customers and Prospects' })
  const names = async () => table.locator('tbody th[scope="row"] a').allTextContents()
  const values = async (column) => table.locator(`tbody tr td:nth-child(${column})`).allTextContents()

  await table.getByRole('button', { name: /Customer Health/ }).click()
  const descendingScores = (await values(4)).map(value => value.match(/([\d.]+)\/100/)?.[1] ?? 'Unavailable')
  const knownDescending = descendingScores.filter(value => value !== 'Unavailable').map(Number)
  expect(knownDescending).toEqual([...knownDescending].sort((a, b) => b - a))
  expect(descendingScores.slice(knownDescending.length).every(value => value === 'Unavailable')).toBeTruthy()

  await table.getByRole('button', { name: /Customer Health/ }).click()
  const ascendingScores = (await values(4)).map(value => value.match(/([\d.]+)\/100/)?.[1] ?? 'Unavailable')
  const knownAscending = ascendingScores.filter(value => value !== 'Unavailable').map(Number)
  expect(knownAscending).toEqual([...knownAscending].sort((a, b) => a - b))
  expect(ascendingScores.slice(knownAscending.length).every(value => value === 'Unavailable')).toBeTruthy()

  await table.getByRole('button', { name: /^Priority/ }).click()
  const priorities = (await values(5)).map(value => value.trim())
  const rank = { High: 3, Medium: 2, Low: 1 }
  const knownPriorities = priorities.filter(value => value !== 'Unavailable')
  expect(knownPriorities.map(value => rank[value])).toEqual([...knownPriorities.map(value => rank[value])].sort((a, b) => b - a))

  await table.getByRole('button', { name: /Customer \/ Prospect/ }).click()
  await page.getByRole('button', { name: /Needs classification/ }).click()
  const firstPageNames = await names()
  await expect(page.getByRole('button', { name: 'Next', exact: true })).toBeEnabled()
  {
    await page.getByRole('button', { name: 'Next', exact: true }).click()
    const secondPageNames = await names()
    expect(firstPageNames.at(-1).localeCompare(secondPageNames[0], undefined, { sensitivity: 'base' })).toBeLessThanOrEqual(0)
  }

  await page.getByRole('button', { name: /Customer \/ Prospect/ }).click()
  const selectedName = (await names())[0]
  await table.getByRole('link', { name: selectedName, exact: true }).click()
  await page.getByRole('button', { name: '← Customers & Prospects' }).click()
  await expect(table.getByRole('columnheader', { name: /Customer \/ Prospect/ })).toHaveAttribute('aria-sort', 'descending')
  await expect(table.locator('tbody th[scope="row"] a').first()).toHaveText(selectedName)
})
