import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import ts from 'typescript'

const source = await readFile(new URL('../src/features/opportunities/opportunityFixture.ts', import.meta.url), 'utf8')
const { outputText } = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } })
const { opportunityFixture } = await import(`data:text/javascript;base64,${Buffer.from(outputText).toString('base64')}`)

async function enter(page, query = 'f.opportunity_fixture=demo') {
  await page.goto('/#/opportunities?' + query)
  const access = page.getByLabel('Access code', { exact: true })
  const heading = page.getByRole('heading', { name: 'Opportunities', level: 1, exact: true })
  await expect(access.or(heading)).toBeVisible()
  if (await access.isVisible()) {
    await access.fill('development-salesperson')
    await page.getByRole('button', { name: /Enter Project Beacon/ }).click()
  }
  await expect(heading).toBeVisible()
}
for (const width of [1440, 390]) {
  test(`row, next, Escape, focus and URL restore at ${width}`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 900 })
    const errors = [], failures = []
    page.on('pageerror', error => errors.push(error.message))
    page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
    page.on('response', response => { if (response.status() >= 400) failures.push(response.status() + ' ' + response.url()) })
    page.on('requestfailed', request => { if (!request.failure()?.errorText.includes('ABORTED')) failures.push(request.url()) })
    await enter(page)
    const row = width > 700 ? page.getByRole('row', { name: 'Honeywell, Structural brackets', exact: true }) : page.locator('.opp-mobile-card').filter({ hasText: 'Structural brackets' })
    await expect(row).toBeVisible()
    await page.evaluate(() => document.fonts.ready)
    expect(await page.locator('vite-error-overlay').count()).toBe(0)
    await page.screenshot({ path: info.outputPath('list.png'), fullPage: true })
    await row.focus()
    await page.keyboard.press('Enter')
    const dialog = page.getByRole('dialog')
    await expect(dialog).toHaveAccessibleName('Structural brackets')
    await expect(dialog).toContainText('82')
    await expect(dialog).toContainText('27 / 30')
    await dialog.getByRole('button', { name: 'Next opportunity', exact: true }).click()
    await expect(dialog).toHaveAccessibleName('Guidance sensor mounts')
    const selectedUrl = page.url()
    await page.screenshot({ path: info.outputPath('drawer.png'), fullPage: true })
    await page.keyboard.press('Escape')
    await expect(dialog).toHaveCount(0)
    await expect(row).toBeFocused()
    await page.goto(selectedUrl)
    await page.reload()
    await expect(dialog).toHaveAccessibleName('Guidance sensor mounts')
    await dialog.getByRole('button', { name: 'Close opportunity', exact: true }).focus()
    for (let i = 0; i < 12; i++) {
      await page.keyboard.press('Tab')
      expect(await dialog.evaluate(el => el.contains(document.activeElement))).toBe(true)
    }
    await page.keyboard.press('Escape')
    await expect(page.locator('[data-opportunity-id="dev-northrop"]').filter({ visible: true })).toBeFocused()
    await expect(page.locator('.opp-priority-number', { hasText: '45 to 75' }).filter({ visible: true })).toBeVisible()
    await page.getByRole('tab', { name: /Prospect/ }).click()
    await expect(page.locator(width > 700 ? '.opp-table-wrap' : '.opp-mobile-list')).toContainText('SpaceX')
    expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
    expect(errors).toEqual([])
    expect(failures).toEqual([])
  })
}
test('market, BU, stage, saved views, grouped subtotals and URL survive refresh', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await enter(page, 'f.opportunity_fixture=demo&f.lane=PROSPECT&f.opportunity_group=market&sort=value-desc')
  await expect(page.locator('.opp-group').filter({ hasText: 'Space' })).toContainText('$660K')
  await page.getByRole('button', { name: 'Market All', exact: true }).click()
  await page.getByRole('checkbox', { name: /Space/ }).check()
  await page.keyboard.press('Escape')
  await expect(page.getByText('2 of 5 shown')).toBeVisible()
  await page.reload()
  await expect(page.getByText('2 of 5 shown')).toBeVisible()
  await page.locator('.opp-group-toggle').filter({ hasText: 'Space' }).first().click()
  await expect(page.getByRole('row', { name: /SpaceX,/ })).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('row', { name: /SpaceX,/ })).toHaveCount(0)
  await page.locator('.opp-group-toggle').filter({ hasText: 'Space' }).first().click()
  await page.getByRole('button', { name: 'Durable best bets', exact: true }).click()
  await expect(page.getByText('1 of 5 shown')).toBeVisible()
  await page.getByRole('button', { name: 'Clear filters', exact: true }).click()
  await expect(page.getByRole('row', { name: /Boston Dynamics,/ })).toBeVisible()
  await page.getByRole('button', { name: 'BU All', exact: true }).click()
  await page.getByRole('button', { name: 'ERA', exact: true }).click()
  await page.keyboard.press('Escape')
  await expect(page.getByText('2 of 5 shown')).toBeVisible()
  await page.getByRole('button', { name: 'Stage All', exact: true }).click()
  await page.getByRole('button', { name: 'Qualification', exact: true }).click()
  await page.keyboard.press('Escape')
  await expect(page.getByText('1 of 5 shown')).toBeVisible()
})
test('mobile filter, sort and group sheets reuse controls', async ({ page }, info) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await enter(page)
  await page.getByRole('button', { name: 'Filters', exact: true }).click()
  await page.getByRole('dialog').getByRole('checkbox', { name: /Defense/ }).check()
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await expect(page.getByText('3 of 7 shown')).toBeVisible()
  await page.getByRole('button', { name: 'Sort', exact: true }).click()
  await page.getByRole('button', { name: 'Company, A to Z', exact: true }).click()
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await expect(page.locator('.opp-mobile-card').first()).toContainText('Lockheed Martin')
  await page.getByRole('button', { name: 'Group by None', exact: true }).click()
  await page.getByRole('button', { name: 'Market', exact: true }).click()
  await page.screenshot({ path: info.outputPath('group-sheet.png'), fullPage: true })
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await expect(page.locator('.opp-mobile-list .opp-group-toggle')).toContainText('Defense')
})
test('live API error retries; empty lane differs from filter empty', async ({ page }) => {
  let fail = true
  await page.route('**/api/accounts/workspace/opportunities', route => fail ? route.fulfill({ status: 503, json: { detail: 'Test unavailable' } }) : route.fulfill({ json: { opportunities: [], revision: 'test' } }))
  await enter(page, '')
  await expect(page.getByRole('alert')).toContainText('Opportunities could not be loaded')
  fail = false
  await page.getByRole('button', { name: 'Retry', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'No opportunities in this lane' })).toBeVisible()
  await enter(page)
  await page.getByRole('searchbox', { name: 'Filter opportunities', exact: true }).fill('no such pursuit')
  await expect(page.getByRole('heading', { name: 'No matches for these filters' })).toBeVisible()
  await page.locator('.opp-empty').getByRole('button', { name: 'Clear filters' }).click()
  await expect(page.getByRole('row', { name: 'Honeywell, Structural brackets', exact: true })).toBeVisible()
})

test('API-backed drawer reuses evidence, preserves context and opens canonical account', async ({ page }) => {
  const row = { ...opportunityFixture[0], account_id: 'honeywell', opportunity_id: 'pursuit-test', source_record_id: 'source-test' }
  await page.route('**/api/accounts/workspace/opportunities', route => route.fulfill({ json: { opportunities: [row], revision: 'test' } }))
  let evidenceRequests = 0
  await page.route('**/api/accounts/honeywell/commercial/evidence*', route => { evidenceRequests++; return route.fulfill({ json: { account_id: 'honeywell', revision: 'test', as_of: '2026-09-20', kind: 'OPPORTUNITY', truth_class: 'SAMPLE', record: { note: 'Scoped evidence fixture' } } }) })
  await enter(page, '')
  await page.getByRole('row', { name: 'Honeywell, Structural brackets', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('button', { name: 'Ask Omni', exact: true })).toBeEnabled()
  expect(evidenceRequests).toBe(0)
  await dialog.getByRole('button', { name: /Evidence/ }).click()
  await expect(dialog).toContainText('Scoped evidence fixture')
  // The development React StrictMode mount replays the evidence effect.
  expect(evidenceRequests).toBe(2)
  await expect(dialog.getByRole('link', { name: 'Open account' })).toHaveAttribute('href', /#\/accounts\/honeywell.*return=/)
  await page.mouse.click(10, 150)
  await expect(dialog).toHaveCount(0)
})

test('table header sort cycles, metrics remain lane-wide and groups keep Unassigned last', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await enter(page)
  const metrics = await page.locator('.opp-metrics').innerText()
  const company = page.getByRole('columnheader', { name: /Company/ })
  await company.getByRole('button').click()
  await expect(company).toHaveAttribute('aria-sort', 'ascending')
  await expect(page.locator('.opp-table-wrap tbody tr').first()).toContainText('Applied Materials')
  await company.getByRole('button').click()
  await expect(company).toHaveAttribute('aria-sort', 'descending')
  await company.getByRole('button').click()
  await expect(page.getByRole('columnheader', { name: /Priority/ })).toHaveAttribute('aria-sort', 'descending')
  await page.getByRole('searchbox', { name: 'Filter opportunities' }).fill('Honeywell')
  expect(await page.locator('.opp-metrics').innerText()).toBe(metrics)
  await page.getByRole('button', { name: 'Clear filters', exact: true }).click()
  await enter(page, 'f.opportunity_fixture=demo&f.lane=PROSPECT&f.opportunity_group=bu')
  await expect(page.locator('.opp-table-wrap .opp-group-toggle').last()).toContainText('Unassigned')
})
