import { test, expect } from '@playwright/test'
import { openRelationshipWorkspace } from './helpers.mjs'

for (const width of [1440, 390]) {
  test(`profiles and scoped opportunities remain distinct at ${width}`, async ({ page }, testInfo) => {
    const errors = []
    page.on('pageerror', error => errors.push(error.message))
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/#/opportunities')
    const access = page.getByLabel('Access code', { exact: true })
    const heading = page.getByRole('heading', { name: 'Opportunities', exact: true, level: 1 })
    await expect(access.or(heading)).toBeVisible()
    if (await access.isVisible()) {
      await access.fill('development-salesperson')
      await page.getByRole('button', { name: /Enter Project Beacon/ }).click()
    }
    await expect(heading).toBeVisible()
    await page.getByRole('searchbox', { name: 'Filter opportunities' }).fill('Honeywell')
    const pursuit = width > 700 ? page.getByRole('row', { name: 'Honeywell, APU service-support cover expansion', exact: true }) : page.locator('.opp-mobile-card').filter({ hasText: 'APU service-support cover expansion' })
    await pursuit.click()
    const detail = page.getByRole('dialog', { name: 'APU service-support cover expansion' })
    await expect(detail).toContainText('Existing releases do not establish demand')
    await expect(detail.getByRole('button', { name: /Evidence/ })).toHaveAttribute('aria-expanded', 'false')
    await page.reload()
    await expect(detail).toBeVisible()
    await page.screenshot({ path: testInfo.outputPath('opportunities.png'), fullPage: true })
    await detail.getByRole('link', { name: 'Open account', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Honeywell', level: 1, exact: true })).toBeVisible()
    await expect(page.locator('.profile-health-kpi')).toContainText('Customer health')
    await expect(page.locator('.profile-health-kpi')).not.toContainText('Attractiveness')
    expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
    await page.screenshot({ path: testInfo.outputPath(`customer-profile-${width}.png`), fullPage: true })
    await page.goBack()
    await expect(detail).toBeVisible()
    await page.getByRole('button', { name: 'Close opportunity' }).click()
    await expect(page.getByRole('searchbox', { name: 'Filter opportunities' })).toHaveValue('Honeywell')
    await page.getByRole('tab', { name: /Prospect/ }).click()
    await expect(page.getByRole('heading', { name: 'No matches for these filters' })).toBeVisible()
    await page.goto('/#/accounts/kla')
    const graph = await openRelationshipWorkspace(page)
    await graph.getByRole('combobox', { name: 'Component scope', exact: true }).selectOption('C2-KLA-01')
    await expect(graph).toHaveAttribute('aria-busy', 'false')
    await graph.getByRole('combobox', { name: 'Compare account', exact: true }).selectOption('spacex')
    await expect(graph.getByRole('combobox', { name: 'Compared component', exact: true }).locator('option[value="C2-SPACEX-01"]')).toHaveCount(1)
    await graph.getByRole('combobox', { name: 'Compared component', exact: true }).selectOption('C2-SPACEX-01')
    await expect(graph).toHaveAttribute('aria-busy', 'false')
    const response = page.waitForResponse(r => r.url().endsWith('/api/relationships/query') && r.request().postDataJSON()?.depth === 6)
    await graph.getByRole('combobox', { name: 'Search depth', exact: true }).selectOption('6')
    const result = await (await response).json()
    const route = result.evaluated_routes.find(route => route.hop_count === 5)
    expect(route).toBeTruthy()
    await graph.getByText('All returned routes · ordered text equivalent', { exact: true }).click()
    await graph.locator(`[data-route-id="${route.path_id}"]`).click()
    await expect(graph).toHaveAttribute('aria-busy', 'false')
    if (width < 760) await graph.getByRole('button', { name: 'Explore network', exact: true }).click()
    await graph.getByRole('button', { name: 'Fit selected route', exact: true }).click()
    await expect(graph).toHaveAttribute('aria-busy', 'false')
    const labels = await graph.locator('foreignObject button.active').evaluateAll(nodes => nodes.map(node => ({ clipped: node.scrollHeight > node.clientHeight || node.scrollWidth > node.clientWidth, rect: node.getBoundingClientRect().toJSON() })))
    expect(labels).toHaveLength(6)
    expect(labels.some(node => node.clipped)).toBe(false)
    const stage = await graph.locator('.ranked-stage').boundingBox()
    expect(labels.every(node => node.rect.left >= stage.x && node.rect.right <= stage.x + stage.width + 1)).toBe(true)
    for (let i = 0; i < labels.length; i++) for (let j = i + 1; j < labels.length; j++) {
      const a = labels[i].rect; const b = labels[j].rect
      expect(a.right <= b.left || b.right <= a.left || a.bottom <= b.top || b.bottom <= a.top).toBe(true)
    }
    expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
    await graph.screenshot({ path: testInfo.outputPath(`profile-graph-${width}.png`) })
    expect(errors).toEqual([])
  })
}
