import { test, expect } from '@playwright/test'

for (const width of [1440, 390]) test(`profile tabs, score explanation and investigation context at ${width}`, async ({ page }) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width, height: 900 })
  await page.goto('/#/accounts/honeywell')
  await expect(page.getByRole('heading', { name: 'Honeywell', level: 1, exact: true })).toBeVisible({ timeout: 30000 })
  const tabs = page.getByRole('tablist', { name: 'Profile sections' })
  await expect(tabs.getByRole('tab')).toHaveCount(6)
  await expect(tabs.getByRole('tab', { name: 'Overview', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(page.locator('.account-decision-zone')).toContainText('Customer health')
  await expect(page.locator('.account-decision-zone')).not.toContainText('Watch')
  const why = page.locator('.account-decision-zone').getByRole('button', { name: 'Why this?' })
  await why.click()
  const dialog = page.getByRole('dialog', { name: 'Why this?' })
  await expect(dialog).toBeVisible()
  await expect(dialog).toContainText('Calculated result:')
  await expect(dialog).toContainText('Data Coverage')
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(why).toBeFocused()
  await tabs.getByRole('tab', { name: 'Opportunities', exact: true }).click()
  await expect(page.locator('.account-decision-zone')).toBeHidden()
  await expect(page.getByRole('link', { name: 'View opportunities for Honeywell' })).toBeVisible()
  const draft = page.getByLabel('Planning objective', { exact: true })
  await draft.fill('Review supported program demand')
  await tabs.getByRole('tab', { name: 'Commercial', exact: true }).click()
  await expect(page.getByRole('button', { name: /Commercial decisions & follow-ups/ })).toBeVisible()
  await tabs.getByRole('tab', { name: 'Opportunities', exact: true }).click()
  await expect(draft).toHaveValue('Review supported program demand')
  await tabs.getByRole('tab', { name: 'Intelligence', exact: true }).click()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Honeywell', level: 1, exact: true })).toBeVisible({ timeout: 30000 })
  await expect(tabs.getByRole('tab', { name: 'Intelligence', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('button', { name: /Recent intelligence/ })).toBeVisible()
  await tabs.getByRole('tab', { name: 'Relationships', exact: true }).click()
  await expect(page.getByRole('button', { name: /People and relationship paths/ })).toBeVisible()
  await tabs.getByRole('tab', { name: 'More', exact: true }).click()
  const evidence = page.locator('#profile-tab-content .profile-page-section:not([hidden]) > .supporting-evidence > button')
  await expect(evidence).toHaveAttribute('aria-expanded', 'false')
  await evidence.click()
  await expect(page.getByRole('heading', { name: 'How this was determined' })).toBeVisible()
  if (width < 760) await page.getByRole('button', { name: 'Close supporting evidence' }).click()
  else await evidence.click()
  await tabs.getByRole('tab', { name: 'Overview', exact: true }).click()
  await tabs.getByRole('tab', { name: 'Overview', exact: true }).press('End')
  await expect(tabs.getByRole('tab', { name: 'More', exact: true })).toBeFocused()
  await tabs.getByRole('tab', { name: 'More', exact: true }).press('Home')
  await expect(tabs.getByRole('tab', { name: 'Overview', exact: true })).toBeFocused()
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
  if (process.env.BTX_UI_SCREENSHOTS) await page.screenshot({ path: `${process.env.BTX_UI_SCREENSHOTS}/profile-${width}.png`, fullPage: true })
  expect(errors).toEqual([])
})
