import { expect, test } from '@playwright/test'

for (const width of [390, 1440]) {
  test(`canonical neighborhood expansion, collapse and paging preserve route and coordinates at ${width}`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height: width === 390 ? 844 : 900 })
    await page.emulateMedia({ reducedMotion: 'reduce' })
    await page.goto('/#/accounts/kla')
    if (width < 760) await page.getByRole('button', { name: /Relationship Intelligence/ }).click()
    const section = page.getByRole('region', { name: 'Ranked canonical relationships', exact: true })
    await expect(section).toHaveAttribute('aria-busy', 'false')
    if (width < 760) await section.getByRole('button', { name: 'Explore network', exact: true }).click()
    const svg = section.getByRole('group', { name: 'Canonical relationship network' })
    const positions = () => svg.locator('foreignObject').evaluateAll(nodes => Object.fromEntries(nodes.map(node => [node.getAttribute('data-node-id'), [node.getAttribute('x'), node.getAttribute('y')]])))
    const before = await positions()
    const heading = await section.getByRole('heading', { name: /^Selected route/ }).textContent()
    const component = svg.locator('[data-node-id="SAMPLE:component_class:C2-KLA-01"] button')
    await component.focus()
    await page.keyboard.press('Enter')
    await expect(section).toContainText('Focused entity: Optical instrument housing. Selected route is unchanged.')
    const expansionResponse = page.waitForResponse(r => r.url().endsWith('/api/relationships/query') && r.request().postDataJSON()?.expanded_node_ids?.length === 1)
    await section.getByRole('button', { name: 'Expand focused entity', exact: true }).click()
    const expanded = await (await expansionResponse).json()
    await expect(section).toHaveAttribute('aria-busy', 'false')
    expect(expanded.graph.expanded_node_ids).toEqual(['SAMPLE:component_class:C2-KLA-01'])
    expect(expanded.graph.neighborhood_depth).toBe(2)
    expect(expanded.graph.context_complete).toBe(true)
    expect(expanded.graph.edges.some(edge => edge.expansion_owners.includes('expansion:SAMPLE:component_class:C2-KLA-01'))).toBe(true)
    const after = await positions()
    for (const id of Object.keys(before).filter(id => id in after)) expect(after[id]).toEqual(before[id])
    await expect(section.getByRole('heading', { name: /^Selected route/ })).toHaveText(heading)
    const collapseResponse = page.waitForResponse(r => r.url().endsWith('/api/relationships/query') && r.request().postDataJSON()?.expanded_node_ids?.length === 0)
    await section.getByRole('button', { name: 'Collapse focused entity', exact: true }).click()
    const collapsed = await (await collapseResponse).json()
    expect(collapsed.graph.selected_path_id).toBe(expanded.graph.selected_path_id)
    await expect(section).toHaveAttribute('aria-busy', 'false')
    if (width === 390) {
      expect(collapsed.graph.page_count).toBeGreaterThan(1)
      const pageResponse = page.waitForResponse(r => r.url().endsWith('/api/relationships/query') && r.request().postDataJSON()?.context_page === 1)
      await section.getByRole('button', { name: 'Next context page', exact: true }).click()
      const next = await (await pageResponse).json()
      expect(next.graph.selected_path_id).toBe(expanded.graph.selected_path_id)
      const route = next.evaluated_routes.find(route => route.path_id === next.graph.selected_path_id)
      expect(route.edge_ids.every(id => next.graph.edges.some(edge => edge.id === id))).toBe(true)
      await expect(section).toHaveAttribute('aria-busy', 'false')
      await section.getByRole('button', { name: 'Previous context page', exact: true }).click()
      await expect(section).toHaveAttribute('aria-busy', 'false')
    }
    await section.getByText('Visible assertions · keyboard and text equivalent', { exact: true }).click()
    const list = section.locator('details').filter({ has: page.getByText('Visible assertions · keyboard and text equivalent', { exact: true }) })
    await list.getByRole('button').first().click()
    await expect(section.getByText(/Original direction:/)).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
    await testInfo.attach('context-selection', { body: JSON.stringify({ width, expanded: expanded.graph, collapsed: collapsed.graph }, null, 2), contentType: 'application/json' })
    await section.screenshot({ path: testInfo.outputPath(`neighborhood-${width}.png`) })
  })
}
