import { expect, test } from '@playwright/test'

async function navigate(page, name) {
  await page.getByRole('navigation', { name: 'Primary navigation' }).getByRole('button', { name }).click()
}

test('desktop Today presents truthful priority, meaning, action, and evidence', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Today', level: 1 })).toBeVisible()
  const distribution = page.getByRole('region', { name: 'Commercial review priority distribution' })
  await expect(distribution).toContainText('High')
  await expect(distribution).toContainText('Medium')
  await expect(distribution).toContainText('Low')
  const attention = page.getByRole('heading', { name: 'Seller attention' }).locator('..').locator('..')
  await expect(attention).toContainText('Why:')
  await expect(attention).toContainText('Next:')
  await expect(attention).toContainText('SAMPLE BTX commercial context')
  await expect(page.getByRole('heading', { name: 'Public intelligence' })).toBeVisible()
  await page.getByRole('button', { name: 'View Intelligence' }).click()
  await expect(page.getByRole('heading', { name: 'Intelligence', level: 1 })).toBeVisible()

  await navigate(page, 'Today')
  const customer = page.locator('.today-attention-item .today-customer-link').first()
  const customerName = await customer.textContent()
  await customer.click()
  await expect(page.getByRole('heading', { name: customerName ?? '', level: 1 })).toBeVisible()
  await expect(page.locator('.today-surface')).toHaveCount(0)
})

test('desktop Intelligence composes search and canonical filters with evidence and Omni selection', async ({ page }) => {
  await page.goto('/')
  await navigate(page, 'Intelligence')
  const search = page.getByRole('searchbox', { name: 'Search Intelligence' })
  await search.fill('Lockheed')
  await expect(page.locator('.intelligence-signal')).toHaveCount(1)
  await expect(page.locator('.intelligence-signal')).toContainText('Lockheed Martin')

  await page.getByLabel('Filter Intelligence by industry').selectOption({ label: 'Defense' })
  await expect(page.locator('.intelligence-signal')).toHaveCount(1)
  const active = page.getByLabel('Active Intelligence filters')
  await expect(active.getByRole('button', { name: 'Remove Defense filter' })).toHaveAttribute('aria-pressed', 'true')
  await search.fill('no governed signal matches this')
  await expect(page.getByText(/No governed Intelligence matches/)).toBeVisible()
  await page.getByRole('button', { name: 'Clear all' }).click()
  await expect(page.locator('.intelligence-signal').first()).toBeVisible()

  const signal = page.locator('.intelligence-signal').first()
  const evidence = signal.getByRole('button', { name: /Evidence/ })
  await expect(evidence).toHaveAttribute('aria-expanded', 'false')
  await evidence.click()
  await expect(evidence).toHaveAttribute('aria-expanded', 'true')
  await expect(signal.locator('.ui-evidence')).toContainText('Source:')
  const useInOmni = signal.getByRole('button', { name: 'Use in Omni' })
  await useInOmni.click()
  await expect(signal.getByRole('button', { name: 'Clear Omni event' })).toHaveAttribute('aria-pressed', 'true')
  await page.getByLabel('Open Omni assistant').click()
  await expect(page.getByRole('dialog', { name: 'Omni' })).toBeVisible()
})

test('mobile Today and Intelligence remain touch-usable at 390px and 320px without overflow', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.locator('.today-priority-summary')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Seller attention' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
  await page.getByRole('navigation', { name: 'Mobile primary navigation' }).getByRole('button', { name: 'Intelligence' }).click()
  await expect(page.getByRole('searchbox', { name: 'Search Intelligence' })).toBeVisible()
  await expect(page.getByLabel('Filter Intelligence by industry')).toBeVisible()
  await expect(page.locator('.intelligence-signal').first()).toBeVisible()
  await page.locator('.intelligence-signal').first().getByRole('button', { name: /Evidence/ }).click()
  await expect(page.locator('.intelligence-signal').first().locator('.ui-evidence')).toBeVisible()
  await expect(page.getByLabel('Open Omni assistant')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)

  await page.setViewportSize({ width: 320, height: 700 })
  await expect(page.getByRole('searchbox', { name: 'Search Intelligence' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
  await page.getByRole('navigation', { name: 'Mobile primary navigation' }).getByRole('button', { name: 'Today' }).click()
  await expect(page.locator('.today-priority-summary')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
})
