import { expect, test } from '@playwright/test'

async function navigate(page, name) {
  await page.getByRole('navigation', { name: 'Primary navigation' }).getByRole('button', { name }).click()
}

test('desktop Today presents truthful priority, meaning, action, and evidence', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Today', level: 1 })).toBeVisible()
  const distribution = page.getByRole('region', { name: 'Commercial Review priority distribution' })
  await expect(distribution).toContainText('High')
  await expect(distribution).toContainText('Medium')
  await expect(distribution).toContainText('Low')
  const attention = page.getByRole('heading', { name: 'What changed / needs attention' }).locator('..').locator('..')
  await expect(attention).toContainText('Why:')
  await expect(attention).toContainText('Next:')
  await expect(attention).toContainText('SAMPLE BTX commercial context')
  await expect(page.getByRole('heading', { name: 'Public intelligence', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'View Intelligence' }).click()
  await expect(page.getByRole('heading', { name: 'Intelligence', level: 1 })).toBeVisible()

  await navigate(page, 'Today')
  const customer = page.locator('.today-attention-item .today-customer-link').first()
  const customerName = await customer.textContent()
  await customer.click()
  await expect(page.getByRole('heading', { name: customerName ?? '', level: 1 })).toBeVisible()
  await expect(page.locator('.today-surface')).toHaveCount(0)
})

test('Today consumes projected priority, market hubs, and curated IDs without substitution', async ({ page }) => {
  await page.goto('/')
  const payload = await page.evaluate(async () => (await fetch('/api/today')).json())
  const projectedPriority = payload.command_center.priority_briefing.map(item => item.id)
  await expect(page.locator('[data-priority-id]')).toHaveCount(projectedPriority.length)
  expect(await page.locator('[data-priority-id]').evaluateAll(nodes => nodes.map(node => node.getAttribute('data-priority-id')))).toEqual(projectedPriority)

  const commercial = payload.command_center.priority_briefing.filter(item => item.kind === 'COMMERCIAL_REVIEW')
  const publicSignals = payload.command_center.priority_briefing.filter(item => item.kind === 'PUBLIC_SIGNAL')
  await expect(page.locator('[data-priority-id]').filter({ hasText: 'SAMPLE BTX commercial context' })).toHaveCount(commercial.length)
  for (const item of commercial) {
    const card = page.locator(`[data-priority-id="${item.id}"]`)
    await card.getByRole('button', { name: 'Evidence and governed action' }).click()
    await expect(card.getByRole('button', { name: 'Create action' })).toBeVisible()
  }
  for (const item of publicSignals) await expect(page.locator(`[data-priority-id="${item.id}"]`).getByRole('button', { name: 'Create action' })).toHaveCount(0)

  const defense = payload.command_center.market_hubs.find(hub => hub.market === 'Defense')
  await page.getByRole('navigation', { name: 'Market hubs' }).getByRole('button', { name: /Defense/ }).click()
  await expect(page.getByRole('heading', { name: 'Defense coverage and gaps' })).toBeVisible()
  const watchPanel = page.getByRole('heading', { name: 'Recommended Customer watchlist' }).locator('..').locator('..')
  const programPanel = page.getByRole('heading', { name: 'Watched programs' }).locator('..').locator('..')
  await expect(watchPanel.locator('.today-watch-list > button')).toHaveCount(Math.min(12, defense.watched_account_ids.length))
  await expect(programPanel.locator('.today-watch-list > button')).toHaveCount(defense.watched_program_ids.length)
  const coverage = page.getByRole('heading', { name: 'Defense coverage and gaps' }).locator('..').locator('..')
  for (const gap of defense.gaps) await expect(coverage).toContainText(gap)

  await page.getByRole('navigation', { name: 'Market hubs' }).getByRole('button', { name: /All markets/ }).click()
  await expect(page.getByRole('heading', { name: 'Coverage and source freshness' })).toBeVisible()
  await expect(watchPanel.locator('.today-watch-list > button')).toHaveCount(Math.min(12, payload.command_center.watched_accounts.length))

  const intelligence = await page.evaluate(async () => (await fetch('/api/intelligence')).json())
  const projected = new Set(payload.command_center.curated_reference_signal_ids)
  const expectedCurated = intelligence.signals.filter(signal => projected.has(signal.id) && signal.data_mode === 'CURATED_PUBLIC')
  const curatedPanel = page.getByRole('heading', { name: 'Public intelligence', exact: true }).locator('..').locator('..')
  await expect(curatedPanel.locator('.seller-signal-brief')).toHaveCount(expectedCurated.length)
})

test('desktop Intelligence composes search and canonical filters with evidence and Omni selection', async ({ page }) => {
  await page.goto('/')
  await navigate(page, 'Intelligence')
  const search = page.getByRole('searchbox', { name: 'Search Intelligence' })
  await search.fill('Lockheed')
  await expect(page.locator('.intelligence-card')).toHaveCount(1)
  await expect(page.locator('.intelligence-card')).toContainText('Lockheed Martin')

  await page.getByLabel('Filter Intelligence by market').selectOption({ label: 'Defense' })
  await expect(page.locator('.intelligence-card')).toHaveCount(1)
  const active = page.locator('.intelligence-active-filters')
  await expect(active.getByRole('button', { name: 'Remove Market: Defense filter' })).toHaveAttribute('aria-pressed', 'true')
  await search.fill('no governed signal matches this')
  await expect(page.getByText(/No governed Intelligence matches/)).toBeVisible()
  await page.getByRole('button', { name: 'Clear all' }).click()
  await expect(page.locator('.intelligence-card').first()).toBeVisible()

  const signal = page.locator('.intelligence-card').first()
  const evidence = signal.getByRole('button', { name: /Evidence/ })
  await expect(evidence).toHaveAttribute('aria-expanded', 'false')
  await evidence.click()
  await expect(evidence).toHaveAttribute('aria-expanded', 'true')
  await expect(signal.locator('.ui-evidence')).toContainText('Source:')
  const useInOmni = signal.getByRole('button', { name: 'Use in Omni' })
  await useInOmni.click()
  await expect(signal.getByRole('button', { name: 'Clear Omni event' })).toHaveAttribute('aria-pressed', 'true')
  await page.getByLabel('Open Omni assistant').click()
  await expect(page.getByRole('dialog', { name: 'Omni' })).toBeVisible()
})

test('mobile Today and Intelligence remain touch-usable at 390px and 320px without overflow', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.locator('.today-priority-summary')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'What changed / needs attention' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
  await page.getByRole('navigation', { name: 'Mobile primary navigation' }).getByRole('button', { name: 'Intelligence' }).click()
  await expect(page.getByRole('searchbox', { name: 'Search Intelligence' })).toBeVisible()
  await expect(page.getByLabel('Filter Intelligence by market')).toBeVisible()
  await expect(page.locator('.intelligence-card').first()).toBeVisible()
  await page.locator('.intelligence-card').first().getByRole('button', { name: /Evidence/ }).click()
  await expect(page.locator('.intelligence-card').first().locator('.ui-evidence')).toBeVisible()
  await expect(page.getByLabel('Open Omni assistant')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)

  await page.setViewportSize({ width: 320, height: 700 })
  await expect(page.getByRole('searchbox', { name: 'Search Intelligence' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
  await page.getByRole('navigation', { name: 'Mobile primary navigation' }).getByRole('button', { name: 'Today' }).click()
  await expect(page.locator('.today-priority-summary')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
})
