import { expect, test } from '@playwright/test'

for (const width of [390, 1440]) {
  test(`Today reference cards and briefing share filtered order and navigation state at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/#/today')
    const payload = await (await page.request.get('/api/today')).json()
    const source = payload.command_center.priority_briefing
    const ids = rows => rows.map(row => row.id)
    const read = attribute => page.locator(`[${attribute}]`).evaluateAll((nodes, key) => nodes.map(node => node.getAttribute(key)), attribute)
    async function parity(expected) {
      await expect(page.locator('[data-priority-id]')).toHaveCount(expected.length)
      expect(await read('data-priority-id')).toEqual(ids(expected))
      expect(await read('data-summary-id')).toEqual(ids(expected).slice(0, 3))
      expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
    }
    await parity(source)
    await page.getByRole('button', { name: 'Public intelligence', exact: true }).click()
    await parity(source.filter(item => item.kind === 'PUBLIC_SIGNAL'))
    await page.getByRole('button', { name: 'Internal intelligence', exact: true }).click()
    const item = source.find(item => item.kind === 'COMMERCIAL_REVIEW' && item.business_unit_ids?.length)
    expect(item).toBeTruthy()
    await page.getByLabel('Filter priorities by customer or prospect').selectOption(item.account_id)
    await page.getByLabel('Filter priorities by business unit').selectOption(item.business_unit_ids[0])
    const expected = source.filter(row => row.kind === 'COMMERCIAL_REVIEW' && row.account_id === item.account_id && row.business_unit_ids?.includes(item.business_unit_ids[0]))
    await parity(expected)
    await page.getByRole('button', { name: 'Review priority' }).first().focus()
    await page.keyboard.press('Enter')
    await expect(page.locator('[data-priority-id]').first()).toBeFocused()
    await page.locator('[data-priority-id]').first().getByRole('button', { name: 'Evidence and governed action' }).click()
    await expect(page.locator('[data-priority-id]').first()).toContainText(item.evidence_ids[0])
    await page.locator('[data-priority-id]').first().locator('.today-customer-link').click()
    await expect(page).toHaveURL(new RegExp(`#/accounts/${item.account_id}$`))
    await page.goBack()
    await expect(page.getByLabel('Filter priorities by customer or prospect')).toHaveValue(item.account_id)
    await expect(page.getByLabel('Filter priorities by business unit')).toHaveValue(item.business_unit_ids[0])
    await parity(expected)
    await page.locator('[data-priority-id]').first().getByRole('button', { name: 'Evidence and governed action' }).click()
    await page.locator('[data-priority-id]').first().getByRole('button', { name: 'Create action', exact: true }).click()
    await expect(page).toHaveURL(/#\/actions$/)
    await expect(page.getByLabel('Selected Today priority')).toBeVisible()
    const actions = await (await page.request.get('/api/actions')).json()
    const recommendation = actions.suggestions.find(suggestion => suggestion.source_alert_id === expected[0].id)
    expect(recommendation).toBeTruthy()
    await page.getByLabel('Suggestion visibility').selectOption('ALL')
    await expect(page.locator('.suggestion-card')).toHaveCount(1)
    await expect(page.locator('.suggestion-card')).toHaveAttribute('data-suggestion-id', recommendation.id)
    await page.locator('.suggestion-card').getByRole('button', { name: 'Evidence references' }).click()
    for (const evidenceId of expected[0].evidence_ids) await expect(page.locator('.suggestion-card')).toContainText(evidenceId)
  })
}
