"""Clean POC SQLAlchemy schema; domain objects remain framework-free."""
from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    ForeignKey,
    Integer,
    MetaData,
    Numeric,
    String,
    Table,
    Text,
)

metadata = MetaData()
accounts = Table("accounts", metadata, Column("id", String(64), primary_key=True), Column("name", String(300), nullable=False), Column("relationship", String(32), nullable=False), Column("domain", String(300)))
facilities = Table("facilities", metadata, Column("id", String(64), primary_key=True), Column("account_id", ForeignKey("accounts.id"), nullable=False), Column("city", String(120), nullable=False), Column("region", String(64), nullable=False), Column("latitude", String(32), nullable=False), Column("longitude", String(32), nullable=False))
external_ranks = Table("external_industry_ranks", metadata, Column("account_id", ForeignKey("accounts.id"), primary_key=True), Column("industry", String(100), primary_key=True), Column("rank", Integer, nullable=False), Column("source", String(300), nullable=False))
identity_mappings = Table("identity_mappings", metadata, Column("source_key", String(300), primary_key=True), Column("account_id", ForeignKey("accounts.id"), nullable=False))
score_configurations = Table("score_configurations", metadata, Column("id", String(64), primary_key=True), Column("version", String(80), nullable=False), Column("hypothesis", Boolean, nullable=False), Column("interpretation_note", Text, nullable=False), Column("created_at", DateTime(timezone=True), nullable=False))
score_assessments = Table("score_assessments", metadata, Column("id", String(64), primary_key=True), Column("account_id", ForeignKey("accounts.id"), nullable=False), Column("configuration_id", ForeignKey("score_configurations.id"), nullable=False), Column("status", String(32), nullable=False), Column("score", Numeric(5, 2)), Column("coverage", Numeric(5, 4), nullable=False), Column("evidence_ids", Text, nullable=False), Column("missing_fields", Text, nullable=False), Column("calculated_at", DateTime(timezone=True), nullable=False))
commercial_alerts = Table("commercial_alerts", metadata, Column("id", String(160), primary_key=True), Column("type", String(64), nullable=False), Column("account_id", ForeignKey("accounts.id"), nullable=False), Column("business_unit", String(100)), Column("severity", String(16), nullable=False), Column("trigger_reason", Text, nullable=False), Column("actual_value", Text, nullable=False), Column("threshold", Text, nullable=False), Column("evidence_ids", Text, nullable=False), Column("observed_at", DateTime(timezone=True), nullable=False), Column("recommended_action", Text, nullable=False), Column("owner_id", String(128)), Column("status", String(32), nullable=False), Column("synthetic", Boolean, nullable=False), Column("provenance_state", String(32), nullable=False))
intelligence_signals = Table("intelligence_signals", metadata, Column("id", String(64), primary_key=True), Column("type", String(64), nullable=False), Column("account_id", ForeignKey("accounts.id")), Column("program_name", String(300)), Column("source_url", Text, nullable=False), Column("evidence_state", String(32), nullable=False), Column("evidence_ids", Text, nullable=False), Column("occurred_at", DateTime(timezone=True), nullable=False))
commercial_matches = Table("commercial_matches", metadata, Column("component_id", String(64), primary_key=True), Column("quote_id", String(64), primary_key=True), Column("account_id", ForeignKey("accounts.id")), Column("method", String(32), nullable=False), Column("review_state", String(32), nullable=False), Column("evidence_state", String(32), nullable=False), Column("evidence_ids", Text, nullable=False), Column("business_unit", String(100)))
work_items = Table("work_items", metadata, Column("id", String(64), primary_key=True), Column("account_id", ForeignKey("accounts.id"), nullable=False), Column("opportunity_id", String(64)), Column("status", String(32), nullable=False), Column("summary", Text, nullable=False), Column("evidence_ids", Text, nullable=False), Column("owner_id", String(128)), Column("priority", String(16), nullable=False), Column("due_date", String(16)), Column("notes", Text), Column("idempotency_key", String(128), nullable=False, unique=True), Column("created_at", DateTime(timezone=True), nullable=False))
work_audit_events = Table("work_audit_events", metadata, Column("id", Integer, primary_key=True), Column("work_item_id", ForeignKey("work_items.id"), nullable=False), Column("event", String(32), nullable=False), Column("actor_id", String(128), nullable=False), Column("occurred_at", DateTime(timezone=True), nullable=False), Column("note", Text))
assistant_turns = Table("assistant_turns", metadata, Column("id", String(64), primary_key=True), Column("account_id", ForeignKey("accounts.id"), nullable=False), Column("content", Text, nullable=False), Column("citation_ids", Text, nullable=False), Column("created_at", DateTime(timezone=True), nullable=False))
monitor_observations = Table("monitor_observations", metadata, Column("id", String(160), primary_key=True), Column("source_id", String(100), nullable=False), Column("source_record_id", String(300), nullable=False), Column("source_version", String(300)), Column("content_hash", String(64), nullable=False), Column("canonical_url", Text, nullable=False), Column("published_at", DateTime(timezone=True)), Column("retrieved_at", DateTime(timezone=True), nullable=False), Column("source_tier", String(64), nullable=False), Column("collection_run_id", String(64), nullable=False), Column("payload_reference", Text), Column("title", Text), Column("structured_payload", Text), Column("created_at", DateTime(timezone=True), nullable=False))
monitor_collection_runs = Table("monitor_collection_runs", metadata, Column("id", String(64), primary_key=True), Column("source_id", String(100), nullable=False), Column("started_at", DateTime(timezone=True), nullable=False), Column("completed_at", DateTime(timezone=True)), Column("cursor", Text), Column("records_seen", Integer, nullable=False), Column("records_new", Integer, nullable=False), Column("records_changed", Integer, nullable=False), Column("records_rejected", Integer, nullable=False), Column("events_created", Integer, nullable=False), Column("events_matched", Integer, nullable=False), Column("failures", Text, nullable=False), Column("latency_ms", Integer))
monitor_source_health = Table("monitor_source_health", metadata, Column("source_id", String(100), primary_key=True), Column("state", String(32), nullable=False), Column("last_attempt_at", DateTime(timezone=True), nullable=False), Column("last_success_at", DateTime(timezone=True)), Column("warning_code", String(64)), Column("detail", Text), Column("updated_at", DateTime(timezone=True), nullable=False))
monitor_event_clusters = Table("monitor_event_clusters", metadata, Column("id", String(64), primary_key=True), Column("event_id", String(160), nullable=False), Column("observation_ids", Text, nullable=False), Column("evidence_ids", Text, nullable=False), Column("related_event_ids", Text, nullable=False), Column("ambiguity_reason", Text))
monitor_source_versions = Table("monitor_source_versions", metadata, Column("source_id", String(100), primary_key=True), Column("source_record_id", String(300), primary_key=True), Column("version_id", String(300)), Column("content_hash", String(64), nullable=False), Column("first_seen_at", DateTime(timezone=True), nullable=False), Column("last_seen_at", DateTime(timezone=True), nullable=False), Column("changed_at", DateTime(timezone=True)), Column("last_observation_id", String(160), nullable=False))
monitor_events = Table("monitor_events", metadata, Column("id", String(160), primary_key=True), Column("source_id", String(100), nullable=False), Column("source_observation_id", String(160), nullable=False), Column("event_type", String(80), nullable=False), Column("publication_date", DateTime(timezone=True)), Column("collected_at", DateTime(timezone=True), nullable=False), Column("updated_at", DateTime(timezone=True), nullable=False), Column("resolution_state", String(32), nullable=False), Column("seller_relevance_state", String(48), nullable=False, server_default="UNRESOLVED"), Column("data_mode", String(32), nullable=False), Column("provenance_source_id", String(300), nullable=False), Column("provenance_url", Text), Column("evidence_ids", Text, nullable=False), Column("event_payload", Text, nullable=False))
monitor_rejected_observations = Table("monitor_rejected_observations", metadata, Column("id", String(200), primary_key=True), Column("collection_run_id", String(64), nullable=False), Column("source_id", String(100), nullable=False), Column("observation_id", String(160), nullable=False), Column("state", String(64), nullable=False), Column("reason", Text, nullable=False), Column("evidence_id", String(160), nullable=False), Column("rejected_at", DateTime(timezone=True), nullable=False))
