import type { Account360 } from '../../types/api'
import type { WorkspaceLocation } from '../../app/navigation'
import { workspaceHash } from '../../app/navigation'
import { WhyThis } from '../../components/SupportingEvidence'
import { ScoreSummary } from '../../components/ScoreSummary'
import { commercialDecisionSummary, prospectFitSummary } from '../../components/scoreSummaryModel'
import { RevenueChart } from './ProfileMetrics'
import './profiles-redesign.css'

const money = (value: number | null | undefined, currency = 'USD') => value == null ? 'Unknown' : new Intl.NumberFormat('en-US', { style: 'currency', currency, maximumFractionDigits: 0 }).format(value / 100)
const decimal = (value: string | null | undefined) => value == null ? 'Unknown' : Number(value).toFixed(2)

export function ProfileOverview({ detail, location }: { detail: Account360; location: WorkspaceLocation }) {
  const profile = detail.profile
  const ledger = detail.commercial_ledger?.ttm ? detail.commercial_ledger : null
  const customer = detail.organization_360.mode === 'CUSTOMER'
  const name = detail.account.name ?? detail.account.legal_name ?? detail.account.id
  const currency = ledger?.currency ?? 'USD'
  const opportunityLink = workspaceHash({ surface: 'opportunities', filters: { account: detail.account.id, lane: customer ? 'CUSTOMER_EXPANSION' : 'PROSPECT' }, returnTo: location })
  const items = [
    ...profile.public_risk_events.map(row => ({ id: row.underlying_event_id, type: 'Public risk', label: row.risk_domain })),
    ...profile.open_internal_items.map(row => ({ id: row.id, type: 'Internal alert', label: row.trigger_reason })),
  ]
  const days = profile.last_activity_at && ledger?.as_of ? Math.floor((Date.parse(ledger.as_of) - Date.parse(profile.last_activity_at)) / 86400000) : null
  return <div className="profile-overview">
    <aside className="profile-sample-banner"><strong>SAMPLE</strong> {ledger ? `Commercial snapshot ${ledger.as_of}.` : 'No linked commercial ledger.'} Public sources, simulated role contacts and missing inputs are distinguished below.</aside>
    {customer ? <><div className="profile-kpis">
      <section className="profile-kpi profile-health-kpi"><span>Health</span>{detail.customer_health ? <><ScoreSummary compact model={commercialDecisionSummary(detail.customer_health, name)} /><small>Data Coverage {(Number(detail.customer_health.data_coverage.ratio) * 100).toFixed(0)}%</small><WhyThis><p>Calculated result: {detail.customer_health.score ?? `${detail.customer_health.score_range?.low}–${detail.customer_health.score_range?.high}`}</p><p>Data Coverage {(Number(detail.customer_health.data_coverage.ratio) * 100).toFixed(0)}%. Missing factors produce a range, not an assumed score.</p><ul>{detail.customer_health.factors.map(row => <li key={row.key}>{row.key}: {row.reason}</li>)}</ul></WhyThis></> : <strong>Unknown</strong>}<small>Band: {profile.health_band ?? 'not configured'}</small></section>
      <section className="profile-kpi"><span>Overall risk</span><strong>{profile.overall_customer_risk.score ?? 'Unknown'}</strong><small>{profile.overall_customer_risk.missing_fields?.length ? 'Data Coverage incomplete' : 'Required inputs available'}</small><p>Public: {profile.public_risk_rollup.score ?? 'Unknown'} · Data Coverage {profile.public_risk_rollup.score == null ? 'unknown' : 'see evidence'}</p>{profile.internal_commercial_risk && <><ScoreSummary compact model={commercialDecisionSummary(profile.internal_commercial_risk, name)} /><small>Data Coverage {(Number(profile.internal_commercial_risk.data_coverage.ratio) * 100).toFixed(0)}%</small></>}</section>
      <section className="profile-kpi"><span>Open items</span><strong>{profile.open_items.public} public</strong><p>{profile.open_items.internal} internal</p><small>Known active records, not complete monitoring coverage.</small></section>
      <section className="profile-kpi"><span>Expansion opportunities</span><strong><a href={opportunityLink}>{profile.expansion_opportunity_count ?? 'Unknown'}</a></strong><p>Account-scoped pursuits</p></section>
      <section className="profile-kpi"><span>Open orders</span><strong>{profile.open_order_count ?? 'Unknown'}</strong><p>{money(profile.open_order_value_minor, currency)} open</p><small>After shipments and cancellations</small></section>
      <section className="profile-kpi"><span>Backlog months</span><strong>{decimal(profile.backlog_months)}</strong><p>Committed remaining value / average monthly revenue</p></section>
    </div><div className="profile-overview-grid"><section className="profile-card"><h2>TTM commercial activity</h2>{ledger ? <><p>Revenue {money(ledger.ttm.revenue_minor, currency)} · Bookings {money(ledger.ttm.bookings_minor, currency)}</p><RevenueChart months={ledger.monthly_history} currency={currency} /></> : <p>Monthly history unavailable.</p>}</section><section className="profile-card"><h2>Quote pipeline</h2><p>Past decision date share: {profile.quote_overdue_share == null ? 'Unknown' : `${(Number(profile.quote_overdue_share) * 100).toFixed(1)}%`}</p><p>Existing calculation, value-weighted open quotes.</p><div className="profile-table-wrap"><table className="profile-table"><thead><tr><th>Recent quote</th><th>Value</th><th>Status</th></tr></thead><tbody>{detail.customer_360.quotes.records.map(row => <tr key={row.id}><td>{row.id}</td><td>{money(row.value_minor, row.currency)}</td><td>{row.status ?? 'Unknown'}</td></tr>)}</tbody></table></div>{!detail.customer_360.quotes.records.length && <p>{detail.customer_360.quotes.missing ?? 'No linked quotes'}</p>}<small>Bounded recent records. Full tables in Commercial.</small></section></div>
    <div className="profile-overview-grid"><section className="profile-card"><h2>Relationship coverage by function</h2><div className="profile-coverage">{profile.function_coverage.map(row => <div key={row.function}><strong>{row.function}</strong><small>{row.state} · {row.source_state}</small><small>{row.verification_scope.join(', ') || 'Verification unknown'}</small></div>)}</div>{!profile.function_coverage.length && <p>Function coverage unknown; research is not complete.</p>}</section><section className="profile-card"><h2>Activity & concentration</h2><p>Last CRM activity: {profile.last_activity_at?.slice(0, 10) ?? 'Unknown'}{days != null && days >= 0 ? ` · ${days} days before snapshot` : ''}</p><p>Last recorded two-way interaction: {profile.last_two_way_at ?? 'Unknown'}</p><p>Expected touch cadence: {profile.expected_touch_days == null ? 'Unknown' : `${profile.expected_touch_days} days`}</p><small>CRM activity is not automatically a meaningful touch.</small><p>BU revenue concentration: {profile.concentration.share == null ? 'Unknown' : `${(Number(profile.concentration.share) * 100).toFixed(1)}%`}</p></section></div>
    </> : <><section className="profile-card"><h2>Prospect Fit</h2>{detail.prospect_fit?.applicable ? <><ScoreSummary model={prospectFitSummary(detail.prospect_fit, name)} /><p>Data Coverage {(Number(detail.prospect_fit.coverage) * 100).toFixed(0)}%. Missing factors remain a range.</p><table className="profile-table"><thead><tr><th>Factor</th><th>Observed points</th><th>Evidence / missingness</th></tr></thead><tbody>{detail.prospect_fit.factors.map(row => <tr key={row.name}><td>{row.label}</td><td>{row.points ?? 'Unknown'}</td><td>{row.reason}</td></tr>)}</tbody></table></> : <p>Classification requires review; no applicable Fit assessment.</p>}</section><section className="profile-card"><h2>Market & access</h2><p>Target market: {detail.account.industries.join(', ') || 'Unknown'}</p><p>Access level: {detail.public_relationship?.state ?? 'Unknown'}</p><p>{detail.public_relationship?.basis ?? 'No verified route is implied.'}</p><h3>Evidenced sites</h3>{detail.public_facilities.length ? <ul>{detail.public_facilities.map(row => <li key={row.id}>{row.name} · {row.city}, {row.region} · {row.verification_state}</li>)}</ul> : <p>No evidenced site projected.</p>}</section></>}
    <section className="profile-card"><h2>Top three open items</h2><p>{profile.open_items.public} public / {profile.open_items.internal} internal · Known active records</p>{items.length ? <ol>{items.slice(0, 3).map(row => <li key={`${row.type}:${row.id}`}><strong>{row.type}</strong> · {row.label}<small> {row.id}</small></li>)}</ol> : <p>No active items in the current projection. This is not confirmation of complete monitoring.</p>}</section>
    <a href={opportunityLink}>View opportunities for {name}</a>
  </div>
}
