import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { api } from '../../api/client'
import { Button, Disclosure, Drawer, Empty, EvidenceSource, FilterChip, FilterTrigger, Panel, SearchInput, SelectInput, StatTile, StatusBadge, Textarea, TextInput } from '../../components/UI'
import type { Account, Action, ActionHistoryEvent, ActionPriority, ActionStatus, OmniContext, Principal, Signal, Suggestion } from '../../types/api'
import './actions.css'
import { SuggestionList } from './SuggestionList'
import { CrmProposalPanel } from './CrmProposalPanel'

const priorityRank: Record<string, number> = { HIGH: 0, MEDIUM: 1, LOW: 2 }
const statusRank: Record<string, number> = { OPEN: 0, IN_PROGRESS: 1, COMPLETED: 2, CANCELED: 3 }
const nextStatuses: Record<ActionStatus, ActionStatus[]> = { OPEN: ['IN_PROGRESS', 'CANCELED'], IN_PROGRESS: ['COMPLETED', 'CANCELED'], COMPLETED: [], CANCELED: [] }
const label = (value: string) => value.replaceAll('_', ' ').toLowerCase().replace(/^./, char => char.toUpperCase())

type Props = {
  sourceAlertId?: string; onClearSource: () => void
  items: Action[]; suggestions: Suggestion[]; principal?: Principal; accounts: Account[]; signals: Signal[]; warning: string
  onItem: (item: Action) => void; onSuggestions: (items: Suggestion[]) => void; onAccount: (id: string) => void
  onActionSelect: (id?: string) => void; onOmniContext: (context: Pick<OmniContext, 'active_filters' | 'visible_record_ids'>) => void
}

export function Actions({ items, suggestions, principal, accounts, signals, warning, onItem, onSuggestions, onAccount, onActionSelect, onOmniContext, sourceAlertId, onClearSource }: Props) {
  const [tab, setTab] = useState<'ACTIONS' | 'SUGGESTIONS' | 'COMPLETED'>(() => sourceAlertId ? 'SUGGESTIONS' : 'ACTIONS')
  const [query, setQuery] = useState(''); const [status, setStatus] = useState('ACTIVE'); const [priority, setPriority] = useState('ALL'); const [sort, setSort] = useState('PRIORITY')
  const [selectedId, setSelectedId] = useState<string>(); const [selectedAction, setSelectedAction] = useState<Action>(); const [editorOpen, setEditorOpen] = useState(false); const [editing, setEditing] = useState<Action>(); const [notice, setNotice] = useState(''); const [history, setHistory] = useState<ActionHistoryEvent[]>([])
  const accountById = useMemo(() => new Map(accounts.map(account => [account.id, account])), [accounts]); const signalByAccount = useMemo(() => new Map(signals.filter(signal => signal.account_id).map(signal => [signal.account_id!, signal])), [signals])
  const customerName = useCallback((id: string) => accountById.get(id)?.name ?? accountById.get(id)?.legal_name ?? 'Unknown Customer', [accountById])
  const visible = useMemo(() => items.filter(item => {
    const search = `${customerName(item.account_id)} ${item.title} ${item.description ?? ''} ${item.owner_id ?? ''}`.toLowerCase()
    const statusMatch = status === 'ALL' || (status === 'ACTIVE' ? ['OPEN', 'IN_PROGRESS'].includes(item.status) : item.status === status)
    return search.includes(query.toLowerCase()) && statusMatch && (priority === 'ALL' || item.priority === priority) && (tab !== 'COMPLETED' || ['COMPLETED', 'CANCELED'].includes(item.status)) && (tab === 'COMPLETED' || !['COMPLETED', 'CANCELED'].includes(item.status))
  }).sort((left, right) => sort === 'DUE' ? (left.due_date ?? '9999').localeCompare(right.due_date ?? '9999') : sort === 'STATUS' ? statusRank[left.status] - statusRank[right.status] : priorityRank[left.priority] - priorityRank[right.priority]), [items, priority, query, sort, status, tab, customerName])
  const scopedSuggestions = useMemo(() => sourceAlertId ? suggestions.filter(item => item.source_alert_id === sourceAlertId) : suggestions, [sourceAlertId, suggestions])
  const selected = tab === 'SUGGESTIONS' ? undefined : selectedAction?.id === selectedId ? selectedAction : items.find(item => item.id === selectedId) ?? visible[0]
  const activeFilters = useMemo(() => ({ ...(status === 'ACTIVE' ? { action_status: 'ACTIVE' } : status === 'ALL' ? {} : { action_status: status }), ...(priority === 'ALL' ? {} : { priority }), ...(tab === 'SUGGESTIONS' ? { action_view: 'SUGGESTIONS', source_alert_id: sourceAlertId ?? '' } : {}) }), [priority, status, sourceAlertId, tab])
  useEffect(() => onActionSelect(selected?.id), [onActionSelect, selected?.id]); useEffect(() => () => onActionSelect(undefined), [onActionSelect])
  useEffect(() => {
    let current = true
    if (!selected?.id) return () => { current = false }
    void api.history(selected.id).then(response => { if (current) setHistory(response.events) }).catch(() => { if (current) setHistory([]) })
    return () => { current = false }
  }, [selected])
  useEffect(() => onOmniContext({ active_filters: activeFilters, visible_record_ids: (tab === 'SUGGESTIONS' ? scopedSuggestions : visible).map(item => item.id).slice(0, 50) }), [activeFilters, onOmniContext, visible, scopedSuggestions, tab]); useEffect(() => () => onOmniContext({}), [onOmniContext])
  const refreshSuggestions = (id: string, patch: Partial<Suggestion>) => onSuggestions(suggestions.map(item => item.id === id ? { ...item, ...patch } : item))
  const convert = async (suggestion: Suggestion) => { try { const action = await api.convertSuggestion(suggestion.id, suggestion.revision); onItem(action); refreshSuggestions(suggestion.id, { converted_action_id: action.id }); setSelectedId(action.id); setTab('ACTIONS'); setNotice('Suggestion converted to one durable Action. No external operation was executed.') } catch (error) { setNotice(error instanceof Error ? error.message : 'Suggestion could not be converted.') } }
  const applySelectedUpdate = (item: Action) => { setSelectedId(item.id); setSelectedAction(item); onItem(item) }
  const transition = async (item: Action, next: ActionStatus) => { try { const updated = await api.transition(item.id, next, item.version); applySelectedUpdate(updated); setNotice(`Action moved to ${label(next)}.`) } catch (error) { setNotice(error instanceof Error ? error.message : 'Action transition failed. Reload the Action before retrying.') } }
  const decide = async (item: Action, decision: 'APPROVED' | 'REJECTED') => { try { const updated = await api.approve(item.id, decision, item.version); applySelectedUpdate(updated); setNotice(`Approval ${decision.toLowerCase()}.`) } catch (error) { setNotice(error instanceof Error ? error.message : 'Approval decision failed. Reload the Action before retrying.') } }
  const clear = () => { setStatus('ACTIVE'); setPriority('ALL'); setQuery('') }
  const openEditor = (action?: Action) => { setEditing(action); setEditorOpen(true) }
  const activeSuggestions = suggestions.filter(item => !item.dismissed)
  return <div className="surface actions-surface">
    <header className="page-title actions-header"><div><span className="eyebrow">Seller workbench</span><h1>Actions</h1><p>Suggestions recommend work. Actions are durable, owned work with an explicit lifecycle.</p></div><Button variant="primary" size="touch" onClick={() => openEditor()}>Create Action</Button></header>
    <p className="truth-note">{principal?.display_name ?? 'Authorized principal'} · {principal?.role ?? 'Loading role'} · {warning}</p>{notice && <p className="notice" role="status">{notice}</p>}
    <nav className="actions-tabs" aria-label="Action views">{([['ACTIONS', 'My Actions'], ['SUGGESTIONS', 'Suggested'], ['COMPLETED', 'Completed']] as const).map(([value, text]) => <button key={value} aria-current={tab === value ? 'page' : undefined} className={tab === value ? 'active' : ''} onClick={() => setTab(value)}>{text}</button>)}</nav>
    <div className="actions-summary-grid" aria-label="Actions summary"><StatTile label="Open" value={items.filter(item => item.status === 'OPEN').length} /><StatTile label="In progress" value={items.filter(item => item.status === 'IN_PROGRESS').length} tone="warning" /><StatTile label="Overdue" value={items.filter(item => item.due_date && item.due_date < '2026-08-31' && !['COMPLETED', 'CANCELED'].includes(item.status)).length} tone="danger" /><StatTile label="Suggested" value={activeSuggestions.filter(item => !item.converted_action_id).length} tone="info" /></div>
    {tab === 'SUGGESTIONS' ? <>{sourceAlertId && <section className="notice" aria-label="Selected Today priority"><p>{scopedSuggestions.length ? 'Showing the recommendation linked to your Today priority. Review its evidence before creating work.' : 'The selected recommendation is no longer available in your current scope. Refresh suggestions; no substitute action was selected.'}</p><Button onClick={onClearSource}>Show all suggestions</Button>{scopedSuggestions.map(item => item.converted_action_id && <Button key={item.id} onClick={() => { setSelectedId(item.converted_action_id); setTab('ACTIONS') }}>Open existing action</Button>)}</section>}<SuggestionList suggestions={scopedSuggestions} name={customerName} onConvert={convert} onFeedback={refreshSuggestions} onRefreshed={onSuggestions} /></> : <>
      <div className="action-toolbar"><SearchInput aria-label="Search actions" placeholder="Search Actions or Customers" value={query} onChange={event => setQuery(event.target.value)} /><FilterTrigger active={status !== 'ACTIVE' || priority !== 'ALL'}>Filters</FilterTrigger><SelectInput aria-label="Filter by status" value={status} onChange={event => setStatus(event.target.value)}><option value="ACTIVE">Active statuses</option><option value="ALL">All statuses</option>{Object.keys(statusRank).map(value => <option key={value}>{value}</option>)}</SelectInput><SelectInput aria-label="Filter by priority" value={priority} onChange={event => setPriority(event.target.value)}><option value="ALL">All priorities</option>{Object.keys(priorityRank).map(value => <option key={value}>{value}</option>)}</SelectInput><SelectInput aria-label="Sort actions" value={sort} onChange={event => setSort(event.target.value)}><option value="PRIORITY">Sort: Priority</option><option value="DUE">Sort: Due date</option><option value="STATUS">Sort: Status</option></SelectInput></div>
      {(status !== 'ACTIVE' || priority !== 'ALL' || query) && <div className="action-filter-chips">{status !== 'ACTIVE' && <FilterChip selected onClear={() => setStatus('ACTIVE')}>Status: {label(status)}</FilterChip>}{priority !== 'ALL' && <FilterChip selected onClear={() => setPriority('ALL')}>Priority: {label(priority)}</FilterChip>}{query && <FilterChip selected onClear={() => setQuery('')}>Search: {query}</FilterChip>}<Button variant="ghost" onClick={clear}>Clear all</Button></div>}
      <div className="action-workbench"><Panel title="My Actions" action={<span className="panel-kicker">{visible.length} visible</span>}><div className="action-list" role="list">{visible.length ? visible.map(item => <ActionRow key={item.id} action={item} customer={customerName(item.account_id)} selected={selected?.id === item.id} onSelect={() => { setSelectedId(item.id); setSelectedAction(item) }} />) : <Empty>No Actions match the current search and filters.</Empty>}</div></Panel><aside className="action-detail">{selected ? <ActionDetail action={selected} history={history} customer={customerName(selected.account_id)} signal={signalByAccount.get(selected.account_id)} principal={principal} onAccount={() => onAccount(selected.account_id)} onEdit={() => openEditor(selected)} onTransition={next => void transition(selected, next)} onDecision={decision => void decide(selected, decision)} /> : <Panel title="Action detail"><Empty>Select an Action to inspect its governed work state.</Empty></Panel>}</aside></div>
    </>}
    {tab !== 'SUGGESTIONS' && selected && <CrmProposalPanel key={selected.id} action={selected} principal={principal} />}
    <ActionEditor key={`${editorOpen}-${editing?.id ?? 'new'}`} open={editorOpen} action={editing} accounts={accounts} principal={principal} onClose={() => setEditorOpen(false)} onSaved={item => { applySelectedUpdate(item); setEditorOpen(false); setNotice(editing ? 'Action updated and recorded in history.' : 'Durable Action created.') }} />
  </div>
}

function ActionRow({ action, customer, selected, onSelect }: { action: Action; customer: string; selected: boolean; onSelect: () => void }) { return <button type="button" role="listitem" className={`action-row ${selected ? 'selected' : ''}`} aria-pressed={selected} onClick={onSelect}><span><strong>{customer}</strong><small>{action.title}</small></span><StatusBadge value={action.priority} kind="priority" /><span className="action-row-meta"><small>{action.owner_id ?? 'Unassigned'}</small><small>{action.due_date ?? 'No due date'}</small></span><StatusBadge value={action.status} kind="action" /></button> }

function ActionDetail({ action, history, customer, signal, principal, onAccount, onEdit, onTransition, onDecision }: { action: Action; history: ActionHistoryEvent[]; customer: string; signal?: Signal; principal?: Principal; onAccount: () => void; onEdit: () => void; onTransition: (status: ActionStatus) => void; onDecision: (decision: 'APPROVED' | 'REJECTED') => void }) { return <Panel title="Action detail" action={<StatusBadge value={action.status} kind="action" />}><div className="action-detail-stack"><div><span className="eyebrow">{customer}</span><h2>{action.title}</h2><p>{action.description ?? 'No additional detail supplied.'}</p></div><dl className="action-meta"><div><dt>Owner</dt><dd>{action.owner_id ?? 'Unassigned'}</dd></div><div><dt>Priority</dt><dd>{label(action.priority)}</dd></div><div><dt>Due</dt><dd>{action.due_date ?? 'No due date'}</dd></div><div><dt>Approval</dt><dd>{label(action.approval_status)}</dd></div></dl><div className="card-actions"><Button onClick={onEdit}>Edit Action</Button><Button variant="ghost" onClick={onAccount}>View Customer</Button></div><Panel title="Next work state" variant="subdued"><div className="card-actions">{nextStatuses[action.status].map(next => <Button key={next} variant={next === 'CANCELED' ? 'destructive' : 'primary'} onClick={() => onTransition(next)}>{next === 'IN_PROGRESS' ? 'Start work' : label(next)}</Button>)}{!nextStatuses[action.status].length && <span className="muted">This Action is closed. Reopening is not supported.</span>}</div></Panel>{action.approval_status === 'PENDING' && <Panel title="Approval" variant="subdued">{principal?.role === 'MANAGER' ? <div className="card-actions"><Button variant="primary" onClick={() => onDecision('APPROVED')}>Approve</Button><Button variant="destructive" onClick={() => onDecision('REJECTED')}>Reject</Button></div> : <p className="muted">Manager review is required for this external workflow. Approval does not change work status.</p>}</Panel>}<Disclosure title="Evidence and history"><p>Evidence IDs: {action.evidence_ids.length ? action.evidence_ids.join(', ') : 'Unavailable'}</p>{signal ? <EvidenceSource title={signal.title} source={signal.source_tier} date={signal.observed_at} evidenceState={signal.evidence_state} validationState={signal.source_validation_state} url={signal.source_url} /> : <p className="muted">No curated public signal is linked. Action evidence may be SAMPLE commercial context.</p>}<p className="muted">Created by {action.created_by} · Updated {new Date(action.updated_at).toLocaleDateString()}</p><ol className="action-history" aria-label="Action history">{history.map(event => <li key={event.id}><strong>{label(event.event)}</strong><span>{event.actor_id} · {new Date(event.occurred_at).toLocaleString()}</span></li>)}</ol></Disclosure></div></Panel> }

function ActionEditor({ open, action, accounts, principal, onClose, onSaved }: { open: boolean; action?: Action; accounts: Account[]; principal?: Principal; onClose: () => void; onSaved: (item: Action) => void }) {
  const [customerSelection, setCustomerId] = useState(action?.account_id)
  const customerId = customerSelection ?? accounts[0]?.id ?? ''
  const [title, setTitle] = useState(action?.title ?? '')
  const [description, setDescription] = useState(action?.description ?? '')
  const [priority, setPriority] = useState<ActionPriority>(action?.priority ?? 'MEDIUM')
  const [dueDate, setDueDate] = useState(action?.due_date ?? '')
  const [ownerId, setOwnerId] = useState(action?.owner_id ?? principal?.user_id ?? '')
  const [approvalRequired, setApprovalRequired] = useState(action?.approval_status === 'PENDING')
  const [error, setError] = useState('')
  const inFlight = useRef(false)
  const retry = useRef<{ signature: string; key: string } | undefined>(undefined)
  const submit = async (event: React.FormEvent) => {
    event.preventDefault()
    if (inFlight.current) return
    if (!customerId || !accounts.some(item => item.id === customerId)) { setError('Choose an available Customer. Your draft is retained.'); return }
    if (!title.trim()) { setError('Title is required.'); return }
    const signature = JSON.stringify([customerId, title, description, priority, dueDate, ownerId, approvalRequired])
    if (retry.current?.signature !== signature) retry.current = { signature, key: crypto.randomUUID() }
    inFlight.current = true
    try {
      const saved = action ? await api.editAction(action.id, { title, description: description || undefined, priority, due_date: dueDate || undefined, expected_version: action.version, ...(principal?.role === 'MANAGER' ? { owner_id: ownerId || undefined } : {}) })
        : await api.createAction({ account_id: customerId, title, description: description || undefined, priority, due_date: dueDate || undefined, owner_id: ownerId || undefined, approval_required: approvalRequired, idempotency_key: retry.current.key })
      onSaved(saved)
    } catch (caught) { setError(caught instanceof Error ? caught.message : 'Action could not be saved. Retry retains this request; inspect saved work if the outcome is unknown.') }
    finally { inFlight.current = false }
  }
  return <Drawer open={open} onClose={onClose} titleId="action-editor-title" className="action-editor"><form onSubmit={event => void submit(event)}><header><div><span className="eyebrow">Durable work</span><h2 id="action-editor-title">{action ? 'Edit Action' : 'Create Action'}</h2></div><Button type="button" variant="ghost" onClick={onClose}>Close</Button></header><SelectInput label="Customer" value={customerId} disabled={Boolean(action)} onChange={event => setCustomerId(event.target.value)}>{accounts.map(account => <option value={account.id} key={account.id}>{account.name ?? account.legal_name}</option>)}</SelectInput><TextInput label="Title" value={title} error={error && !title.trim() ? error : undefined} onChange={event => setTitle(event.target.value)} /><Textarea label="Details" value={description} onChange={event => setDescription(event.target.value)} /><div className="action-form-grid"><SelectInput label="Priority" value={priority} onChange={event => setPriority(event.target.value as ActionPriority)}><option>HIGH</option><option>MEDIUM</option><option>LOW</option></SelectInput><TextInput label="Due date" type="date" value={dueDate} onChange={event => setDueDate(event.target.value)} /></div>{principal?.role === 'MANAGER' && <TextInput label="Owner ID" value={ownerId} onChange={event => setOwnerId(event.target.value)} />}{!action && <label className="action-approval-choice"><input type="checkbox" checked={approvalRequired} onChange={event => setApprovalRequired(event.target.checked)} /> External workflow requires Manager approval</label>}{error && title.trim() && <p className="ui-field-message" role="alert">{error}</p>}<footer><Button type="button" onClick={onClose}>Cancel</Button><Button type="submit" variant="primary">{action ? 'Save changes' : 'Create Action'}</Button></footer></form></Drawer>
}
