export type Relationship = 'PUBLIC_MARKET' | 'CURRENT_CUSTOMER' | 'FORMER_CUSTOMER' | 'TARGET'

export interface Account { id: string; name?: string; legal_name?: string; relationship: Relationship; industries: string[]; secondary_classifications?: string[]; domain?: string; contact_role_families?: string[]; public_research_state?: string; public_identity_state?: string; public_relationship_state?: string; prospect_research_priority?: string; prospect_rationale?: string; is_rich_scenario?: boolean; truth_state?: string; attractiveness?: string; business_unit?: string; commercial_context_state?: string; location?: { city?: string; state?: string; country?: string }; provenance?: string }
export interface Alert { id: string; account_id: string; type: string; severity: string; trigger_reason: string; recommended_action: string; evidence_ids: string[]; status: string }
export interface Signal { id: string; kind: string; title: string; source_url: string; account_id?: string; program_name?: string; evidence_state: string; resolution_state?: string; data_mode?: string; observed_at?: string; source_tier?: string; source_validation_state?: string; relevance_explanation: string; evidence_ids: string[] }
export interface WorkItem { id: string; account_id: string; status: string; summary: string; owner_id?: string; priority: string; due_date?: string; notes?: string; evidence_ids: string[] }
export interface MapRecord { account_id: string; industry: string; relationship: Relationship; is_rich_scenario?: boolean; latitude: string; longitude: string; deep_account: boolean; nearest_btx_facility: { name: string }; proximity_input: string; location_truth_state: string }
export interface PublicLocation { account_id: string; location_id: string; location_name: string; location_type: string; truth_state: string; city: string; region: string; country: string; latitude: string; longitude: string; source_url?: string }
export interface Account360 { account: Account; public_identity?: unknown; public_identity_state: string; public_relationship?: { state: string; confidence: string; basis: string }; prospect_research_priority?: string; prospect_rationale?: string; reason_for_attention?: string; recommended_next_step?: string; truth_categories: { public: string; btx: string }; public_contacts: Array<{ contact_type: string; name?: string; title_or_function?: string; role_family: string; verification_state: string; source_url?: string; public_email?: string }>; public_facilities: Array<{ id: string; name: string; city: string; region: string; country: string; facility_type: string; verification_state: string; source_url?: string }>; prism_commercial_context: unknown[]; paperless_accounts: Array<{ id: string; canonical_account_id: string; name: string }>; paperless_quotes: Array<{ id: string; status: string; value_minor?: number; quoted_at: string }>; crm: { owner_id: string; deal_ids: string[]; activity_ids: string[] } | null; account_attractiveness: { score: string | null; coverage: string; status: string; simulation: boolean; exclusion_reason?: string; factors: Array<{ name: string; score?: string; contribution?: string; missing: boolean; gaps: string[] }>; missingness: string[] }; alerts: Alert[]; intelligence: Signal[]; matching: Array<{ method: string; review_state: string; evidence_ids: string[] }>; provenance: { source_record_id: string; evidence_state: string }; missingness: string[] }
export interface OmniResponse { content: string; account_id?: string; account_name?: string; citations: string[]; citation_links?: Array<{ label: string; url: string }>; provenance: string[]; missingness: string[]; recommended_action?: string }
export interface MonitorPreviewSignal { id: string; account_id: string; company: string; industry: string; event_type: string; title: string; event_date: string; source_url: string; evidence_state: string; source_validation_state: string; data_mode: 'CURATED_PUBLIC' }
export interface MonitorHealth { collection_enabled: boolean; durable_run_state: boolean; seller_message: string; sources: Array<{ source_id: string; state?: string; last_attempt_at?: string; last_success_at?: string; detail?: string }>; last_runs: Array<{ source_id: string; completed_at?: string; records_seen?: number; records_new?: number; records_changed?: number; failures?: string[] }>; events?: Array<{ id: string; source_id: string; publication_date?: string; collected_at: string; updated_at: string; resolution_state: string; seller_relevance_state?: string; data_mode: string; provenance_url?: string }>; curated_preview: MonitorPreviewSignal[] }
