export type Relationship = 'CURRENT_CUSTOMER' | 'FORMER_CUSTOMER' | 'TARGET'

export interface Account { id: string; name?: string; legal_name?: string; relationship: Relationship; industries: string[]; domain?: string; contact_role_families?: string[]; public_research_state?: string; public_identity_state?: string; public_relationship_state?: string; prospect_research_priority?: string; external_rank?: number; attractiveness?: string; business_unit?: string; commercial_context_state?: string; location?: { city?: string; state?: string; country?: string }; provenance?: string }
export interface Alert { id: string; account_id: string; type: string; severity: string; trigger_reason: string; recommended_action: string; evidence_ids: string[]; status: string }
export interface Signal { id: string; kind: string; title: string; source_url: string; account_id?: string; program_name?: string; evidence_state: string; resolution_state?: string; data_mode?: string; observed_at?: string; source_tier?: string; relevance_explanation: string; evidence_ids: string[] }
export interface WorkItem { id: string; account_id: string; status: string; summary: string; owner_id?: string; priority: string; evidence_ids: string[] }
export interface MapRecord { account_id: string; industry: string; relationship: Relationship; latitude: string; longitude: string; external_rank: number; deep_account: boolean; nearest_btx_facility: { name: string }; proximity_input: string; location_truth_state: string }
export interface PublicLocation { account_id: string; location_id: string; location_name: string; location_type: string; truth_state: string; city: string; region: string; country: string; latitude: string; longitude: string; source_url?: string }
export interface Account360 { account: Account; public_identity?: unknown; public_identity_state: string; public_relationship?: { state: string; confidence: string; basis: string }; prospect_research_priority?: string; prospect_rationale?: string; public_contacts: Array<{ contact_type: string; name?: string; title_or_function?: string; role_family: string; verification_state: string; source_url?: string; public_email?: string }>; public_facilities: Array<{ id: string; name: string; city: string; region: string; country: string; facility_type: string; verification_state: string; source_url?: string }>; prism_commercial_context: unknown[]; paperless_accounts: Array<{ id: string; canonical_account_id: string; name: string }>; paperless_quotes: Array<{ id: string; status: string; value_minor?: number; quoted_at: string }>; crm: { owner_id: string; deal_ids: string[]; activity_ids: string[] } | null; account_attractiveness: { score: string | null; coverage: string; missingness: string[] }; alerts: Alert[]; intelligence: Signal[]; matching: Array<{ method: string; review_state: string; evidence_ids: string[] }>; provenance: { source_record_id: string; evidence_state: string }; missingness: string[] }
export interface OmniResponse { content: string; citations: string[]; provenance: string[]; missingness: string[]; recommended_action?: string }
