import { useEffect, useMemo, useState } from 'react'
import { api } from '../../api/client'
import type { FederalAssessment, FederalOpportunity, FederalProcurement, FederalRoute, OmniContext, OmniFederalSelection } from '../../types/api'
import { Button, Drawer, Empty, LoadingStatus, Notice, Panel, SelectInput, StatTile, StatusBadge } from '../../components/UI'
import { GovernedExplanationDisclosure } from '../../components/GovernedExplanationDisclosure'
import { SupportingEvidence } from '../../components/SupportingEvidence'
import { presentationLabel } from '../../components/presentation'
import type { WorkspaceLocation } from '../../app/navigation'
import { ScoreSummary } from '../../components/ScoreSummary'
import type { ScoreSummaryModel } from '../../components/scoreSummaryModel'

const money = (value: string) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(Number(value))
const displayDate = (value?: string) => value ? new Date(value).toLocaleDateString() : 'Unavailable'
const routeLabel = (route?: FederalRoute | null) => route?.label ?? 'Route needs investigation'
const federalScoreSummary = (item: FederalOpportunity): ScoreSummaryModel => ({
  family: 'Federal Opportunity Relevance', decision: 'Prioritize requirements with a supported commercial route', subject: item.title,
  value: item.relevance.score, interpretation: item.relevance.calibration_label,
  version: item.assessment?.policy_version, asOf: item.posted_date,
  positiveFactors: item.relevance.factors.filter(factor => factor.points > 0).map(factor => ({ label: presentationLabel(factor.name), detail: presentationLabel(factor.state), value: `${factor.points}/${factor.weight}` })),
  limitingFactors: item.relevance.factors.filter(factor => factor.points <= 0).map(factor => ({ label: presentationLabel(factor.name), detail: presentationLabel(factor.state), value: `${factor.points}/${factor.weight}` })),
  missingInputs: [...item.missingness, ...(item.assessment?.technical.remaining_unknowns ?? [])],
  coverage: { present: item.relevance.factors.filter(factor => !['MISSING', 'UNAVAILABLE', 'UNKNOWN'].includes(factor.state.toUpperCase())).length, applicable: item.relevance.factors.length },
  evidenceIds: item.assessment?.evidence_references,
})
type SortKey = 'title' | 'stage' | 'agency' | 'deadline' | 'relevance' | 'route'

type FederalHandlers = {
  location: WorkspaceLocation
  onLocationChange: (next: WorkspaceLocation, mode?: 'push' | 'replace') => void
  onAccount: (id: string, selection: OmniFederalSelection, assessment: FederalAssessment) => void
  onPartnership: (id: string, selection: OmniFederalSelection, assessment: FederalAssessment) => void
  onRelationship: (id: string, selection: OmniFederalSelection, assessment: FederalAssessment) => void
  onAskOmni: (selection: OmniFederalSelection) => void
  onCreateAction: (opportunity: FederalOpportunity, route: FederalRoute) => void
  onOmniContext: (context: Pick<OmniContext, 'selected_federal_opportunity' | 'visible_record_ids'>) => void
}

const federalSelection = (opportunity: FederalOpportunity, route: FederalRoute): OmniFederalSelection | undefined => opportunity.assessment ? ({ opportunity_id: opportunity.opportunity_id, assessment_id: opportunity.assessment.assessment_id, assessment_version: opportunity.assessment.assessment_version, route_type: route.route_type, account_id: route.account_id, partnership_id: route.route_type === 'STRATEGIC_PARTNER' ? route.account_id : undefined }) : undefined

export function FederalProcurementView({ location, onLocationChange, onAccount, onPartnership, onRelationship, onAskOmni, onCreateAction, onOmniContext }: FederalHandlers) {
  const [tab, setTab] = useState<'active' | 'awarded'>('active')
  const [data, setData] = useState<FederalProcurement>()
  const [filter, setFilter] = useState(() => String(location.filters?.notice_type ?? '')); const [fiscalYear, setFiscalYear] = useState(() => String(location.filters?.fiscal_year ?? ''))
  const [selectedOverride, setSelectedOverride] = useState<FederalOpportunity>()
  const setSelected = setSelectedOverride
  const [state, setState] = useState<'loading' | 'loaded' | 'error'>('loading'); const [retry, setRetry] = useState(0)
  useEffect(() => {
    const controller = new AbortController(); const params = new URLSearchParams(); if (filter) params.set('notice_type', filter); if (fiscalYear) params.set('fiscal_year', fiscalYear)
    void api.federalProcurement(params.size ? `?${params}` : '', controller.signal).then(value => { if (!controller.signal.aborted) { setData(value); setState('loaded') } }).catch(error => { if (error?.name !== 'AbortError') setState('error') })
    return () => controller.abort()
  }, [filter, fiscalYear, retry])
  useEffect(() => { onOmniContext({ visible_record_ids: data?.active.opportunities.map(item => item.opportunity_id).slice(0, 50) ?? [] }) }, [data?.active.opportunities, onOmniContext])
  const selected = selectedOverride ?? data?.active.opportunities.find(item => item.opportunity_id === location.federal?.opportunityId && item.assessment?.assessment_id === location.federal?.assessmentId && item.assessment?.assessment_version === location.federal?.assessmentVersion)
  useEffect(() => { onLocationChange({ ...location, filters: { ...(filter ? { notice_type: filter } : {}), ...(fiscalYear ? { fiscal_year: fiscalYear } : {}) } }, 'replace') }, [filter, fiscalYear, location, onLocationChange])
  const retryRecords = () => { setState('loading'); setRetry(value => value + 1) }
  if (!data) return <div className="surface federal-procurement"><header className="page-title intelligence-title"><span className="eyebrow">Intelligence workspace</span><h1>Federal Procurement</h1><p>Federal requirements, award history, possible BTX fit, and supported commercial routes.</p></header>{state === 'loading' ? <LoadingStatus>Preparing saved federal opportunities…</LoadingStatus> : <Empty>Federal procurement data could not be loaded. No zero-value metrics are shown. <Button onClick={retryRecords}>Retry federal records</Button></Empty>}</div>
  return <div className="surface intelligence-surface federal-procurement">
    <header className="page-title intelligence-title"><span className="eyebrow">Intelligence workspace</span><h1>Federal Procurement</h1><p>Understand the requirement, compare supported routes and decide what to validate next.</p></header>
    <div className="federal-tabs" role="tablist" aria-label="Federal Procurement views"><Button role="tab" aria-selected={tab === 'active'} onClick={() => setTab('active')}>Opportunity pipeline</Button><Button role="tab" aria-selected={tab === 'awarded'} onClick={() => setTab('awarded')}>Awarded dollars</Button></div>
    {state === 'loading' && <LoadingStatus>Refreshing federal opportunities… Existing records retain their prior source dates.</LoadingStatus>}
    {state === 'error' && <Notice tone="warning">Federal procurement could not refresh. Previously loaded records remain visible with their saved source dates. <Button onClick={retryRecords}>Retry federal records</Button></Notice>}
    {tab === 'active' ? <Active data={data} filter={filter} setFilter={value => { setState('loading'); setFilter(value) }} onSelect={item => { setSelectedOverride(item); const route = item.assessment?.recommended_route; const selection = route ? federalSelection(item, route) : undefined; onOmniContext({ selected_federal_opportunity: selection }); onLocationChange({ ...location, recordId: item.opportunity_id, federal: selection ? { opportunityId: selection.opportunity_id, assessmentId: selection.assessment_id, assessmentVersion: selection.assessment_version, routeType: selection.route_type, accountId: selection.account_id ?? undefined, partnershipId: selection.partnership_id ?? undefined } : undefined, anchor: item.opportunity_id }, 'push') }} /> : <Awarded data={data} fiscalYear={fiscalYear} setFiscalYear={value => { setState('loading'); setFiscalYear(value) }} />}
    <OpportunityDrawer key={selected?.assessment?.assessment_id ?? 'none'} selected={selected} initialRouteType={location.federal?.routeType} close={() => { setSelected(undefined); onOmniContext({ selected_federal_opportunity: undefined }); onLocationChange({ ...location, federal: undefined, recordId: undefined, anchor: undefined }, 'push') }} onAccount={onAccount} onPartnership={onPartnership} onRelationship={onRelationship} onAskOmni={(selection) => { onOmniContext({ selected_federal_opportunity: selection }); onAskOmni(selection) }} onCreateAction={onCreateAction} onSelectContext={(selection) => { onOmniContext({ selected_federal_opportunity: selection }); onLocationChange({ ...location, federal: { opportunityId: selection.opportunity_id, assessmentId: selection.assessment_id, assessmentVersion: selection.assessment_version, routeType: selection.route_type, accountId: selection.account_id ?? undefined, partnershipId: selection.partnership_id ?? undefined } }, 'replace') }} />
  </div>
}

function Coverage({ data }: { data: FederalProcurement }) {
  const coverage = data.sam.coverage ?? []; const complete = coverage.filter(item => !item.pending_continuation).length
  return <Notice tone={data.sam.coverage_complete ? 'info' : 'warning'} title={`Collection coverage: ${data.sam.coverage_complete ? 'complete for saved windows' : 'continuing'}`}>
    {coverage.length ? `${complete} of ${coverage.length} configured searches completed their current window. ` : 'No durable query coverage has been recorded yet. '}{data.sam.coverage_note}
    {coverage.length > 0 && <SupportingEvidence count={coverage.length} investigationKey="federal:coverage"><div className="federal-coverage-list">{coverage.map(item => <p key={item.query_key}><strong>NAICS {item.query_value}</strong> · {item.coverage_state.replaceAll('_', ' ').toLowerCase()} · through {displayDate(item.window_end)}{item.total_records != null ? ` · ${item.offset} of ${item.total_records} records visited` : ''}{item.last_error ? ` · ${item.last_error}` : ''}</p>)}</div></SupportingEvidence>}
  </Notice>
}

function Active({ data, filter, setFilter, onSelect }: { data: FederalProcurement; filter: string; setFilter: (value: string) => void; onSelect: (value: FederalOpportunity) => void }) {
  const [sort, setSort] = useState<SortKey>('relevance'); const [ascending, setAscending] = useState(false)
  const opportunities = useMemo(() => [...data.active.opportunities].sort((a, b) => {
    const av = sort === 'title' ? a.title : sort === 'stage' ? a.stage.label : sort === 'agency' ? a.agency ?? '' : sort === 'deadline' ? a.response_deadline ?? '9999' : sort === 'route' ? routeLabel(a.assessment?.recommended_route) : a.relevance.score
    const bv = sort === 'title' ? b.title : sort === 'stage' ? b.stage.label : sort === 'agency' ? b.agency ?? '' : sort === 'deadline' ? b.response_deadline ?? '9999' : sort === 'route' ? routeLabel(b.assessment?.recommended_route) : b.relevance.score
    const compared = typeof av === 'number' && typeof bv === 'number' ? av - bv : String(av).localeCompare(String(bv)); return (ascending ? compared : -compared) || a.opportunity_id.localeCompare(b.opportunity_id)
  }), [ascending, data.active.opportunities, sort])
  const changeSort = (key: SortKey) => { if (sort === key) setAscending(value => !value); else { setSort(key); setAscending(key !== 'relevance') } }
  const ariaSort = (key: SortKey): 'ascending' | 'descending' | 'none' => sort === key ? ascending ? 'ascending' : 'descending' : 'none'
  const k = data.active.kpis
  return <><Notice tone={data.sam.state === 'CONNECTED' || data.sam.state === 'SAMPLE' ? 'info' : 'warning'} title="SAM.gov collection">{presentationLabel(data.sam.state, 'provider')}. {data.sam.targeting === 'VERIFIED' ? 'BTX-approved NAICS targeting is active.' : 'NAICS targeting remains pending verification.'}</Notice><Coverage data={data} /><section className="federal-kpis">{[['Saved active records', k.open_opportunities], ['Posted last 7 days', k.posted_last_7_days], ['Closing within 14 days', k.closing_within_14_days], ['Sources Sought', k.sources_sought]].map(([label,value]) => <StatTile key={String(label)} label={String(label)} value={Number(value)} detail={label === 'Saved active records' ? 'Not a total-market estimate' : undefined} />)}</section>
    <SelectInput aria-label="Filter federal opportunities by notice type" value={filter} onChange={event => setFilter(event.target.value)}><option value="">All procurement stages</option>{data.active.pipeline.filter(item => item.count).map(item => <option key={item.type}>{item.type}</option>)}</SelectInput>
    <Panel title="Opportunity pipeline"><div className="federal-table-scroll" tabIndex={0} aria-label="Scrollable federal opportunity results"><table className="federal-results-table"><thead><tr>{([['title','Requirement'],['stage','Stage'],['agency','Agency'],['deadline','Response date'],['relevance','Relevance'],['route','Best supported route']] as Array<[SortKey,string]>).map(([key,label]) => <th key={key} scope="col" aria-sort={ariaSort(key)}><button type="button" onClick={() => changeSort(key)}>{label}<span aria-hidden="true">{sort === key ? ascending ? '↑' : '↓' : '↕'}</span></button></th>)}</tr></thead><tbody>{opportunities.map(item => <tr key={item.canonical_source_id}><th scope="row"><button className="federal-result-link" onClick={() => onSelect(item)}>{item.title}</button><small>{item.solicitation_number ?? item.opportunity_id}</small></th><td><StatusBadge value={item.stage.label} /><small>{item.stage.code === 'SOURCES_SOUGHT' ? 'Not an open bid' : item.stage.explanation}</small></td><td>{item.agency ?? 'Unavailable'}</td><td>{displayDate(item.response_deadline)}</td><td><ScoreSummary compact model={federalScoreSummary(item)} /></td><td>{routeLabel(item.assessment?.recommended_route)}</td></tr>)}</tbody></table>{!opportunities.length && <Empty>No active SAM opportunities are currently collected. This is not a zero market estimate.</Empty>}</div></Panel></>
}

function OpportunityDrawer({ selected, initialRouteType, close, onAccount, onPartnership, onRelationship, onAskOmni, onCreateAction, onSelectContext }: { selected?: FederalOpportunity; initialRouteType?: FederalRoute['route_type']; close: () => void; onAccount: FederalHandlers['onAccount']; onPartnership: FederalHandlers['onPartnership']; onRelationship: FederalHandlers['onRelationship']; onAskOmni: FederalHandlers['onAskOmni']; onCreateAction: FederalHandlers['onCreateAction']; onSelectContext: (selection: OmniFederalSelection) => void }) {
  const assessment = selected?.assessment
  const [routeType, setRouteType] = useState<FederalRoute['route_type'] | undefined>(initialRouteType ?? assessment?.recommended_route?.route_type)
  const route = assessment?.routes.find(item => item.route_type === routeType) ?? assessment?.recommended_route
  const selection = selected && route ? federalSelection(selected, route) : undefined
  return <Drawer open={Boolean(selected)} onClose={close} titleId="federal-detail"><div className="drawer-head"><h2 id="federal-detail">{selected?.title}</h2><Button onClick={close}>Close</Button></div>{selected && <div className="detail-stack"><div className="status-row"><StatusBadge value={selected.stage.label} /></div><p>{selected.stage.explanation}</p><ScoreSummary model={federalScoreSummary(selected)} />{assessment?.recommended_route && <Notice title={assessment.recommended_route.label}>{assessment.recommended_route.why}<br /><strong>Next:</strong> {assessment.recommended_route.governed_action}</Notice>}
    <div className="meta-grid"><span>Agency<strong>{selected.agency ?? 'Unavailable'}</strong></span><span>Response date<strong>{displayDate(selected.response_deadline)}</strong></span><span>NAICS<strong>{selected.naics ?? 'Unavailable'}</strong></span><span>PSC<strong>{selected.psc ?? 'Unavailable'}</strong></span><span>NSN<strong>{assessment?.technical.nsn ?? 'Unavailable'}</strong></span><span>Part number<strong>{assessment?.technical.part_number ?? 'Unavailable'}</strong></span></div>
    {assessment && <><Panel title="Commercial routes">{assessment.routes.map(item => <article className="federal-route" key={`${item.route_type}-${item.account_id ?? 'btx'}`}><div><strong>{item.label}</strong><StatusBadge value={`${item.score}/100`} /></div><p>{item.why}</p><small>{item.unknowns.join(' · ')}</small><Button variant={route?.route_type === item.route_type ? 'primary' : 'ghost'} onClick={() => { setRouteType(item.route_type); const next = federalSelection(selected, item); if (next) onSelectContext(next) }}>{route?.route_type === item.route_type ? 'Selected route' : 'Compare this route'}</Button></article>)}</Panel>{route && selection && <section className="federal-route-actions" aria-label="Selected route actions"><h3>Work with this route</h3>{route.account_id && route.route_type !== 'STRATEGIC_PARTNER' && <Button onClick={() => onAccount(route.account_id!, selection, assessment)}>Open organization profile</Button>}{route.account_id && route.route_type === 'STRATEGIC_PARTNER' && <Button onClick={() => onPartnership(route.account_id!, selection, assessment)}>Open Strategic Partnership profile</Button>}{route.account_id && <Button onClick={() => onRelationship(route.account_id!, selection, assessment)}>Explore relationship route</Button>}<Button onClick={() => onAskOmni(selection)}>Ask Omni about this opportunity</Button>{route.account_id && <Button variant="primary" onClick={() => onCreateAction(selected, route)}>Create or review Action proposal</Button>}</section>}<Panel title="Program durability"><strong>{assessment.durability.label}</strong><p>{assessment.durability.explanation}</p></Panel></>}
    <GovernedExplanationDisclosure title="Why this opportunity is relevant" explanation={selected.governed_explanation} />
    <SupportingEvidence count={assessment?.supporting_evidence_count ?? 1} investigationKey={`federal:${selected.opportunity_id}:${assessment?.assessment_version ?? 0}`}><section><h3>Official source facts</h3><p>{selected.description || 'The saved source did not include a synopsis.'}</p><a href={selected.official_source_url} target="_blank" rel="noreferrer">Open official SAM.gov record →</a></section>{assessment && <><section><h3>Technical and qualification gaps</h3><ul>{assessment.technical.remaining_unknowns.map(item => <li key={item}>{item}</li>)}</ul></section><section><h3>Route evidence and unknowns</h3>{assessment.routes.map(route => <div key={`${route.route_type}-evidence`}><strong>{route.label}</strong><p>{route.evidence_state.replaceAll('_',' ').toLowerCase()}: {route.why}</p></div>)}</section><section><h3>Score details</h3>{selected.relevance.factors.map(factor => <div className="line" key={factor.name}><span>{factor.name}: {factor.state}</span><strong>{factor.points}/{factor.weight}</strong></div>)}</section></>}</SupportingEvidence></div>}</Drawer>
}

function Awarded({ data, fiscalYear, setFiscalYear }: { data: FederalProcurement; fiscalYear: string; setFiscalYear: (value: string) => void }) { const total = data.awarded.quarterly.reduce((sum, item) => sum + Number(item.total_award_amount), 0); return <><Notice tone="warning" title="USAspending collection">{data.usaspending.scope === 'PROVISIONAL_UNSCOPED' ? 'Procurement scope pending BTX NAICS confirmation.' : data.usaspending.scope === 'SAMPLE_FIXTURE' ? 'Stored federal reference records are shown with their saved source dates.' : 'Verified procurement scope.'}</Notice><SelectInput aria-label="Select fiscal year" value={fiscalYear} onChange={event => setFiscalYear(event.target.value)}><option value="">Latest fiscal year</option>{data.awarded.available_fiscal_years?.map(year => <option key={year} value={year}>FY{year}</option>)}</SelectInput><section className="federal-kpis"><StatTile label="Relevant awarded dollars" value={money(String(total))} detail="Scope-qualified historical results" /><StatTile label="Award records" value={data.awarded.awards.length} /><StatTile label="Quarterly periods" value={data.awarded.quarterly.length} /></section><Panel title="Quarterly awarded dollars">{data.awarded.quarterly.length ? data.awarded.quarterly.map(item => <div className="line" key={`${item.fiscal_year}-${item.quarter}-${item.sector}`}><span>FY{item.fiscal_year} Q{item.quarter} · {item.sector}</span><strong>{money(item.total_award_amount)}</strong></div>) : <Empty>No USAspending award history has been collected.</Empty>}</Panel><Panel title="Top prime recipients">{data.awarded.top_recipients.length ? data.awarded.top_recipients.map(item => <div className="line" key={item.recipient}><span>{item.recipient}</span><strong>{money(item.total_award_amount)}</strong></div>) : <Empty>No recipients available.</Empty>}</Panel><Notice title="Supply-chain lag">{data.awarded.lag.detail}</Notice></> }
