import { useEffect, useState } from 'react'
import { api } from '../../api/client'
import type { FederalOpportunity, FederalProcurement } from '../../types/api'
import { Button, Drawer, Empty, Notice, Panel, SelectInput, StatTile, StatusBadge } from '../../components/UI'

const money = (value: string) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(Number(value))

export function FederalProcurementView() {
  const [tab, setTab] = useState<'active' | 'awarded'>('active'); const [data, setData] = useState<FederalProcurement>(); const [filter, setFilter] = useState(''); const [fiscalYear, setFiscalYear] = useState(''); const [selected, setSelected] = useState<FederalOpportunity>()
  useEffect(() => { const p = new URLSearchParams(); if (filter) p.set('notice_type', filter); if (fiscalYear) p.set('fiscal_year', fiscalYear); void api.federalProcurement(p.size ? `?${p}` : '').then(setData).catch(() => setData(undefined)) }, [filter, fiscalYear])
  if (!data) return <div className="surface"><h1>Federal Procurement</h1><Empty>Federal procurement data is unavailable. No zero-value metrics are shown.</Empty></div>
  return <div className="surface intelligence-surface federal-procurement">
    <header className="page-title intelligence-title"><span className="eyebrow">Intelligence workspace</span><h1>Federal Procurement</h1><p>SAM.gov forward pipeline with USAspending historical context.</p></header>
    <div className="federal-tabs" role="tablist" aria-label="Federal Procurement views"><Button role="tab" aria-selected={tab === 'active'} onClick={() => setTab('active')}>Active Opportunities</Button><Button role="tab" aria-selected={tab === 'awarded'} onClick={() => setTab('awarded')}>Awarded Dollars</Button></div>
    {tab === 'active' ? <Active data={data} filter={filter} setFilter={setFilter} onSelect={setSelected} /> : <Awarded data={data} fiscalYear={fiscalYear} setFiscalYear={setFiscalYear} />}
    <Drawer open={Boolean(selected)} onClose={() => setSelected(undefined)} titleId="federal-detail"><div className="drawer-head"><h2 id="federal-detail">{selected?.title}</h2><Button onClick={() => setSelected(undefined)}>Close</Button></div>{selected && <div className="detail-stack"><StatusBadge value={`Relevance ${selected.relevance.score}/100`} /><p>{selected.relevance.calibration_label}</p><div className="meta-grid"><span>Agency<strong>{selected.agency ?? 'Unavailable'}</strong></span><span>Deadline<strong>{selected.response_deadline ?? 'Unavailable'}</strong></span><span>Notice type<strong>{selected.notice_category ?? 'Unavailable'}</strong></span><span>NAICS<strong>{selected.naics ?? 'Unavailable'}</strong></span><span>Set-aside<strong>{selected.set_aside ?? 'Unavailable'}</strong></span></div><Panel title="Why it matters to BTX">{selected.relevance.factors.map(f => <div className="line" key={f.name}><span>{f.name}: {f.state}</span><strong>{f.points}/{f.weight}</strong></div>)}</Panel><Panel title="Official evidence"><a href={selected.official_source_url} target="_blank" rel="noreferrer">Open official SAM.gov evidence →</a></Panel></div>}</Drawer>
  </div>
}
function Active({ data, filter, setFilter, onSelect }: { data: FederalProcurement; filter: string; setFilter: (value: string) => void; onSelect: (value: FederalOpportunity) => void }) { const k = data.active.kpis; const history = (item: { available?: boolean; delta?: number | null }) => !item.available ? 'History unavailable' : item.delta === 0 ? 'No change' : `${item.delta! > 0 ? '+' : ''}${item.delta} this week`; return <><Notice tone={data.sam.state === 'CONNECTED' ? 'info' : 'warning'} title={`SAM.gov: ${data.sam.state}`}>{data.sam.targeting === 'PENDING_CONFIRMATION' ? 'BTX NAICS targeting pending confirmation; no NAICS scope is claimed.' : 'Official source evidence retained.'}</Notice><section className="federal-kpis">{[['Open opportunities', k.open_opportunities], ['Posted last 7 days', k.posted_last_7_days], ['Closing within 14 days', k.closing_within_14_days], ['Sources Sought', k.sources_sought]].map(([label,value]) => <StatTile key={String(label)} label={String(label)} value={Number(value)} detail="History unavailable" />)}</section><SelectInput aria-label="Filter federal opportunities by notice type" value={filter} onChange={e => setFilter(e.target.value)}><option value="">All notice types</option>{data.active.pipeline.filter(x => x.count).map(x => <option key={x.type}>{x.type}</option>)}</SelectInput><Panel title="Pipeline by notice type">{data.active.pipeline.map(x => <div className="line" key={x.type}><span>{x.type} · {x.count}</span><strong>{history(x)}</strong></div>)}</Panel><Panel title="Ranked opportunities"><div className="card-list">{data.active.opportunities.length ? data.active.opportunities.map(item => <article className="card" key={item.canonical_source_id}><div className="panel-head"><span className="rank">Federal Opportunity Relevance {item.relevance.score}/100</span><StatusBadge value={item.notice_category ?? 'UNCLASSIFIED'} /></div><h3>{item.title}</h3><p>{item.agency ?? 'Agency unavailable'} · {item.response_deadline ? `Closes ${new Date(item.response_deadline).toLocaleDateString()}` : 'Deadline unavailable'} · NAICS {item.naics ?? 'unavailable'}</p><div className="card-actions"><Button onClick={() => onSelect(item)}>View relevance & evidence</Button><a href={item.official_source_url} target="_blank" rel="noreferrer">SAM.gov →</a></div></article>) : <Empty>No active SAM opportunities are currently collected. This is not a zero market estimate.</Empty>}</div></Panel></> }
function Awarded({ data, fiscalYear, setFiscalYear }: { data: FederalProcurement; fiscalYear: string; setFiscalYear: (value: string) => void }) { const total = data.awarded.quarterly.reduce((sum, x) => sum + Number(x.total_award_amount), 0); return <><Notice tone="warning" title={`USAspending: ${data.usaspending.state}`}>{data.usaspending.scope === 'PROVISIONAL_UNSCOPED' ? 'Procurement scope pending BTX NAICS confirmation.' : data.usaspending.scope === 'SAMPLE_FIXTURE' ? 'SAMPLE federal fixtures for deterministic validation.' : 'Verified procurement scope.'}</Notice><SelectInput aria-label="Select fiscal year" value={fiscalYear} onChange={e => setFiscalYear(e.target.value)}><option value="">Latest fiscal year</option>{data.awarded.available_fiscal_years?.map(year => <option key={year} value={year}>FY{year}</option>)}</SelectInput><section className="federal-kpis"><StatTile label="Relevant awarded dollars" value={money(String(total))} detail="Scope-qualified historical results" /><StatTile label="Award records" value={data.awarded.awards.length} /><StatTile label="Quarterly periods" value={data.awarded.quarterly.length} /></section><Panel title="Quarterly awarded dollars">{data.awarded.quarterly.length ? data.awarded.quarterly.map(x => <div className="line" key={`${x.fiscal_year}-${x.quarter}-${x.sector}`}><span>FY{x.fiscal_year} Q{x.quarter} · {x.sector}</span><strong>{money(x.total_award_amount)}</strong></div>) : <Empty>No USAspending award history has been collected.</Empty>}</Panel><Panel title="Sector totals">{data.awarded.sector_totals?.map(x => <div className="line" key={x.sector}><span>{x.sector} · {x.share ?? 'unavailable'}%</span><strong>{money(x.amount)}</strong></div>)}</Panel><Panel title="Top prime recipients">{data.awarded.top_recipients.length ? data.awarded.top_recipients.map(x => <div className="line" key={x.recipient}><span>{x.recipient}</span><strong>{money(x.total_award_amount)}</strong></div>) : <Empty>No recipients available.</Empty>}</Panel><Notice title="Supply-chain lag">{data.awarded.lag.detail}</Notice></> }
