import { useEffect, useMemo, useState } from 'react'
import { api } from '../../api/client'
import type { FederalOpportunity, FederalProcurement, FederalRoute } from '../../types/api'
import { Button, Drawer, Empty, Notice, Panel, SelectInput, StatTile, StatusBadge } from '../../components/UI'
import { GovernedExplanationDisclosure } from '../../components/GovernedExplanationDisclosure'
import { SupportingEvidence } from '../../components/SupportingEvidence'

const money = (value: string) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(Number(value))
const displayDate = (value?: string) => value ? new Date(value).toLocaleDateString() : 'Unavailable'
const routeLabel = (route?: FederalRoute | null) => route?.label ?? 'Route needs investigation'
type SortKey = 'title' | 'stage' | 'agency' | 'deadline' | 'relevance' | 'route'

export function FederalProcurementView() {
  const [tab, setTab] = useState<'active' | 'awarded'>('active')
  const [data, setData] = useState<FederalProcurement>()
  const [filter, setFilter] = useState(''); const [fiscalYear, setFiscalYear] = useState('')
  const [selected, setSelected] = useState<FederalOpportunity>()
  const [state, setState] = useState<'loading' | 'loaded' | 'error'>('loading'); const [retry, setRetry] = useState(0)
  useEffect(() => {
    const controller = new AbortController(); const params = new URLSearchParams(); if (filter) params.set('notice_type', filter); if (fiscalYear) params.set('fiscal_year', fiscalYear)
    void api.federalProcurement(params.size ? `?${params}` : '', controller.signal).then(value => { if (!controller.signal.aborted) { setData(value); setState('loaded') } }).catch(error => { if (error?.name !== 'AbortError') setState('error') })
    return () => controller.abort()
  }, [filter, fiscalYear, retry])
  const retryRecords = () => { setState('loading'); setRetry(value => value + 1) }
  if (!data) return <div className="surface federal-procurement"><header className="page-title intelligence-title"><span className="eyebrow">Intelligence workspace</span><h1>Federal Procurement</h1><p>Federal requirements, award history and governed commercial routes.</p></header>{state === 'loading' ? <p role="status">Loading saved federal procurement records…</p> : <Empty>Federal procurement data could not be loaded. No zero-value metrics are shown. <Button onClick={retryRecords}>Retry federal records</Button></Empty>}</div>
  return <div className="surface intelligence-surface federal-procurement">
    <header className="page-title intelligence-title"><span className="eyebrow">Intelligence workspace</span><h1>Federal Procurement</h1><p>Understand the requirement, compare supported routes and decide what to validate next.</p></header>
    <div className="federal-tabs" role="tablist" aria-label="Federal Procurement views"><Button role="tab" aria-selected={tab === 'active'} onClick={() => setTab('active')}>Opportunity pipeline</Button><Button role="tab" aria-selected={tab === 'awarded'} onClick={() => setTab('awarded')}>Awarded dollars</Button></div>
    {state === 'loading' && <p role="status">Refreshing federal procurement records… Existing records retain their prior source dates.</p>}
    {state === 'error' && <Notice tone="warning">Federal procurement could not refresh. Previously loaded records remain visible with their saved source dates. <Button onClick={retryRecords}>Retry federal records</Button></Notice>}
    {tab === 'active' ? <Active data={data} filter={filter} setFilter={value => { setState('loading'); setFilter(value) }} onSelect={setSelected} /> : <Awarded data={data} fiscalYear={fiscalYear} setFiscalYear={value => { setState('loading'); setFiscalYear(value) }} />}
    <OpportunityDrawer selected={selected} close={() => setSelected(undefined)} />
  </div>
}

function Coverage({ data }: { data: FederalProcurement }) {
  const coverage = data.sam.coverage ?? []; const complete = coverage.filter(item => !item.pending_continuation).length
  return <Notice tone={data.sam.coverage_complete ? 'info' : 'warning'} title={`Collection coverage: ${data.sam.coverage_complete ? 'complete for saved windows' : 'continuing'}`}>
    {coverage.length ? `${complete} of ${coverage.length} governed searches completed their current window. ` : 'No durable query coverage has been recorded yet. '}{data.sam.coverage_note}
    {coverage.length > 0 && <SupportingEvidence count={coverage.length} investigationKey="federal:coverage"><div className="federal-coverage-list">{coverage.map(item => <p key={item.query_key}><strong>NAICS {item.query_value}</strong> · {item.coverage_state.replaceAll('_', ' ').toLowerCase()} · through {displayDate(item.window_end)}{item.total_records != null ? ` · ${item.offset} of ${item.total_records} records visited` : ''}{item.last_error ? ` · ${item.last_error}` : ''}</p>)}</div></SupportingEvidence>}
  </Notice>
}

function Active({ data, filter, setFilter, onSelect }: { data: FederalProcurement; filter: string; setFilter: (value: string) => void; onSelect: (value: FederalOpportunity) => void }) {
  const [sort, setSort] = useState<SortKey>('relevance'); const [ascending, setAscending] = useState(false)
  const opportunities = useMemo(() => [...data.active.opportunities].sort((a, b) => {
    const av = sort === 'title' ? a.title : sort === 'stage' ? a.stage.label : sort === 'agency' ? a.agency ?? '' : sort === 'deadline' ? a.response_deadline ?? '9999' : sort === 'route' ? routeLabel(a.assessment?.recommended_route) : a.relevance.score
    const bv = sort === 'title' ? b.title : sort === 'stage' ? b.stage.label : sort === 'agency' ? b.agency ?? '' : sort === 'deadline' ? b.response_deadline ?? '9999' : sort === 'route' ? routeLabel(b.assessment?.recommended_route) : b.relevance.score
    const compared = typeof av === 'number' && typeof bv === 'number' ? av - bv : String(av).localeCompare(String(bv)); return (ascending ? compared : -compared) || a.opportunity_id.localeCompare(b.opportunity_id)
  }), [ascending, data.active.opportunities, sort])
  const changeSort = (key: SortKey) => { if (sort === key) setAscending(value => !value); else { setSort(key); setAscending(key !== 'relevance') } }
  const ariaSort = (key: SortKey): 'ascending' | 'descending' | 'none' => sort === key ? ascending ? 'ascending' : 'descending' : 'none'
  const k = data.active.kpis
  return <><Notice tone={data.sam.state === 'CONNECTED' || data.sam.state === 'SAMPLE' ? 'info' : 'warning'} title={`SAM.gov: ${data.sam.state}`}>{data.sam.targeting === 'VERIFIED' ? 'Governed NAICS targeting is active.' : 'NAICS targeting remains pending verification.'}</Notice><Coverage data={data} /><section className="federal-kpis">{[['Saved active records', k.open_opportunities], ['Posted last 7 days', k.posted_last_7_days], ['Closing within 14 days', k.closing_within_14_days], ['Sources Sought', k.sources_sought]].map(([label,value]) => <StatTile key={String(label)} label={String(label)} value={Number(value)} detail={label === 'Saved active records' ? 'Not a total-market estimate' : undefined} />)}</section>
    <SelectInput aria-label="Filter federal opportunities by notice type" value={filter} onChange={event => setFilter(event.target.value)}><option value="">All procurement stages</option>{data.active.pipeline.filter(item => item.count).map(item => <option key={item.type}>{item.type}</option>)}</SelectInput>
    <Panel title="Opportunity pipeline"><div className="federal-table-scroll" tabIndex={0} aria-label="Scrollable federal opportunity results"><table className="federal-results-table"><thead><tr>{([['title','Requirement'],['stage','Stage'],['agency','Agency'],['deadline','Response date'],['relevance','Relevance'],['route','Best supported route']] as Array<[SortKey,string]>).map(([key,label]) => <th key={key} scope="col" aria-sort={ariaSort(key)}><button type="button" onClick={() => changeSort(key)}>{label}<span aria-hidden="true">{sort === key ? ascending ? '↑' : '↓' : '↕'}</span></button></th>)}</tr></thead><tbody>{opportunities.map(item => <tr key={item.canonical_source_id}><th scope="row"><button className="federal-result-link" onClick={() => onSelect(item)}>{item.title}</button><small>{item.solicitation_number ?? item.opportunity_id}</small></th><td><StatusBadge value={item.stage.label} /><small>{item.stage.code === 'SOURCES_SOUGHT' ? 'Not an open bid' : item.stage.explanation}</small></td><td>{item.agency ?? 'Unavailable'}</td><td>{displayDate(item.response_deadline)}</td><td>{item.relevance.score}/100</td><td>{routeLabel(item.assessment?.recommended_route)}</td></tr>)}</tbody></table>{!opportunities.length && <Empty>No active SAM opportunities are currently collected. This is not a zero market estimate.</Empty>}</div></Panel></>
}

function OpportunityDrawer({ selected, close }: { selected?: FederalOpportunity; close: () => void }) {
  const assessment = selected?.assessment
  return <Drawer open={Boolean(selected)} onClose={close} titleId="federal-detail"><div className="drawer-head"><h2 id="federal-detail">{selected?.title}</h2><Button onClick={close}>Close</Button></div>{selected && <div className="detail-stack"><div className="status-row"><StatusBadge value={selected.stage.label} /><StatusBadge value={`Relevance ${selected.relevance.score}/100`} /></div><p>{selected.stage.explanation}</p><p>{selected.relevance.calibration_label}</p>{assessment?.recommended_route && <Notice title={assessment.recommended_route.label}>{assessment.recommended_route.why}<br /><strong>Next:</strong> {assessment.recommended_route.governed_action}</Notice>}
    <div className="meta-grid"><span>Agency<strong>{selected.agency ?? 'Unavailable'}</strong></span><span>Response date<strong>{displayDate(selected.response_deadline)}</strong></span><span>NAICS<strong>{selected.naics ?? 'Unavailable'}</strong></span><span>PSC<strong>{selected.psc ?? 'Unavailable'}</strong></span><span>NSN<strong>{assessment?.technical.nsn ?? 'Unavailable'}</strong></span><span>Part number<strong>{assessment?.technical.part_number ?? 'Unavailable'}</strong></span></div>
    {assessment && <><Panel title="Commercial routes">{assessment.routes.map(route => <article className="federal-route" key={`${route.route_type}-${route.account_id ?? 'btx'}`}><div><strong>{route.label}</strong><StatusBadge value={`${route.score}/100`} /></div><p>{route.why}</p><small>{route.unknowns.join(' · ')}</small></article>)}</Panel><Panel title="Program durability"><strong>{assessment.durability.label}</strong><p>{assessment.durability.explanation}</p></Panel></>}
    <GovernedExplanationDisclosure title="Why this opportunity is relevant" explanation={selected.governed_explanation} />
    <SupportingEvidence count={assessment?.supporting_evidence_count ?? 1} investigationKey={`federal:${selected.opportunity_id}:${assessment?.assessment_version ?? 0}`}><section><h3>Official source facts</h3><p>{selected.description || 'The saved source did not include a synopsis.'}</p><a href={selected.official_source_url} target="_blank" rel="noreferrer">Open official SAM.gov record →</a></section>{assessment && <><section><h3>Technical and qualification gaps</h3><ul>{assessment.technical.remaining_unknowns.map(item => <li key={item}>{item}</li>)}</ul></section><section><h3>Route evidence and unknowns</h3>{assessment.routes.map(route => <div key={`${route.route_type}-evidence`}><strong>{route.label}</strong><p>{route.evidence_state.replaceAll('_',' ').toLowerCase()}: {route.why}</p></div>)}</section><section><h3>Score details</h3>{selected.relevance.factors.map(factor => <div className="line" key={factor.name}><span>{factor.name}: {factor.state}</span><strong>{factor.points}/{factor.weight}</strong></div>)}</section></>}</SupportingEvidence></div>}</Drawer>
}

function Awarded({ data, fiscalYear, setFiscalYear }: { data: FederalProcurement; fiscalYear: string; setFiscalYear: (value: string) => void }) { const total = data.awarded.quarterly.reduce((sum, item) => sum + Number(item.total_award_amount), 0); return <><Notice tone="warning" title={`USAspending: ${data.usaspending.state}`}>{data.usaspending.scope === 'PROVISIONAL_UNSCOPED' ? 'Procurement scope pending BTX NAICS confirmation.' : data.usaspending.scope === 'SAMPLE_FIXTURE' ? 'Stored federal reference records; collection is not live.' : 'Verified procurement scope.'}</Notice><SelectInput aria-label="Select fiscal year" value={fiscalYear} onChange={event => setFiscalYear(event.target.value)}><option value="">Latest fiscal year</option>{data.awarded.available_fiscal_years?.map(year => <option key={year} value={year}>FY{year}</option>)}</SelectInput><section className="federal-kpis"><StatTile label="Relevant awarded dollars" value={money(String(total))} detail="Scope-qualified historical results" /><StatTile label="Award records" value={data.awarded.awards.length} /><StatTile label="Quarterly periods" value={data.awarded.quarterly.length} /></section><Panel title="Quarterly awarded dollars">{data.awarded.quarterly.length ? data.awarded.quarterly.map(item => <div className="line" key={`${item.fiscal_year}-${item.quarter}-${item.sector}`}><span>FY{item.fiscal_year} Q{item.quarter} · {item.sector}</span><strong>{money(item.total_award_amount)}</strong></div>) : <Empty>No USAspending award history has been collected.</Empty>}</Panel><Panel title="Top prime recipients">{data.awarded.top_recipients.length ? data.awarded.top_recipients.map(item => <div className="line" key={item.recipient}><span>{item.recipient}</span><strong>{money(item.total_award_amount)}</strong></div>) : <Empty>No recipients available.</Empty>}</Panel><Notice title="Supply-chain lag">{data.awarded.lag.detail}</Notice></> }
