import { useEffect, useMemo, useState } from 'react'
import type { Account, Alert, CommandCenter, MonitorSignalBrief, OmniContext, Signal } from '../../types/api'
import { SignalBriefCard } from '../../components/SignalBriefCard'
import { curatedSignalBrief } from '../../components/signalBriefModel'
import { Button, Disclosure, Empty, Panel, State, StatTile } from '../../components/UI'
import './today.css'

const priorityCounts = (alerts: Alert[]) => alerts.reduce((counts, alert) => { const value = alert.severity.toUpperCase(); if (value in counts) counts[value as keyof typeof counts] += 1; return counts }, { HIGH: 0, MEDIUM: 0, LOW: 0 })
const itemsById = <T extends { id: string }>(items: T[], ids?: string[]) => ids ? ids.flatMap(id => { const item = items.find(value => value.id === id); return item ? [item] : [] }) : items

export function Today({ commandCenter, state, alerts, signals, accounts, onAccount, onAction, onIntelligence, onMonitor, onEventSelect, onOmniContext }: { commandCenter?: CommandCenter; state: 'loading' | 'loaded' | 'unavailable'; alerts: Alert[]; signals: Signal[]; accounts: Account[]; onAccount: (id: string) => void; onAction: (alert: Alert) => void; onIntelligence: () => void; onMonitor: () => void; onEventSelect: (id?: string) => void; onOmniContext: (context: Pick<OmniContext, 'selected_event_id' | 'selected_program_id' | 'active_filters' | 'visible_record_ids'>) => void }) {
  const [market, setMarket] = useState('')
  const [selectedEventId, setSelectedEventId] = useState<string>()
  const [selectedProgramId, setSelectedProgramId] = useState<string>()
  const counts = useMemo(() => priorityCounts(alerts), [alerts])
  const accountById = useMemo(() => new Map(accounts.map(account => [account.id, account])), [accounts])
  const current = useMemo(() => commandCenter?.current_signal_briefs ?? [], [commandCenter])
  const radar = useMemo(() => commandCenter?.upcoming_radar ?? [], [commandCenter])
  const selectedHub = commandCenter?.market_hubs.find(hub => hub.market === market)
  const visibleCurrent = useMemo(() => itemsById(current, selectedHub?.current_signal_ids), [current, selectedHub?.current_signal_ids])
  const visibleRadar = useMemo(() => itemsById(radar, selectedHub?.upcoming_signal_ids), [radar, selectedHub?.upcoming_signal_ids])
  const visibleAccounts = useMemo(() => market ? (commandCenter?.watched_accounts ?? []).filter(item => selectedHub?.watched_account_ids.includes(item.account_id)) : (commandCenter?.watched_accounts ?? []), [commandCenter?.watched_accounts, market, selectedHub?.watched_account_ids])
  const visiblePrograms = useMemo(() => market ? (commandCenter?.watched_programs ?? []).filter(item => selectedHub?.watched_program_ids.includes(item.program_id)) : (commandCenter?.watched_programs ?? []), [commandCenter?.watched_programs, market, selectedHub?.watched_program_ids])
  const alertById = useMemo(() => new Map(alerts.map(alert => [alert.id, alert])), [alerts])
  const priority = useMemo(() => commandCenter?.priority_briefing ?? [], [commandCenter])
  const curatedIds = useMemo(() => commandCenter?.curated_reference_signal_ids ?? [], [commandCenter])
  const curatedSignals = useMemo(() => curatedIds.flatMap(id => { const signal = signals.find(item => item.id === id && item.data_mode === 'CURATED_PUBLIC'); return signal ? [signal] : [] }), [curatedIds, signals])
  const curated = useMemo(() => curatedSignals.map(signal => curatedSignalBrief(signal, accountById.get(signal.account_id ?? ''))), [accountById, curatedSignals])
  const missingCuratedCount = curatedIds.length - curated.length
  const visibleIds = useMemo(() => [...new Set([...priority.map(item => item.id), ...visibleCurrent.map(item => item.id), ...visibleRadar.map(item => item.id), ...visibleAccounts.slice(0, 12).map(item => item.account_id), ...visiblePrograms.map(item => item.program_id), ...curated.map(item => item.id)])].slice(0, 50), [curated, priority, visibleAccounts, visibleCurrent, visiblePrograms, visibleRadar])
  useEffect(() => { onOmniContext({ selected_event_id: selectedEventId, selected_program_id: selectedProgramId, active_filters: market ? { market } : undefined, visible_record_ids: visibleIds }) }, [market, onOmniContext, selectedEventId, selectedProgramId, visibleIds])
  useEffect(() => () => { onEventSelect(undefined); onOmniContext({}) }, [onEventSelect, onOmniContext])
  const name = (id: string) => accountById.get(id)?.name ?? accountById.get(id)?.legal_name ?? 'Unresolved Customer'
  const useBrief = (brief: MonitorSignalBrief) => { const next = selectedEventId === brief.id ? undefined : brief.id; setSelectedEventId(next); setSelectedProgramId(next ? brief.canonical_program_id : undefined); onEventSelect(next) }
  const changeMarket = (nextMarket: string) => {
    const nextHub = commandCenter?.market_hubs.find(hub => hub.market === nextMarket)
    const nextVisibleEvents = new Set([...priority.map(item => item.id), ...(nextHub ? nextHub.current_signal_ids : current.map(item => item.id)), ...(nextHub ? nextHub.upcoming_signal_ids : radar.map(item => item.id)), ...curated.map(item => item.id)])
    const nextVisiblePrograms = new Set(nextHub ? nextHub.watched_program_ids : (commandCenter?.watched_programs ?? []).map(item => item.program_id))
    if (selectedEventId && !nextVisibleEvents.has(selectedEventId)) { setSelectedEventId(undefined); onEventSelect(undefined) }
    if (selectedProgramId && !nextVisiblePrograms.has(selectedProgramId)) setSelectedProgramId(undefined)
    setMarket(nextMarket)
  }
  return <div className="surface today-surface">
    <header className="page-title today-title"><span className="eyebrow">Seller Command Center</span><h1>Today</h1><p>Attention, change, timing, and governed next steps in one briefing.</p></header>
    <p className={`today-data-mode ${state === 'unavailable' ? 'unavailable' : ''}`} role={state === 'unavailable' ? 'alert' : undefined}>{state === 'unavailable' ? 'Today briefing is unavailable. This is not zero activity; retry when the governed projection is available.' : <>Commercial history and review context are <strong>SAMPLE BTX data</strong>. Public intelligence is <strong>{commandCenter?.daily_briefing.live_intelligence_available ? 'CONNECTED public evidence' : 'not currently available'}</strong>.</>}</p>
    {state === 'unavailable' ? <Panel title="Today briefing unavailable"><Empty>The Today projection could not be loaded. Customer, intelligence, and action surfaces may still be available separately.</Empty></Panel> : <>
    <section className="today-priority-summary" aria-label="Commercial Review priority distribution">
      <StatTile label="High" value={counts.HIGH} detail="SAMPLE commercial reviews" tone={counts.HIGH ? 'danger' : 'neutral'} />
      <StatTile label="Medium" value={counts.MEDIUM} detail="SAMPLE commercial reviews" tone={counts.MEDIUM ? 'warning' : 'neutral'} />
      <StatTile label="Low" value={counts.LOW} detail="SAMPLE commercial reviews" />
      <StatTile label="Current signals" value={current.length} detail="Eligible collected evidence" tone="info" />
      <StatTile label="Upcoming" value={radar.length} detail="Source-supported dates" />
    </section>
    <div className="today-command-grid">
      <Panel title="What changed / needs attention" action={<span className="panel-kicker">Backend-prioritized briefing</span>}>
        {priority.length ? <div className="today-attention-list">{priority.map(item => item.kind === 'COMMERCIAL_REVIEW' ? <article className="today-attention-item" key={item.id} data-priority-id={item.id}><div className="today-item-heading"><button className="today-customer-link" disabled={!item.account_id} onClick={() => item.account_id && onAccount(item.account_id)}>{item.account_id ? name(item.account_id) : 'Customer unavailable'}</button><State value={item.severity ?? 'REVIEW'} /></div><State value="SAMPLE BTX commercial context" /><p><strong>Why:</strong> {item.reason}</p><p><strong>Next:</strong> {item.recommended_action ?? 'Governed next step unavailable.'}</p><Disclosure title="Evidence and governed action"><p className="today-evidence-note">SAMPLE BTX commercial context · Evidence IDs: {item.evidence_ids.length ? item.evidence_ids.join(', ') : 'Unavailable'}</p><div className="card-actions">{item.account_id && <Button onClick={() => onAccount(item.account_id!)}>Review Customer</Button>}{alertById.get(item.id) && <Button variant="primary" onClick={() => onAction(alertById.get(item.id)!)}>Create action</Button>}</div></Disclosure></article> : item.signal_brief ? <div className="today-priority-signal" key={item.id} data-priority-id={item.id}><SignalBriefCard brief={item.signal_brief} accountName={name} onAccount={onAccount} onUseInOmni={useBrief} selected={selectedEventId === item.id} /></div> : <article className="today-attention-item" key={item.id} data-priority-id={item.id}><State value={item.data_mode} /><p>{item.reason}</p><p className="muted">Signal Brief details are unavailable; no substitute was selected.</p></article>)}</div> : <Empty>No governed priority briefing items are available.</Empty>}
      </Panel>
      <Panel title="Current public intelligence" action={<Button variant="ghost" onClick={onMonitor}>Source health</Button>}>{visibleCurrent.length ? <div className="seller-signal-list">{visibleCurrent.map(brief => <SignalBriefCard key={brief.id} brief={brief} accountName={name} onAccount={onAccount} onUseInOmni={useBrief} />)}</div> : <Empty>No current CONNECTED public evidence{market ? ` for ${market}` : ''}. Curated demonstration material is shown separately and is not live collection.</Empty>}</Panel>
    </div>
    <Panel title="Upcoming Radar" action={<span className="panel-kicker">Only source-supported future dates</span>}>{visibleRadar.length ? <div className="seller-signal-list radar-list">{visibleRadar.map(brief => <SignalBriefCard key={brief.id} brief={brief} accountName={name} onAccount={onAccount} onUseInOmni={useBrief} />)}</div> : <Empty>No governed upcoming dates{market ? ` for ${market}` : ''}. Unknown dates are not promoted into Radar.</Empty>}</Panel>
    <section className="today-market-section" aria-labelledby="market-hubs-title"><div><span className="eyebrow">Navigation and context</span><h2 id="market-hubs-title">Market Hubs</h2></div><nav className="today-market-hubs" aria-label="Market hubs"><Button variant={market ? 'ghost' : 'primary'} aria-pressed={!market} onClick={() => changeMarket('')}>All markets</Button>{(commandCenter?.market_hubs ?? []).map(hub => <Button key={hub.market} variant={market === hub.market ? 'primary' : 'ghost'} aria-pressed={market === hub.market} onClick={() => changeMarket(hub.market)}>{hub.market}<span>{hub.current_signal_ids.length + hub.upcoming_signal_ids.length}</span></Button>)}</nav></section>
    <div className="today-watch-grid">
      <Panel title="Recommended Customer watchlist" action={<span className="panel-kicker">System recommended · read only</span>}>{visibleAccounts.length ? <div className="today-watch-list">{visibleAccounts.slice(0, 12).map(item => <button key={item.account_id} onClick={() => onAccount(item.account_id)}><span><strong>{item.name}</strong><small>{item.markets.join(' · ')}</small></span><State value={item.relationship === 'TARGET' ? 'PROSPECT' : 'CUSTOMER'} /></button>)}</div> : <Empty>No governed watch targets{market ? ` for ${market}` : ''}. No user saves are implied.</Empty>}</Panel>
      <Panel title="Watched programs" action={<span className="panel-kicker">Governed Signal Brief associations</span>}>{visiblePrograms.length ? <div className="today-watch-list">{visiblePrograms.map(item => <button key={item.program_id} aria-pressed={selectedProgramId === item.program_id} onClick={() => setSelectedProgramId(selectedProgramId === item.program_id ? undefined : item.program_id)}><span><strong>{item.name}</strong><small>{item.reason}</small></span></button>)}</div> : <Empty>No current or upcoming Signal Brief has a canonical program association{market ? ` for ${market}` : ''}.</Empty>}</Panel>
    </div>
    <Panel title={market ? `${market} coverage and gaps` : 'Coverage and source freshness'} action={<Button variant="ghost" onClick={onMonitor}>Open Monitor</Button>}><p className="truth-note">{commandCenter?.daily_briefing.live_intelligence_available ? 'Current eligible collected evidence is available.' : 'No current eligible live intelligence is available.'} Worker readiness does not prove that a schedule is active.</p>{selectedHub && <div className="today-hub-summary"><p><strong>Source coverage:</strong> {selectedHub.source_coverage.length ? selectedHub.source_coverage.map(source => `${source.source_name} (${source.state.replaceAll('_', ' ').toLocaleLowerCase()})`).join(' · ') : 'No declared source coverage'}</p>{selectedHub.gaps.length ? <ul>{selectedHub.gaps.map(gap => <li key={gap}>{gap}</li>)}</ul> : <p>No governed coverage gap is reported for this market.</p>}</div>}{!selectedHub && (commandCenter?.source_health_warnings.length ?? 0) > 0 && <Disclosure title={`${commandCenter!.source_health_warnings.length} source coverage notices`}><ul>{commandCenter!.source_health_warnings.map(item => <li key={item.source_id}><strong>{item.source_name}</strong>: {item.message}</li>)}</ul></Disclosure>}{!selectedHub && (commandCenter?.missingness.length ?? 0) > 0 && <p className="muted">{commandCenter!.missingness.join(' ')}</p>}</Panel>
    <Panel title="Public intelligence" action={<Button variant="ghost" onClick={onIntelligence}>View Intelligence</Button>}><p className="monitor-intro">Stored public scenarios demonstrate evidence workflows. They are curated public material, not today’s live collection.</p>{curated.length ? <div className="seller-signal-list curated-reference-list">{curated.map(brief => <SignalBriefCard key={brief.id} brief={brief} accountName={name} onAccount={onAccount} onUseInOmni={useBrief} selected={selectedEventId === brief.id} />)}</div> : <Empty>No projected curated public evidence is available.</Empty>}{missingCuratedCount > 0 && <p className="muted">{missingCuratedCount} projected curated record{missingCuratedCount === 1 ? '' : 's'} could not be resolved from the current Intelligence payload; no substitute was shown.</p>}</Panel>
    </>}
  </div>
}
