import type { Alert, Signal } from '../../types/api'
import { Empty, Panel, State } from '../../components/UI'

function SignalTruth({ signal }: { signal: Signal }) { return <div className="truth-row"><State value={signal.data_mode === 'CONNECTED' ? 'LIVE_PUBLIC' : 'SAMPLE'} /><State value={signal.resolution_state ?? signal.evidence_state} /></div> }

export function Today({ alerts, signals, onAccount, onAction }: { alerts: Alert[]; signals: Signal[]; onAccount: (id: string) => void; onAction: (alert: Alert) => void }) {
  const live = signals.filter(signal => signal.data_mode === 'CONNECTED'); const priority = [...live, ...signals.filter(signal => signal.data_mode !== 'CONNECTED')]
  return <div className="surface"><div className="page-title"><span className="eyebrow">Commercial command</span><h1>Today</h1><p>What changed, why it matters, and the governed next step—separated by source truth.</p></div><div className="priority-strip"><span><strong>{alerts.length}</strong> commercial exceptions</span><span><strong>{live.length}</strong> live public observations</span><span>SAMPLE internal context remains synthetic</span></div><div className="today-grid"><Panel title="Act now" action={<span className="panel-kicker">Commercial alerts</span>}>{alerts.length ? <div className="card-list">{alerts.map(alert => <article className="card priority-card" key={alert.id}><div className="row"><div><State value={alert.severity} /> <State value={alert.type} /></div><small>Account: {alert.account_id}</small></div><h3>{alert.trigger_reason}</h3><p>{alert.recommended_action}</p><div className="card-actions"><button onClick={() => onAccount(alert.account_id)}>Review account</button><button className="primary" onClick={() => onAction(alert)}>Create action</button></div><small>Evidence: {alert.evidence_ids.join(', ')}</small></article>)}</div> : <Empty>No alertable commercial exceptions.</Empty>}</Panel><Panel title="What changed" action={<span className="panel-kicker">Intelligence</span>}>{priority.length ? <div className="card-list">{priority.map(signal => <article className="card" key={signal.id}><div className="row"><State value={signal.kind} /><SignalTruth signal={signal} /></div><h3>{signal.title}</h3><p>{signal.relevance_explanation}</p><div className="card-actions"><a href={signal.source_url} target="_blank" rel="noreferrer">Evidence source ↗</a>{signal.account_id && <button onClick={() => onAccount(signal.account_id!)}>Open account</button>}</div><small>{signal.observed_at ? `Observed ${new Date(signal.observed_at).toLocaleDateString()} · ` : ''}Evidence: {signal.evidence_ids.join(', ')}</small></article>)}</div> : <Empty>No governed intelligence is available.</Empty>}</Panel></div></div>
}
