"""Stable, source-neutral Monitor 2.0 event vocabulary."""
from enum import StrEnum


class EventType(StrEnum):
    UNCLASSIFIED_PUBLIC_UPDATE = "UNCLASSIFIED_PUBLIC_UPDATE"
    CONTRACT_AWARD = "CONTRACT_AWARD"
    SOLICITATION = "SOLICITATION"
    CONTRACT_MODIFICATION = "CONTRACT_MODIFICATION"
    FACILITY_EXPANSION = "FACILITY_EXPANSION"
    CAPACITY_EXPANSION = "CAPACITY_EXPANSION"
    NEW_FACILITY = "NEW_FACILITY"
    PROGRAM_LAUNCH = "PROGRAM_LAUNCH"
    PRODUCTION_RAMP = "PRODUCTION_RAMP"
    PRODUCT_LAUNCH = "PRODUCT_LAUNCH"
    SUPPLIER_AWARD = "SUPPLIER_AWARD"
    SUPPLY_CHAIN_CHANGE = "SUPPLY_CHAIN_CHANGE"
    CAPITAL_INVESTMENT = "CAPITAL_INVESTMENT"
    M_AND_A = "M_AND_A"
    PARTNERSHIP = "PARTNERSHIP"
    REGULATORY_APPROVAL = "REGULATORY_APPROVAL"
    REGULATORY_CHANGE = "REGULATORY_CHANGE"
    GOVERNMENT_FUNDING = "GOVERNMENT_FUNDING"
    GRANT_AWARD = "GRANT_AWARD"
    EXECUTIVE_CHANGE = "EXECUTIVE_CHANGE"
    EARNINGS_SIGNAL = "EARNINGS_SIGNAL"
    BACKLOG_CHANGE = "BACKLOG_CHANGE"
    CONTRACT_REDUCTION = "CONTRACT_REDUCTION"
    PROGRAM_CANCELLATION = "PROGRAM_CANCELLATION"
    FACILITY_CLOSURE = "FACILITY_CLOSURE"
    WORKFORCE_REDUCTION = "WORKFORCE_REDUCTION"
    FINANCIAL_DISTRESS = "FINANCIAL_DISTRESS"
    EXPORT_RESTRICTION = "EXPORT_RESTRICTION"
    PRODUCTION_DELAY = "PRODUCTION_DELAY"


class ResolutionState(StrEnum):
    RESOLVED = "RESOLVED"
    AMBIGUOUS = "AMBIGUOUS"
    UNRESOLVED = "UNRESOLVED"
    REJECTED = "REJECTED"


class SellerRelevanceState(StrEnum):
    """Whether a collected observation can be shown as seller intelligence.

    This deliberately carries more policy information than entity resolution alone.
    """

    RESOLVED_ELIGIBLE = "RESOLVED_ELIGIBLE"
    RESOLVED_NEEDS_REVIEW = "RESOLVED_NEEDS_REVIEW"
    AMBIGUOUS = "AMBIGUOUS"
    UNRESOLVED = "UNRESOLVED"
    REJECTED = "REJECTED"


class CandidateReviewState(StrEnum):
    """Governed review state for a non-canonical public identity."""

    PENDING_REVIEW = "PENDING_REVIEW"
    AMBIGUOUS = "AMBIGUOUS"
    REJECTED = "REJECTED"
    READY_FOR_PROMOTION = "READY_FOR_PROMOTION"
    PROMOTED = "PROMOTED"


class RejectionState(StrEnum):
    NOT_RELEVANT = "NOT_RELEVANT"
    NO_ENTITY_MATCH = "NO_ENTITY_MATCH"
    AMBIGUOUS_ENTITY = "AMBIGUOUS_ENTITY"
    DUPLICATE_EVENT = "DUPLICATE_EVENT"
    EXPIRED_EVENT = "EXPIRED_EVENT"
    UNSUPPORTED_CLAIM = "UNSUPPORTED_CLAIM"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    OUTSIDE_PHASE_1_SCOPE = "OUTSIDE_PHASE_1_SCOPE"


class SourceHealthState(StrEnum):
    NEVER_ATTEMPTED = "NEVER_ATTEMPTED"
    HEALTHY = "HEALTHY"
    STALE = "STALE"
    PARTIAL = "PARTIAL"
    WARNING = "WARNING"
    FAILED = "FAILED"
    DISABLED = "DISABLED"
    NOT_CONFIGURED = "NOT_CONFIGURED"
