"""Stable, source-neutral Monitor 2.0 event vocabulary."""
from enum import StrEnum


class EventType(StrEnum):
    CONTRACT_AWARD = "CONTRACT_AWARD"
    SOLICITATION = "SOLICITATION"
    CONTRACT_MODIFICATION = "CONTRACT_MODIFICATION"
    FACILITY_EXPANSION = "FACILITY_EXPANSION"
    CAPACITY_EXPANSION = "CAPACITY_EXPANSION"
    NEW_FACILITY = "NEW_FACILITY"
    PROGRAM_LAUNCH = "PROGRAM_LAUNCH"
    PRODUCTION_RAMP = "PRODUCTION_RAMP"
    PRODUCT_LAUNCH = "PRODUCT_LAUNCH"
    SUPPLIER_AWARD = "SUPPLIER_AWARD"
    SUPPLY_CHAIN_CHANGE = "SUPPLY_CHAIN_CHANGE"
    CAPITAL_INVESTMENT = "CAPITAL_INVESTMENT"
    M_AND_A = "M_AND_A"
    PARTNERSHIP = "PARTNERSHIP"
    REGULATORY_APPROVAL = "REGULATORY_APPROVAL"
    REGULATORY_CHANGE = "REGULATORY_CHANGE"
    GOVERNMENT_FUNDING = "GOVERNMENT_FUNDING"
    GRANT_AWARD = "GRANT_AWARD"
    EXECUTIVE_CHANGE = "EXECUTIVE_CHANGE"
    EARNINGS_SIGNAL = "EARNINGS_SIGNAL"
    BACKLOG_CHANGE = "BACKLOG_CHANGE"


class ResolutionState(StrEnum):
    RESOLVED = "RESOLVED"
    AMBIGUOUS = "AMBIGUOUS"
    UNRESOLVED = "UNRESOLVED"
    REJECTED = "REJECTED"


class RejectionState(StrEnum):
    NOT_RELEVANT = "NOT_RELEVANT"
    NO_ENTITY_MATCH = "NO_ENTITY_MATCH"
    AMBIGUOUS_ENTITY = "AMBIGUOUS_ENTITY"
    DUPLICATE_EVENT = "DUPLICATE_EVENT"
    EXPIRED_EVENT = "EXPIRED_EVENT"
    UNSUPPORTED_CLAIM = "UNSUPPORTED_CLAIM"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    OUTSIDE_PHASE_1_SCOPE = "OUTSIDE_PHASE_1_SCOPE"


class SourceHealthState(StrEnum):
    HEALTHY = "HEALTHY"
    WARNING = "WARNING"
    FAILED = "FAILED"

